// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countOwnedApplications = `-- name: CountOwnedApplications :one
SELECT count(*) FROM applications WHERE owner_id = $1
`

func (q *Queries) CountOwnedApplications(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedApplications, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (id, owner_id, bot_user_id, name, description, icon_url, is_public)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, bot_user_id, name, description, icon_url, is_public, created_at, updated_at
`

type CreateApplicationParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	BotUserID   uuid.UUID
	Name        string
	Description string
	IconUrl     *string
	IsPublic    bool
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.OwnerID,
		arg.BotUserID,
		arg.Name,
		arg.Description,
		arg.IconUrl,
		arg.IsPublic,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BotUserID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createApplicationCommand = `-- name: CreateApplicationCommand :one
INSERT INTO application_commands (id, application_id, name, description, options)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, application_id, name, description, options, created_at
`

type CreateApplicationCommandParams struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
	Name          string
	Description   string
	Options       []byte
}

func (q *Queries) CreateApplicationCommand(ctx context.Context, arg CreateApplicationCommandParams) (ApplicationCommand, error) {
	row := q.db.QueryRow(ctx, createApplicationCommand,
		arg.ID,
		arg.ApplicationID,
		arg.Name,
		arg.Description,
		arg.Options,
	)
	var i ApplicationCommand
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.Description,
		&i.Options,
		&i.CreatedAt,
	)
	return i, err
}

const createBotUser = `-- name: CreateBotUser :one
INSERT INTO users (id, username, email, password_hash, display_name, is_bot)
VALUES ($1, $2, $3, '', $4, true)
RETURNING id, username, email, password_hash, display_name, bio, pronouns, avatar_url, is_instance_admin, email_verified_at, created_at, updated_at, deleted_at, is_bot
`

type CreateBotUserParams struct {
	ID          uuid.UUID
	Username    string
	Email       string
	DisplayName string
}

func (q *Queries) CreateBotUser(ctx context.Context, arg CreateBotUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createBotUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Bio,
		&i.Pronouns,
		&i.AvatarUrl,
		&i.IsInstanceAdmin,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsBot,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const deleteApplicationCommands = `-- name: DeleteApplicationCommands :exec
DELETE FROM application_commands WHERE application_id = $1
`

func (q *Queries) DeleteApplicationCommands(ctx context.Context, applicationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplicationCommands, applicationID)
	return err
}

const getApplication = `-- name: GetApplication :one
SELECT id, owner_id, bot_user_id, name, description, icon_url, is_public, created_at, updated_at FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BotUserID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByBot = `-- name: GetApplicationByBot :one
SELECT id, owner_id, bot_user_id, name, description, icon_url, is_public, created_at, updated_at FROM applications WHERE bot_user_id = $1
`

func (q *Queries) GetApplicationByBot(ctx context.Context, botUserID uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByBot, botUserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BotUserID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationCommand = `-- name: GetApplicationCommand :one
SELECT id, application_id, name, description, options, created_at FROM application_commands WHERE application_id = $1 AND name = $2
`

type GetApplicationCommandParams struct {
	ApplicationID uuid.UUID
	Name          string
}

func (q *Queries) GetApplicationCommand(ctx context.Context, arg GetApplicationCommandParams) (ApplicationCommand, error) {
	row := q.db.QueryRow(ctx, getApplicationCommand, arg.ApplicationID, arg.Name)
	var i ApplicationCommand
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.Description,
		&i.Options,
		&i.CreatedAt,
	)
	return i, err
}

const listApplicationCommands = `-- name: ListApplicationCommands :many
SELECT id, application_id, name, description, options, created_at FROM application_commands WHERE application_id = $1 ORDER BY name
`

func (q *Queries) ListApplicationCommands(ctx context.Context, applicationID uuid.UUID) ([]ApplicationCommand, error) {
	rows, err := q.db.Query(ctx, listApplicationCommands, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationCommand{}
	for rows.Next() {
		var i ApplicationCommand
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.Description,
			&i.Options,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommandsForApplications = `-- name: ListCommandsForApplications :many
SELECT id, application_id, name, description, options, created_at FROM application_commands WHERE application_id = ANY($1::uuid[]) ORDER BY name, application_id
`

func (q *Queries) ListCommandsForApplications(ctx context.Context, applicationIds []uuid.UUID) ([]ApplicationCommand, error) {
	rows, err := q.db.Query(ctx, listCommandsForApplications, applicationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationCommand{}
	for rows.Next() {
		var i ApplicationCommand
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.Description,
			&i.Options,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedApplications = `-- name: ListOwnedApplications :many
SELECT id, owner_id, bot_user_id, name, description, icon_url, is_public, created_at, updated_at FROM applications WHERE owner_id = $1 ORDER BY created_at
`

func (q *Queries) ListOwnedApplications(ctx context.Context, ownerID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listOwnedApplications, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.BotUserID,
			&i.Name,
			&i.Description,
			&i.IconUrl,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceApplications = `-- name: ListPlaceApplications :many
SELECT a.id, a.owner_id, a.bot_user_id, a.name, a.description, a.icon_url, a.is_public, a.created_at, a.updated_at
FROM applications a
JOIN place_members m ON m.user_id = a.bot_user_id
WHERE m.place_id = $1
ORDER BY a.name, a.id
`

// Applications whose bot is a member of the place.
func (q *Queries) ListPlaceApplications(ctx context.Context, placeID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listPlaceApplications, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.BotUserID,
			&i.Name,
			&i.Description,
			&i.IconUrl,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET name        = COALESCE($1::text, name),
    description = COALESCE($2::text, description),
    icon_url    = CASE WHEN $3::text IS NULL THEN icon_url
                       ELSE NULLIF($3::text, '') END,
    is_public   = COALESCE($4::boolean, is_public),
    updated_at  = now()
WHERE id = $5
RETURNING id, owner_id, bot_user_id, name, description, icon_url, is_public, created_at, updated_at
`

type UpdateApplicationParams struct {
	Name        *string
	Description *string
	IconUrl     *string
	IsPublic    *bool
	ID          uuid.UUID
}

// Nullable params leave the column unchanged; an empty icon_url clears it.
func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.Name,
		arg.Description,
		arg.IconUrl,
		arg.IsPublic,
		arg.ID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BotUserID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
