// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMessageAttachments = `-- name: AddMessageAttachments :exec
INSERT INTO message_attachments (message_id, upload_id, position)
SELECT $1::uuid, a.id, (a.ord - 1)::smallint
FROM unnest($2::uuid[]) WITH ORDINALITY AS a(id, ord)
`

type AddMessageAttachmentsParams struct {
	MessageID uuid.UUID
	UploadIds []uuid.UUID
}

func (q *Queries) AddMessageAttachments(ctx context.Context, arg AddMessageAttachmentsParams) error {
	_, err := q.db.Exec(ctx, addMessageAttachments, arg.MessageID, arg.UploadIds)
	return err
}

const addPostAttachments = `-- name: AddPostAttachments :exec
INSERT INTO post_attachments (post_id, upload_id, position)
SELECT $1::uuid, a.id, (a.ord - 1)::smallint
FROM unnest($2::uuid[]) WITH ORDINALITY AS a(id, ord)
`

type AddPostAttachmentsParams struct {
	PostID    uuid.UUID
	UploadIds []uuid.UUID
}

func (q *Queries) AddPostAttachments(ctx context.Context, arg AddPostAttachmentsParams) error {
	_, err := q.db.Exec(ctx, addPostAttachments, arg.PostID, arg.UploadIds)
	return err
}

const listAttachedUploads = `-- name: ListAttachedUploads :many
SELECT upload_id FROM message_attachments WHERE upload_id = ANY($1::uuid[])
UNION ALL
SELECT upload_id FROM post_attachments WHERE upload_id = ANY($1::uuid[])
`

// The given uploads that already belong to a message or post.
func (q *Queries) ListAttachedUploads(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAttachedUploads, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var upload_id uuid.UUID
		if err := rows.Scan(&upload_id); err != nil {
			return nil, err
		}
		items = append(items, upload_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkPreviews = `-- name: ListLinkPreviews :many
SELECT lp.url, lp.status, lp.kind, lp.final_url, lp.site_name, lp.title, lp.description, lp.theme_color,
       lp.large_image, lp.fetched_at, u.url AS image_url, u.width AS image_width, u.height AS image_height
FROM link_previews lp
LEFT JOIN uploads u ON u.id = lp.image_upload_id
WHERE lp.url = ANY($1::text[])
`

type ListLinkPreviewsRow struct {
	Url         string
	Status      string
	Kind        string
	FinalUrl    string
	SiteName    string
	Title       string
	Description string
	ThemeColor  string
	LargeImage  bool
	FetchedAt   time.Time
	ImageUrl    *string
	ImageWidth  *int32
	ImageHeight *int32
}

func (q *Queries) ListLinkPreviews(ctx context.Context, urls []string) ([]ListLinkPreviewsRow, error) {
	rows, err := q.db.Query(ctx, listLinkPreviews, urls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinkPreviewsRow{}
	for rows.Next() {
		var i ListLinkPreviewsRow
		if err := rows.Scan(
			&i.Url,
			&i.Status,
			&i.Kind,
			&i.FinalUrl,
			&i.SiteName,
			&i.Title,
			&i.Description,
			&i.ThemeColor,
			&i.LargeImage,
			&i.FetchedAt,
			&i.ImageUrl,
			&i.ImageWidth,
			&i.ImageHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageAttachments = `-- name: ListMessageAttachments :many
SELECT ma.message_id, u.id, u.storage_key, u.url, u.purpose, u.uploader_id, u.content_type, u.size_bytes, u.width, u.height, u.created_at, u.filename
FROM message_attachments ma
JOIN uploads u ON u.id = ma.upload_id
WHERE ma.message_id = ANY($1::uuid[])
ORDER BY ma.message_id, ma.position
`

type ListMessageAttachmentsRow struct {
	MessageID uuid.UUID
	Upload    Upload
}

func (q *Queries) ListMessageAttachments(ctx context.Context, messageIds []uuid.UUID) ([]ListMessageAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listMessageAttachments, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageAttachmentsRow{}
	for rows.Next() {
		var i ListMessageAttachmentsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Upload.ID,
			&i.Upload.StorageKey,
			&i.Upload.Url,
			&i.Upload.Purpose,
			&i.Upload.UploaderID,
			&i.Upload.ContentType,
			&i.Upload.SizeBytes,
			&i.Upload.Width,
			&i.Upload.Height,
			&i.Upload.CreatedAt,
			&i.Upload.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostAttachments = `-- name: ListPostAttachments :many
SELECT pa.post_id, u.id, u.storage_key, u.url, u.purpose, u.uploader_id, u.content_type, u.size_bytes, u.width, u.height, u.created_at, u.filename
FROM post_attachments pa
JOIN uploads u ON u.id = pa.upload_id
WHERE pa.post_id = ANY($1::uuid[])
ORDER BY pa.post_id, pa.position
`

type ListPostAttachmentsRow struct {
	PostID uuid.UUID
	Upload Upload
}

func (q *Queries) ListPostAttachments(ctx context.Context, postIds []uuid.UUID) ([]ListPostAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listPostAttachments, postIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostAttachmentsRow{}
	for rows.Next() {
		var i ListPostAttachmentsRow
		if err := rows.Scan(
			&i.PostID,
			&i.Upload.ID,
			&i.Upload.StorageKey,
			&i.Upload.Url,
			&i.Upload.Purpose,
			&i.Upload.UploaderID,
			&i.Upload.ContentType,
			&i.Upload.SizeBytes,
			&i.Upload.Width,
			&i.Upload.Height,
			&i.Upload.CreatedAt,
			&i.Upload.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadsByIDs = `-- name: ListUploadsByIDs :many
SELECT id, storage_key, url, purpose, uploader_id, content_type, size_bytes, width, height, created_at, filename FROM uploads WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListUploadsByIDs(ctx context.Context, ids []uuid.UUID) ([]Upload, error) {
	rows, err := q.db.Query(ctx, listUploadsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Upload{}
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.Url,
			&i.Purpose,
			&i.UploaderID,
			&i.ContentType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLinkPreview = `-- name: UpsertLinkPreview :exec
INSERT INTO link_previews (url, status, kind, final_url, site_name, title, description, theme_color, large_image,
                           image_upload_id, fetched_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, now())
ON CONFLICT (url) DO UPDATE
SET status          = EXCLUDED.status,
    kind            = EXCLUDED.kind,
    final_url       = EXCLUDED.final_url,
    site_name       = EXCLUDED.site_name,
    title           = EXCLUDED.title,
    description     = EXCLUDED.description,
    theme_color     = EXCLUDED.theme_color,
    large_image     = EXCLUDED.large_image,
    image_upload_id = EXCLUDED.image_upload_id,
    fetched_at      = now()
`

type UpsertLinkPreviewParams struct {
	Url           string
	Status        string
	Kind          string
	FinalUrl      string
	SiteName      string
	Title         string
	Description   string
	ThemeColor    string
	LargeImage    bool
	ImageUploadID *uuid.UUID
}

func (q *Queries) UpsertLinkPreview(ctx context.Context, arg UpsertLinkPreviewParams) error {
	_, err := q.db.Exec(ctx, upsertLinkPreview,
		arg.Url,
		arg.Status,
		arg.Kind,
		arg.FinalUrl,
		arg.SiteName,
		arg.Title,
		arg.Description,
		arg.ThemeColor,
		arg.LargeImage,
		arg.ImageUploadID,
	)
	return err
}
