// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bans.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteBan = `-- name: DeleteBan :execrows
DELETE FROM place_bans WHERE place_id = $1 AND user_id = $2
`

type DeleteBanParams struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteBan(ctx context.Context, arg DeleteBanParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBan, arg.PlaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isBanned = `-- name: IsBanned :one
SELECT EXISTS (SELECT 1 FROM place_bans WHERE place_id = $1 AND user_id = $2)
`

type IsBannedParams struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) IsBanned(ctx context.Context, arg IsBannedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBanned, arg.PlaceID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBans = `-- name: ListBans :many
SELECT b.place_id, b.user_id, b.reason, b.banned_by, b.created_at, u.id, u.username, u.email, u.password_hash, u.display_name, u.bio, u.pronouns, u.avatar_url, u.is_instance_admin, u.email_verified_at, u.created_at, u.updated_at, u.deleted_at
FROM place_bans b
JOIN users u ON u.id = b.user_id
WHERE b.place_id = $1
ORDER BY b.created_at DESC
LIMIT $3 OFFSET $2
`

type ListBansParams struct {
	PlaceID uuid.UUID
	Off     int32
	Lim     int32
}

type ListBansRow struct {
	PlaceBan PlaceBan
	User     User
}

func (q *Queries) ListBans(ctx context.Context, arg ListBansParams) ([]ListBansRow, error) {
	rows, err := q.db.Query(ctx, listBans, arg.PlaceID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBansRow{}
	for rows.Next() {
		var i ListBansRow
		if err := rows.Scan(
			&i.PlaceBan.PlaceID,
			&i.PlaceBan.UserID,
			&i.PlaceBan.Reason,
			&i.PlaceBan.BannedBy,
			&i.PlaceBan.CreatedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.DisplayName,
			&i.User.Bio,
			&i.User.Pronouns,
			&i.User.AvatarUrl,
			&i.User.IsInstanceAdmin,
			&i.User.EmailVerifiedAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBan = `-- name: UpsertBan :exec
INSERT INTO place_bans (place_id, user_id, reason, banned_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (place_id, user_id) DO UPDATE
SET reason = EXCLUDED.reason, banned_by = EXCLUDED.banned_by, created_at = now()
`

type UpsertBanParams struct {
	PlaceID  uuid.UUID
	UserID   uuid.UUID
	Reason   string
	BannedBy *uuid.UUID
}

func (q *Queries) UpsertBan(ctx context.Context, arg UpsertBanParams) error {
	_, err := q.db.Exec(ctx, upsertBan,
		arg.PlaceID,
		arg.UserID,
		arg.Reason,
		arg.BannedBy,
	)
	return err
}
