// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package store

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createNotification = `-- name: CreateNotification :batchexec
INSERT INTO notifications (id, user_id, kind, place_id, topic_id, post_id, actor_id, data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT DO NOTHING
`

type CreateNotificationBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateNotificationParams struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Kind    string
	PlaceID *uuid.UUID
	TopicID *uuid.UUID
	PostID  *uuid.UUID
	ActorID *uuid.UUID
	Data    []byte
}

// Duplicate reaction notifications are silently skipped.
func (q *Queries) CreateNotification(ctx context.Context, arg []CreateNotificationParams) *CreateNotificationBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.UserID,
			a.Kind,
			a.PlaceID,
			a.TopicID,
			a.PostID,
			a.ActorID,
			a.Data,
		}
		batch.Queue(createNotification, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateNotificationBatchResults{br, len(arg), false}
}

func (b *CreateNotificationBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateNotificationBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
