// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package store

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createNotification = `-- name: CreateNotification :batchone
INSERT INTO notifications (id, user_id, kind, place_id, topic_id, post_id, channel_id, message_id, actor_id, data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT DO NOTHING
RETURNING id, user_id, kind, place_id, topic_id, post_id, actor_id, data, read_at, created_at, channel_id, message_id
`

type CreateNotificationBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateNotificationParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	PlaceID   *uuid.UUID
	TopicID   *uuid.UUID
	PostID    *uuid.UUID
	ChannelID *uuid.UUID
	MessageID *uuid.UUID
	ActorID   *uuid.UUID
	Data      []byte
}

// Duplicate reaction and direct-message notifications are silently skipped (no row is
// returned).
func (q *Queries) CreateNotification(ctx context.Context, arg []CreateNotificationParams) *CreateNotificationBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.UserID,
			a.Kind,
			a.PlaceID,
			a.TopicID,
			a.PostID,
			a.ChannelID,
			a.MessageID,
			a.ActorID,
			a.Data,
		}
		batch.Queue(createNotification, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateNotificationBatchResults{br, len(arg), false}
}

func (b *CreateNotificationBatchResults) QueryRow(f func(int, Notification, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i Notification
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.PlaceID,
			&i.TopicID,
			&i.PostID,
			&i.ActorID,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
			&i.ChannelID,
			&i.MessageID,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *CreateNotificationBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
