// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const adjustBoardCounts = `-- name: AdjustBoardCounts :exec
UPDATE boards
SET topic_count  = topic_count + $1::integer,
    post_count   = post_count + $2::integer,
    last_post_at = CASE WHEN $3::boolean THEN now() ELSE last_post_at END
WHERE id = $4
`

type AdjustBoardCountsParams struct {
	Topics int32
	Posts  int32
	Touch  bool
	ID     uuid.UUID
}

func (q *Queries) AdjustBoardCounts(ctx context.Context, arg AdjustBoardCountsParams) error {
	_, err := q.db.Exec(ctx, adjustBoardCounts,
		arg.Topics,
		arg.Posts,
		arg.Touch,
		arg.ID,
	)
	return err
}

const countBoards = `-- name: CountBoards :one
SELECT count(*) FROM boards WHERE place_id = $1
`

func (q *Queries) CountBoards(ctx context.Context, placeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBoards, placeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveBoardTopics = `-- name: CountLiveBoardTopics :one
SELECT count(*) FROM topics WHERE board_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLiveBoardTopics(ctx context.Context, boardID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveBoardTopics, boardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (id, place_id, parent_id, kind, slug, name, description, position,
                    reply_mode, solutions_enabled, is_nsfw)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11)
RETURNING id, place_id, parent_id, kind, slug, name, description, position, reply_mode, solutions_enabled, is_nsfw, is_public, topic_count, post_count, last_post_at, created_at, updated_at
`

type CreateBoardParams struct {
	ID               uuid.UUID
	PlaceID          uuid.UUID
	ParentID         *uuid.UUID
	Kind             string
	Slug             string
	Name             string
	Description      string
	Position         int32
	ReplyMode        string
	SolutionsEnabled bool
	IsNsfw           bool
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard,
		arg.ID,
		arg.PlaceID,
		arg.ParentID,
		arg.Kind,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Position,
		arg.ReplyMode,
		arg.SolutionsEnabled,
		arg.IsNsfw,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.ParentID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.ReplyMode,
		&i.SolutionsEnabled,
		&i.IsNsfw,
		&i.IsPublic,
		&i.TopicCount,
		&i.PostCount,
		&i.LastPostAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoard, id)
	return err
}

const deleteBoardOverwrite = `-- name: DeleteBoardOverwrite :execrows
DELETE FROM board_overwrites WHERE board_id = $1 AND role_id = $2
`

type DeleteBoardOverwriteParams struct {
	BoardID uuid.UUID
	RoleID  uuid.UUID
}

func (q *Queries) DeleteBoardOverwrite(ctx context.Context, arg DeleteBoardOverwriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoardOverwrite, arg.BoardID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBoard = `-- name: GetBoard :one
SELECT id, place_id, parent_id, kind, slug, name, description, position, reply_mode, solutions_enabled, is_nsfw, is_public, topic_count, post_count, last_post_at, created_at, updated_at FROM boards WHERE id = $1
`

func (q *Queries) GetBoard(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.ParentID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.ReplyMode,
		&i.SolutionsEnabled,
		&i.IsNsfw,
		&i.IsPublic,
		&i.TopicCount,
		&i.PostCount,
		&i.LastPostAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoardOverwrites = `-- name: ListBoardOverwrites :many
SELECT board_id, role_id, place_id, allow, deny FROM board_overwrites WHERE place_id = $1
`

func (q *Queries) ListBoardOverwrites(ctx context.Context, placeID uuid.UUID) ([]BoardOverwrite, error) {
	rows, err := q.db.Query(ctx, listBoardOverwrites, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardOverwrite{}
	for rows.Next() {
		var i BoardOverwrite
		if err := rows.Scan(
			&i.BoardID,
			&i.RoleID,
			&i.PlaceID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoards = `-- name: ListBoards :many
SELECT id, place_id, parent_id, kind, slug, name, description, position, reply_mode, solutions_enabled, is_nsfw, is_public, topic_count, post_count, last_post_at, created_at, updated_at FROM boards WHERE place_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListBoards(ctx context.Context, placeID uuid.UUID) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoards, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.ParentID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Position,
			&i.ReplyMode,
			&i.SolutionsEnabled,
			&i.IsNsfw,
			&i.IsPublic,
			&i.TopicCount,
			&i.PostCount,
			&i.LastPostAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBoardPosition = `-- name: NextBoardPosition :one
SELECT (COALESCE(MAX(position), -1) + 1)::integer FROM boards
WHERE place_id = $1 AND parent_id IS NOT DISTINCT FROM $2::uuid
`

type NextBoardPositionParams struct {
	PlaceID  uuid.UUID
	ParentID *uuid.UUID
}

func (q *Queries) NextBoardPosition(ctx context.Context, arg NextBoardPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextBoardPosition, arg.PlaceID, arg.ParentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setPublicBoards = `-- name: SetPublicBoards :exec
UPDATE boards SET is_public = (id = ANY($1::uuid[]))
WHERE place_id = $2 AND is_public <> (id = ANY($1::uuid[]))
`

type SetPublicBoardsParams struct {
	PublicIds []uuid.UUID
	PlaceID   uuid.UUID
}

func (q *Queries) SetPublicBoards(ctx context.Context, arg SetPublicBoardsParams) error {
	_, err := q.db.Exec(ctx, setPublicBoards, arg.PublicIds, arg.PlaceID)
	return err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET name              = COALESCE($1::text, name),
    slug              = COALESCE($2::text, slug),
    description       = COALESCE($3::text, description),
    position          = COALESCE($4::integer, position),
    reply_mode        = COALESCE($5::text, reply_mode),
    solutions_enabled = COALESCE($6::boolean, solutions_enabled),
    is_nsfw           = COALESCE($7::boolean, is_nsfw),
    parent_id         = CASE WHEN $8::boolean THEN $9::uuid ELSE parent_id END,
    updated_at        = now()
WHERE id = $10
RETURNING id, place_id, parent_id, kind, slug, name, description, position, reply_mode, solutions_enabled, is_nsfw, is_public, topic_count, post_count, last_post_at, created_at, updated_at
`

type UpdateBoardParams struct {
	Name             *string
	Slug             *string
	Description      *string
	Position         *int32
	ReplyMode        *string
	SolutionsEnabled *bool
	IsNsfw           *bool
	SetParent        bool
	ParentID         *uuid.UUID
	ID               uuid.UUID
}

// Nullable params leave the column unchanged; set_parent controls parent_id separately so
// a board can be moved to the root.
func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Position,
		arg.ReplyMode,
		arg.SolutionsEnabled,
		arg.IsNsfw,
		arg.SetParent,
		arg.ParentID,
		arg.ID,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.ParentID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.ReplyMode,
		&i.SolutionsEnabled,
		&i.IsNsfw,
		&i.IsPublic,
		&i.TopicCount,
		&i.PostCount,
		&i.LastPostAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBoardOverwrite = `-- name: UpsertBoardOverwrite :one
INSERT INTO board_overwrites (board_id, role_id, place_id, allow, deny)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (board_id, role_id) DO UPDATE SET allow = EXCLUDED.allow, deny = EXCLUDED.deny
RETURNING board_id, role_id, place_id, allow, deny
`

type UpsertBoardOverwriteParams struct {
	BoardID uuid.UUID
	RoleID  uuid.UUID
	PlaceID uuid.UUID
	Allow   int64
	Deny    int64
}

func (q *Queries) UpsertBoardOverwrite(ctx context.Context, arg UpsertBoardOverwriteParams) (BoardOverwrite, error) {
	row := q.db.QueryRow(ctx, upsertBoardOverwrite,
		arg.BoardID,
		arg.RoleID,
		arg.PlaceID,
		arg.Allow,
		arg.Deny,
	)
	var i BoardOverwrite
	err := row.Scan(
		&i.BoardID,
		&i.RoleID,
		&i.PlaceID,
		&i.Allow,
		&i.Deny,
	)
	return i, err
}
