// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const ackChannel = `-- name: AckChannel :exec
INSERT INTO channel_reads (user_id, channel_id, last_read_message_id, mention_count)
VALUES ($1, $2, $3, 0)
ON CONFLICT (user_id, channel_id) DO UPDATE
SET last_read_message_id = GREATEST(channel_reads.last_read_message_id, EXCLUDED.last_read_message_id),
    updated_at           = now()
`

type AckChannelParams struct {
	UserID    uuid.UUID
	ChannelID uuid.UUID
	MessageID *uuid.UUID
}

// Read positions never move backwards.
func (q *Queries) AckChannel(ctx context.Context, arg AckChannelParams) error {
	_, err := q.db.Exec(ctx, ackChannel, arg.UserID, arg.ChannelID, arg.MessageID)
	return err
}

const addChannelRecipient = `-- name: AddChannelRecipient :execrows
INSERT INTO channel_recipients (channel_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddChannelRecipientParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) AddChannelRecipient(ctx context.Context, arg AddChannelRecipientParams) (int64, error) {
	result, err := q.db.Exec(ctx, addChannelRecipient, arg.ChannelID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addMentions = `-- name: AddMentions :exec
INSERT INTO channel_reads (user_id, channel_id, mention_count)
SELECT unnest($1::uuid[]), $2::uuid, 1
ON CONFLICT (user_id, channel_id) DO UPDATE SET mention_count = channel_reads.mention_count + 1
WHERE channel_reads.last_read_message_id IS NULL OR channel_reads.last_read_message_id < $3::uuid
`

type AddMentionsParams struct {
	UserIds   []uuid.UUID
	ChannelID uuid.UUID
	MessageID uuid.UUID
}

// Counts message_id as an unread mention for each user who has not read past it.
func (q *Queries) AddMentions(ctx context.Context, arg AddMentionsParams) error {
	_, err := q.db.Exec(ctx, addMentions, arg.UserIds, arg.ChannelID, arg.MessageID)
	return err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (id, place_id, parent_id, kind, name, topic, position, is_nsfw, owner_id,
                      thread_message_id, dm_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11)
RETURNING id, place_id, parent_id, kind, name, topic, position, is_nsfw, owner_id, thread_message_id, is_archived, dm_key, last_message_id, last_message_at, message_count, created_at, updated_at
`

type CreateChannelParams struct {
	ID              uuid.UUID
	PlaceID         *uuid.UUID
	ParentID        *uuid.UUID
	Kind            string
	Name            string
	Topic           string
	Position        int32
	IsNsfw          bool
	OwnerID         *uuid.UUID
	ThreadMessageID *uuid.UUID
	DmKey           *string
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.PlaceID,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.Topic,
		arg.Position,
		arg.IsNsfw,
		arg.OwnerID,
		arg.ThreadMessageID,
		arg.DmKey,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsNsfw,
		&i.OwnerID,
		&i.ThreadMessageID,
		&i.IsArchived,
		&i.DmKey,
		&i.LastMessageID,
		&i.LastMessageAt,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const deleteChannelOverwrite = `-- name: DeleteChannelOverwrite :execrows
DELETE FROM channel_overwrites WHERE channel_id = $1 AND role_id = $2
`

type DeleteChannelOverwriteParams struct {
	ChannelID uuid.UUID
	RoleID    uuid.UUID
}

func (q *Queries) DeleteChannelOverwrite(ctx context.Context, arg DeleteChannelOverwriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelOverwrite, arg.ChannelID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChannelReadsFor = `-- name: DeleteChannelReadsFor :exec
DELETE FROM channel_reads WHERE channel_id = $1 AND user_id = $2
`

type DeleteChannelReadsForParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) DeleteChannelReadsFor(ctx context.Context, arg DeleteChannelReadsForParams) error {
	_, err := q.db.Exec(ctx, deleteChannelReadsFor, arg.ChannelID, arg.UserID)
	return err
}

const filterPresenceAudience = `-- name: FilterPresenceAudience :many
SELECT u.id FROM users u
WHERE u.id = ANY($1::uuid[])
  AND (u.id = $2
       OR EXISTS (SELECT 1 FROM place_members a
                  JOIN place_members b ON b.place_id = a.place_id
                  JOIN places p ON p.id = a.place_id
                  WHERE a.user_id = $2 AND b.user_id = u.id AND p.deleted_at IS NULL)
       OR EXISTS (SELECT 1 FROM channel_recipients r1
                  JOIN channel_recipients r2 ON r2.channel_id = r1.channel_id
                  WHERE r1.user_id = $2 AND r2.user_id = u.id))
`

type FilterPresenceAudienceParams struct {
	UserIds  []uuid.UUID
	ViewerID uuid.UUID
}

// Returns the subset of user_ids whose presence the viewer may see: themselves, people
// sharing a place with them, and their DM partners.
func (q *Queries) FilterPresenceAudience(ctx context.Context, arg FilterPresenceAudienceParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, filterPresenceAudience, arg.UserIds, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannel = `-- name: GetChannel :one
SELECT id, place_id, parent_id, kind, name, topic, position, is_nsfw, owner_id, thread_message_id, is_archived, dm_key, last_message_id, last_message_at, message_count, created_at, updated_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsNsfw,
		&i.OwnerID,
		&i.ThreadMessageID,
		&i.IsArchived,
		&i.DmKey,
		&i.LastMessageID,
		&i.LastMessageAt,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelForUpdate = `-- name: GetChannelForUpdate :one
SELECT id, place_id, parent_id, kind, name, topic, position, is_nsfw, owner_id, thread_message_id, is_archived, dm_key, last_message_id, last_message_at, message_count, created_at, updated_at FROM channels WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetChannelForUpdate(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelForUpdate, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsNsfw,
		&i.OwnerID,
		&i.ThreadMessageID,
		&i.IsArchived,
		&i.DmKey,
		&i.LastMessageID,
		&i.LastMessageAt,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDMChannelByKey = `-- name: GetDMChannelByKey :one
SELECT id, place_id, parent_id, kind, name, topic, position, is_nsfw, owner_id, thread_message_id, is_archived, dm_key, last_message_id, last_message_at, message_count, created_at, updated_at FROM channels WHERE dm_key = $1
`

func (q *Queries) GetDMChannelByKey(ctx context.Context, dmKey *string) (Channel, error) {
	row := q.db.QueryRow(ctx, getDMChannelByKey, dmKey)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsNsfw,
		&i.OwnerID,
		&i.ThreadMessageID,
		&i.IsArchived,
		&i.DmKey,
		&i.LastMessageID,
		&i.LastMessageAt,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isChannelRecipient = `-- name: IsChannelRecipient :one
SELECT EXISTS (SELECT 1 FROM channel_recipients WHERE channel_id = $1 AND user_id = $2)
`

type IsChannelRecipientParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) IsChannelRecipient(ctx context.Context, arg IsChannelRecipientParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelRecipient, arg.ChannelID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const leaveAllGroupDMs = `-- name: LeaveAllGroupDMs :many
DELETE FROM channel_recipients r
USING channels c
WHERE r.channel_id = c.id AND c.kind = 'group_dm' AND r.user_id = $1
RETURNING r.channel_id
`

func (q *Queries) LeaveAllGroupDMs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, leaveAllGroupDMs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var channel_id uuid.UUID
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelOverwrites = `-- name: ListChannelOverwrites :many
SELECT channel_id, role_id, place_id, allow, deny FROM channel_overwrites WHERE place_id = $1
`

func (q *Queries) ListChannelOverwrites(ctx context.Context, placeID uuid.UUID) ([]ChannelOverwrite, error) {
	rows, err := q.db.Query(ctx, listChannelOverwrites, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelOverwrite{}
	for rows.Next() {
		var i ChannelOverwrite
		if err := rows.Scan(
			&i.ChannelID,
			&i.RoleID,
			&i.PlaceID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelReads = `-- name: ListChannelReads :many
SELECT user_id, channel_id, last_read_message_id, mention_count, updated_at FROM channel_reads WHERE user_id = $1 AND channel_id = ANY($2::uuid[])
`

type ListChannelReadsParams struct {
	UserID     uuid.UUID
	ChannelIds []uuid.UUID
}

func (q *Queries) ListChannelReads(ctx context.Context, arg ListChannelReadsParams) ([]ChannelRead, error) {
	rows, err := q.db.Query(ctx, listChannelReads, arg.UserID, arg.ChannelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelRead{}
	for rows.Next() {
		var i ChannelRead
		if err := rows.Scan(
			&i.UserID,
			&i.ChannelID,
			&i.LastReadMessageID,
			&i.MentionCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelReceipts = `-- name: ListChannelReceipts :many
SELECT user_id, channel_id, last_read_message_id, mention_count, updated_at FROM channel_reads
WHERE channel_id = $1 AND last_read_message_id IS NOT NULL
ORDER BY user_id
`

func (q *Queries) ListChannelReceipts(ctx context.Context, channelID uuid.UUID) ([]ChannelRead, error) {
	rows, err := q.db.Query(ctx, listChannelReceipts, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelRead{}
	for rows.Next() {
		var i ChannelRead
		if err := rows.Scan(
			&i.UserID,
			&i.ChannelID,
			&i.LastReadMessageID,
			&i.MentionCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelRecipients = `-- name: ListChannelRecipients :many
SELECT channel_id, user_id, joined_at FROM channel_recipients
WHERE channel_id = ANY($1::uuid[])
ORDER BY joined_at, user_id
`

func (q *Queries) ListChannelRecipients(ctx context.Context, channelIds []uuid.UUID) ([]ChannelRecipient, error) {
	rows, err := q.db.Query(ctx, listChannelRecipients, channelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelRecipient{}
	for rows.Next() {
		var i ChannelRecipient
		if err := rows.Scan(&i.ChannelID, &i.UserID, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDMPartnerIDs = `-- name: ListDMPartnerIDs :many
SELECT DISTINCT r2.user_id
FROM channel_recipients r1
JOIN channel_recipients r2 ON r2.channel_id = r1.channel_id
WHERE r1.user_id = $1 AND r2.user_id <> $1
`

func (q *Queries) ListDMPartnerIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDMPartnerIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceChannels = `-- name: ListPlaceChannels :many
SELECT id, place_id, parent_id, kind, name, topic, position, is_nsfw, owner_id, thread_message_id, is_archived, dm_key, last_message_id, last_message_at, message_count, created_at, updated_at FROM channels
WHERE place_id = $1 AND kind IN ('category', 'text')
ORDER BY position, created_at
`

// Categories and text channels; threads are listed per parent channel.
func (q *Queries) ListPlaceChannels(ctx context.Context, placeID *uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listPlaceChannels, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.Topic,
			&i.Position,
			&i.IsNsfw,
			&i.OwnerID,
			&i.ThreadMessageID,
			&i.IsArchived,
			&i.DmKey,
			&i.LastMessageID,
			&i.LastMessageAt,
			&i.MessageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceMemberIDs = `-- name: ListPlaceMemberIDs :many
SELECT user_id FROM place_members WHERE place_id = $1
`

func (q *Queries) ListPlaceMemberIDs(ctx context.Context, placeID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPlaceMemberIDs, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreads = `-- name: ListThreads :many
SELECT id, place_id, parent_id, kind, name, topic, position, is_nsfw, owner_id, thread_message_id, is_archived, dm_key, last_message_id, last_message_at, message_count, created_at, updated_at FROM channels
WHERE parent_id = $1 AND kind = 'thread' AND is_archived = $2
ORDER BY last_message_at DESC NULLS LAST, id DESC
LIMIT $4 OFFSET $3
`

type ListThreadsParams struct {
	ParentID *uuid.UUID
	Archived bool
	Off      int32
	Lim      int32
}

func (q *Queries) ListThreads(ctx context.Context, arg ListThreadsParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listThreads,
		arg.ParentID,
		arg.Archived,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.Topic,
			&i.Position,
			&i.IsNsfw,
			&i.OwnerID,
			&i.ThreadMessageID,
			&i.IsArchived,
			&i.DmKey,
			&i.LastMessageID,
			&i.LastMessageAt,
			&i.MessageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsByMessage = `-- name: ListThreadsByMessage :many
SELECT id, place_id, parent_id, kind, name, topic, position, is_nsfw, owner_id, thread_message_id, is_archived, dm_key, last_message_id, last_message_at, message_count, created_at, updated_at FROM channels WHERE thread_message_id = ANY($1::uuid[])
`

func (q *Queries) ListThreadsByMessage(ctx context.Context, messageIds []uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listThreadsByMessage, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.Topic,
			&i.Position,
			&i.IsNsfw,
			&i.OwnerID,
			&i.ThreadMessageID,
			&i.IsArchived,
			&i.DmKey,
			&i.LastMessageID,
			&i.LastMessageAt,
			&i.MessageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDMChannels = `-- name: ListUserDMChannels :many
SELECT c.id, c.place_id, c.parent_id, c.kind, c.name, c.topic, c.position, c.is_nsfw, c.owner_id, c.thread_message_id, c.is_archived, c.dm_key, c.last_message_id, c.last_message_at, c.message_count, c.created_at, c.updated_at FROM channels c
JOIN channel_recipients r ON r.channel_id = c.id
WHERE r.user_id = $1
ORDER BY COALESCE(c.last_message_at, c.created_at) DESC, c.id DESC
LIMIT $3 OFFSET $2
`

type ListUserDMChannelsParams struct {
	UserID uuid.UUID
	Off    int32
	Lim    int32
}

// Most recently active first.
func (q *Queries) ListUserDMChannels(ctx context.Context, arg ListUserDMChannelsParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listUserDMChannels, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.Topic,
			&i.Position,
			&i.IsNsfw,
			&i.OwnerID,
			&i.ThreadMessageID,
			&i.IsArchived,
			&i.DmKey,
			&i.LastMessageID,
			&i.LastMessageAt,
			&i.MessageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPlaceIDs = `-- name: ListUserPlaceIDs :many
SELECT m.place_id FROM place_members m
JOIN places p ON p.id = m.place_id
WHERE m.user_id = $1 AND p.deleted_at IS NULL
`

func (q *Queries) ListUserPlaceIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserPlaceIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var place_id uuid.UUID
		if err := rows.Scan(&place_id); err != nil {
			return nil, err
		}
		items = append(items, place_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveChildChannelsToRoot = `-- name: MoveChildChannelsToRoot :exec
UPDATE channels SET parent_id = NULL, updated_at = now() WHERE parent_id = $1 AND kind = 'text'
`

func (q *Queries) MoveChildChannelsToRoot(ctx context.Context, parentID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, moveChildChannelsToRoot, parentID)
	return err
}

const nextChannelPosition = `-- name: NextChannelPosition :one
SELECT (COALESCE(MAX(position), -1) + 1)::integer FROM channels
WHERE place_id = $1 AND kind IN ('category', 'text')
  AND parent_id IS NOT DISTINCT FROM $2::uuid
`

type NextChannelPositionParams struct {
	PlaceID  *uuid.UUID
	ParentID *uuid.UUID
}

func (q *Queries) NextChannelPosition(ctx context.Context, arg NextChannelPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextChannelPosition, arg.PlaceID, arg.ParentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const reassignGroupDMOwnership = `-- name: ReassignGroupDMOwnership :exec
UPDATE channels
SET owner_id = (SELECT cr.user_id FROM channel_recipients cr
                WHERE cr.channel_id = channels.id AND cr.user_id <> $1
                ORDER BY cr.joined_at, cr.user_id LIMIT 1),
    updated_at = now()
WHERE kind = 'group_dm' AND owner_id = $1
`

// Hands group DMs owned by a departing user to the longest-standing other recipient.
func (q *Queries) ReassignGroupDMOwnership(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, reassignGroupDMOwnership, userID)
	return err
}

const recordChannelMessage = `-- name: RecordChannelMessage :exec
UPDATE channels
SET last_message_id = $1,
    last_message_at = $2,
    message_count   = message_count + 1,
    is_archived     = false
WHERE id = $3
`

type RecordChannelMessageParams struct {
	MessageID *uuid.UUID
	CreatedAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) RecordChannelMessage(ctx context.Context, arg RecordChannelMessageParams) error {
	_, err := q.db.Exec(ctx, recordChannelMessage, arg.MessageID, arg.CreatedAt, arg.ID)
	return err
}

const recountMentions = `-- name: RecountMentions :one
UPDATE channel_reads r
SET mention_count = (
    SELECT count(*)::integer FROM messages m
    WHERE m.channel_id = r.channel_id
      AND m.id > r.last_read_message_id
      AND CASE WHEN $1::boolean THEN m.author_id IS DISTINCT FROM r.user_id
               ELSE r.user_id = ANY(m.mention_ids) END
)
WHERE r.user_id = $2 AND r.channel_id = $3
RETURNING user_id, channel_id, last_read_message_id, mention_count, updated_at
`

type RecountMentionsParams struct {
	IsDm      bool
	UserID    uuid.UUID
	ChannelID uuid.UUID
}

// Counts unread messages that notified the user: every message from someone else in a
// DM, mentions and replies elsewhere.
func (q *Queries) RecountMentions(ctx context.Context, arg RecountMentionsParams) (ChannelRead, error) {
	row := q.db.QueryRow(ctx, recountMentions, arg.IsDm, arg.UserID, arg.ChannelID)
	var i ChannelRead
	err := row.Scan(
		&i.UserID,
		&i.ChannelID,
		&i.LastReadMessageID,
		&i.MentionCount,
		&i.UpdatedAt,
	)
	return i, err
}

const refreshChannelAfterDelete = `-- name: RefreshChannelAfterDelete :exec
UPDATE channels
SET message_count   = GREATEST(message_count - 1, 0),
    last_message_id = (SELECT m.id FROM messages m WHERE m.channel_id = $1 ORDER BY m.id DESC LIMIT 1),
    last_message_at = (SELECT m.created_at FROM messages m WHERE m.channel_id = $1 ORDER BY m.id DESC LIMIT 1)
WHERE channels.id = $1
`

func (q *Queries) RefreshChannelAfterDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshChannelAfterDelete, id)
	return err
}

const removeChannelRecipient = `-- name: RemoveChannelRecipient :execrows
DELETE FROM channel_recipients WHERE channel_id = $1 AND user_id = $2
`

type RemoveChannelRecipientParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveChannelRecipient(ctx context.Context, arg RemoveChannelRecipientParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeChannelRecipient, arg.ChannelID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sharesPlace = `-- name: SharesPlace :one
SELECT EXISTS (
    SELECT 1 FROM place_members a
    JOIN place_members b ON b.place_id = a.place_id
    JOIN places p ON p.id = a.place_id
    WHERE a.user_id = $1 AND b.user_id = $2 AND p.deleted_at IS NULL
)
`

type SharesPlaceParams struct {
	UserA uuid.UUID
	UserB uuid.UUID
}

func (q *Queries) SharesPlace(ctx context.Context, arg SharesPlaceParams) (bool, error) {
	row := q.db.QueryRow(ctx, sharesPlace, arg.UserA, arg.UserB)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name        = COALESCE($1::text, name),
    topic       = COALESCE($2::text, topic),
    position    = COALESCE($3::integer, position),
    is_nsfw     = COALESCE($4::boolean, is_nsfw),
    is_archived = COALESCE($5::boolean, is_archived),
    owner_id    = COALESCE($6::uuid, owner_id),
    parent_id   = CASE WHEN $7::boolean THEN $8::uuid ELSE parent_id END,
    updated_at  = now()
WHERE id = $9
RETURNING id, place_id, parent_id, kind, name, topic, position, is_nsfw, owner_id, thread_message_id, is_archived, dm_key, last_message_id, last_message_at, message_count, created_at, updated_at
`

type UpdateChannelParams struct {
	Name       *string
	Topic      *string
	Position   *int32
	IsNsfw     *bool
	IsArchived *bool
	OwnerID    *uuid.UUID
	SetParent  bool
	ParentID   *uuid.UUID
	ID         uuid.UUID
}

// Nullable params leave the column unchanged; set_parent controls parent_id separately so
// a channel can be moved out of its category.
func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.Name,
		arg.Topic,
		arg.Position,
		arg.IsNsfw,
		arg.IsArchived,
		arg.OwnerID,
		arg.SetParent,
		arg.ParentID,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.ParentID,
		&i.Kind,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsNsfw,
		&i.OwnerID,
		&i.ThreadMessageID,
		&i.IsArchived,
		&i.DmKey,
		&i.LastMessageID,
		&i.LastMessageAt,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChannelOverwrite = `-- name: UpsertChannelOverwrite :one
INSERT INTO channel_overwrites (channel_id, role_id, place_id, allow, deny)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (channel_id, role_id) DO UPDATE SET allow = EXCLUDED.allow, deny = EXCLUDED.deny
RETURNING channel_id, role_id, place_id, allow, deny
`

type UpsertChannelOverwriteParams struct {
	ChannelID uuid.UUID
	RoleID    uuid.UUID
	PlaceID   uuid.UUID
	Allow     int64
	Deny      int64
}

func (q *Queries) UpsertChannelOverwrite(ctx context.Context, arg UpsertChannelOverwriteParams) (ChannelOverwrite, error) {
	row := q.db.QueryRow(ctx, upsertChannelOverwrite,
		arg.ChannelID,
		arg.RoleID,
		arg.PlaceID,
		arg.Allow,
		arg.Deny,
	)
	var i ChannelOverwrite
	err := row.Scan(
		&i.ChannelID,
		&i.RoleID,
		&i.PlaceID,
		&i.Allow,
		&i.Deny,
	)
	return i, err
}
