// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adjustTopicVotes = `-- name: AdjustTopicVotes :exec
UPDATE topics
SET upvotes   = upvotes + $1::integer,
    downvotes = downvotes + $2::integer
WHERE id = $3
`

type AdjustTopicVotesParams struct {
	UpDelta   int32
	DownDelta int32
	ID        uuid.UUID
}

func (q *Queries) AdjustTopicVotes(ctx context.Context, arg AdjustTopicVotesParams) error {
	_, err := q.db.Exec(ctx, adjustTopicVotes, arg.UpDelta, arg.DownDelta, arg.ID)
	return err
}

const deleteTopicVote = `-- name: DeleteTopicVote :one
DELETE FROM topic_votes WHERE topic_id = $1 AND user_id = $2 RETURNING value
`

type DeleteTopicVoteParams struct {
	TopicID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteTopicVote(ctx context.Context, arg DeleteTopicVoteParams) (int16, error) {
	row := q.db.QueryRow(ctx, deleteTopicVote, arg.TopicID, arg.UserID)
	var value int16
	err := row.Scan(&value)
	return value, err
}

const getTopicVote = `-- name: GetTopicVote :one
SELECT value FROM topic_votes WHERE topic_id = $1 AND user_id = $2
`

type GetTopicVoteParams struct {
	TopicID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetTopicVote(ctx context.Context, arg GetTopicVoteParams) (int16, error) {
	row := q.db.QueryRow(ctx, getTopicVote, arg.TopicID, arg.UserID)
	var value int16
	err := row.Scan(&value)
	return value, err
}

const listBoardOverwritesForPlaces = `-- name: ListBoardOverwritesForPlaces :many
SELECT board_id, role_id, place_id, allow, deny FROM board_overwrites WHERE place_id = ANY($1::uuid[])
`

func (q *Queries) ListBoardOverwritesForPlaces(ctx context.Context, placeIds []uuid.UUID) ([]BoardOverwrite, error) {
	rows, err := q.db.Query(ctx, listBoardOverwritesForPlaces, placeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardOverwrite{}
	for rows.Next() {
		var i BoardOverwrite
		if err := rows.Scan(
			&i.BoardID,
			&i.RoleID,
			&i.PlaceID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardsForPlaces = `-- name: ListBoardsForPlaces :many
SELECT id, place_id, parent_id, kind, slug, name, description, position, reply_mode, solutions_enabled, is_nsfw, is_public, topic_count, post_count, last_post_at, created_at, updated_at FROM boards WHERE place_id = ANY($1::uuid[]) ORDER BY place_id, position, created_at
`

func (q *Queries) ListBoardsForPlaces(ctx context.Context, placeIds []uuid.UUID) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoardsForPlaces, placeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.ParentID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Position,
			&i.ReplyMode,
			&i.SolutionsEnabled,
			&i.IsNsfw,
			&i.IsPublic,
			&i.TopicCount,
			&i.PostCount,
			&i.LastPostAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedActive = `-- name: ListFeedActive :many
SELECT t.id, t.place_id, t.board_id, t.author_id, t.title, t.slug, t.tags, t.is_pinned, t.is_locked, t.is_archived, t.solution_post_id, t.post_count, t.last_post_number, t.last_post_at, t.last_poster_id, t.created_at, t.updated_at, t.deleted_at, t.deleted_by, t.upvotes, t.downvotes, t.score, t.hot_rank, t.controversy FROM topics t
WHERE t.board_id = ANY($1::uuid[])
  AND t.deleted_at IS NULL
  AND ($2::uuid IS NULL OR t.place_id = $2::uuid)
  AND ($3::boolean OR NOT t.is_archived)
  AND NOT ($4::boolean AND t.is_pinned)
  AND ($5::text IS NULL OR $5::text = ANY(t.tags))
  AND ($6::boolean IS NULL
       OR (t.solution_post_id IS NOT NULL) = $6::boolean)
  AND ($7::timestamptz IS NULL OR t.created_at >= $7::timestamptz)
  AND NOT ($8::boolean AND EXISTS (
        SELECT 1 FROM topic_reads r
        WHERE r.user_id = $9::uuid AND r.topic_id = t.id
          AND r.opened_at IS NOT NULL AND r.seen_post_number >= t.last_post_number))
  AND NOT COALESCE(
        (SELECT s.level = 'muted' FROM subscriptions s
         WHERE $10::boolean AND s.user_id = $9::uuid
           AND s.target_type = 'topic' AND s.target_id = t.id),
        t.board_id = ANY($11::uuid[]))
  AND ($12::uuid IS NULL
       OR (t.last_post_at, t.id) < ($13::timestamptz, $12::uuid))
ORDER BY t.last_post_at DESC, t.id DESC
LIMIT $14
`

type ListFeedActiveParams struct {
	BoardIds        []uuid.UUID
	PlaceID         *uuid.UUID
	IncludeArchived bool
	ExcludePinned   bool
	Tag             *string
	Solved          *bool
	Since           *time.Time
	HideRead        bool
	ViewerID        uuid.UUID
	ApplyMutes      bool
	MutedBoardIds   []uuid.UUID
	AfterID         *uuid.UUID
	AfterTime       *time.Time
	Lim             int32
}

// Latest reply first.
func (q *Queries) ListFeedActive(ctx context.Context, arg ListFeedActiveParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listFeedActive,
		arg.BoardIds,
		arg.PlaceID,
		arg.IncludeArchived,
		arg.ExcludePinned,
		arg.Tag,
		arg.Solved,
		arg.Since,
		arg.HideRead,
		arg.ViewerID,
		arg.ApplyMutes,
		arg.MutedBoardIds,
		arg.AfterID,
		arg.AfterTime,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Tags,
			&i.IsPinned,
			&i.IsLocked,
			&i.IsArchived,
			&i.SolutionPostID,
			&i.PostCount,
			&i.LastPostNumber,
			&i.LastPostAt,
			&i.LastPosterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Upvotes,
			&i.Downvotes,
			&i.Score,
			&i.HotRank,
			&i.Controversy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedControversial = `-- name: ListFeedControversial :many
SELECT t.id, t.place_id, t.board_id, t.author_id, t.title, t.slug, t.tags, t.is_pinned, t.is_locked, t.is_archived, t.solution_post_id, t.post_count, t.last_post_number, t.last_post_at, t.last_poster_id, t.created_at, t.updated_at, t.deleted_at, t.deleted_by, t.upvotes, t.downvotes, t.score, t.hot_rank, t.controversy FROM topics t
WHERE t.board_id = ANY($1::uuid[])
  AND t.deleted_at IS NULL
  AND ($2::uuid IS NULL OR t.place_id = $2::uuid)
  AND ($3::boolean OR NOT t.is_archived)
  AND NOT ($4::boolean AND t.is_pinned)
  AND ($5::text IS NULL OR $5::text = ANY(t.tags))
  AND ($6::boolean IS NULL
       OR (t.solution_post_id IS NOT NULL) = $6::boolean)
  AND ($7::timestamptz IS NULL OR t.created_at >= $7::timestamptz)
  AND NOT ($8::boolean AND EXISTS (
        SELECT 1 FROM topic_reads r
        WHERE r.user_id = $9::uuid AND r.topic_id = t.id
          AND r.opened_at IS NOT NULL AND r.seen_post_number >= t.last_post_number))
  AND NOT COALESCE(
        (SELECT s.level = 'muted' FROM subscriptions s
         WHERE $10::boolean AND s.user_id = $9::uuid
           AND s.target_type = 'topic' AND s.target_id = t.id),
        t.board_id = ANY($11::uuid[]))
  AND t.controversy > 0
  AND ($12::uuid IS NULL
       OR (t.controversy, t.id) < ($13::float8, $12::uuid))
ORDER BY t.controversy DESC, t.id DESC
LIMIT $14
`

type ListFeedControversialParams struct {
	BoardIds        []uuid.UUID
	PlaceID         *uuid.UUID
	IncludeArchived bool
	ExcludePinned   bool
	Tag             *string
	Solved          *bool
	Since           *time.Time
	HideRead        bool
	ViewerID        uuid.UUID
	ApplyMutes      bool
	MutedBoardIds   []uuid.UUID
	AfterID         *uuid.UUID
	AfterRank       *float64
	Lim             int32
}

// Many votes split between up and down; since bounds the window.
func (q *Queries) ListFeedControversial(ctx context.Context, arg ListFeedControversialParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listFeedControversial,
		arg.BoardIds,
		arg.PlaceID,
		arg.IncludeArchived,
		arg.ExcludePinned,
		arg.Tag,
		arg.Solved,
		arg.Since,
		arg.HideRead,
		arg.ViewerID,
		arg.ApplyMutes,
		arg.MutedBoardIds,
		arg.AfterID,
		arg.AfterRank,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Tags,
			&i.IsPinned,
			&i.IsLocked,
			&i.IsArchived,
			&i.SolutionPostID,
			&i.PostCount,
			&i.LastPostNumber,
			&i.LastPostAt,
			&i.LastPosterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Upvotes,
			&i.Downvotes,
			&i.Score,
			&i.HotRank,
			&i.Controversy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedHot = `-- name: ListFeedHot :many
SELECT t.id, t.place_id, t.board_id, t.author_id, t.title, t.slug, t.tags, t.is_pinned, t.is_locked, t.is_archived, t.solution_post_id, t.post_count, t.last_post_number, t.last_post_at, t.last_poster_id, t.created_at, t.updated_at, t.deleted_at, t.deleted_by, t.upvotes, t.downvotes, t.score, t.hot_rank, t.controversy FROM topics t
WHERE t.board_id = ANY($1::uuid[])
  AND t.deleted_at IS NULL
  AND ($2::uuid IS NULL OR t.place_id = $2::uuid)
  AND ($3::boolean OR NOT t.is_archived)
  AND NOT ($4::boolean AND t.is_pinned)
  AND ($5::text IS NULL OR $5::text = ANY(t.tags))
  AND ($6::boolean IS NULL
       OR (t.solution_post_id IS NOT NULL) = $6::boolean)
  AND ($7::timestamptz IS NULL OR t.created_at >= $7::timestamptz)
  AND NOT ($8::boolean AND EXISTS (
        SELECT 1 FROM topic_reads r
        WHERE r.user_id = $9::uuid AND r.topic_id = t.id
          AND r.opened_at IS NOT NULL AND r.seen_post_number >= t.last_post_number))
  AND NOT COALESCE(
        (SELECT s.level = 'muted' FROM subscriptions s
         WHERE $10::boolean AND s.user_id = $9::uuid
           AND s.target_type = 'topic' AND s.target_id = t.id),
        t.board_id = ANY($11::uuid[]))
  AND ($12::uuid IS NULL
       OR (t.hot_rank, t.id) < ($13::float8, $12::uuid))
ORDER BY t.hot_rank DESC, t.id DESC
LIMIT $14
`

type ListFeedHotParams struct {
	BoardIds        []uuid.UUID
	PlaceID         *uuid.UUID
	IncludeArchived bool
	ExcludePinned   bool
	Tag             *string
	Solved          *bool
	Since           *time.Time
	HideRead        bool
	ViewerID        uuid.UUID
	ApplyMutes      bool
	MutedBoardIds   []uuid.UUID
	AfterID         *uuid.UUID
	AfterRank       *float64
	Lim             int32
}

// Highest hot_rank first.
func (q *Queries) ListFeedHot(ctx context.Context, arg ListFeedHotParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listFeedHot,
		arg.BoardIds,
		arg.PlaceID,
		arg.IncludeArchived,
		arg.ExcludePinned,
		arg.Tag,
		arg.Solved,
		arg.Since,
		arg.HideRead,
		arg.ViewerID,
		arg.ApplyMutes,
		arg.MutedBoardIds,
		arg.AfterID,
		arg.AfterRank,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Tags,
			&i.IsPinned,
			&i.IsLocked,
			&i.IsArchived,
			&i.SolutionPostID,
			&i.PostCount,
			&i.LastPostNumber,
			&i.LastPostAt,
			&i.LastPosterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Upvotes,
			&i.Downvotes,
			&i.Score,
			&i.HotRank,
			&i.Controversy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedNew = `-- name: ListFeedNew :many
SELECT t.id, t.place_id, t.board_id, t.author_id, t.title, t.slug, t.tags, t.is_pinned, t.is_locked, t.is_archived, t.solution_post_id, t.post_count, t.last_post_number, t.last_post_at, t.last_poster_id, t.created_at, t.updated_at, t.deleted_at, t.deleted_by, t.upvotes, t.downvotes, t.score, t.hot_rank, t.controversy FROM topics t
WHERE t.board_id = ANY($1::uuid[])
  AND t.deleted_at IS NULL
  AND ($2::uuid IS NULL OR t.place_id = $2::uuid)
  AND ($3::boolean OR NOT t.is_archived)
  AND NOT ($4::boolean AND t.is_pinned)
  AND ($5::text IS NULL OR $5::text = ANY(t.tags))
  AND ($6::boolean IS NULL
       OR (t.solution_post_id IS NOT NULL) = $6::boolean)
  AND ($7::timestamptz IS NULL OR t.created_at >= $7::timestamptz)
  AND NOT ($8::boolean AND EXISTS (
        SELECT 1 FROM topic_reads r
        WHERE r.user_id = $9::uuid AND r.topic_id = t.id
          AND r.opened_at IS NOT NULL AND r.seen_post_number >= t.last_post_number))
  AND NOT COALESCE(
        (SELECT s.level = 'muted' FROM subscriptions s
         WHERE $10::boolean AND s.user_id = $9::uuid
           AND s.target_type = 'topic' AND s.target_id = t.id),
        t.board_id = ANY($11::uuid[]))
  AND ($12::uuid IS NULL
       OR (t.created_at, t.id) < ($13::timestamptz, $12::uuid))
ORDER BY t.created_at DESC, t.id DESC
LIMIT $14
`

type ListFeedNewParams struct {
	BoardIds        []uuid.UUID
	PlaceID         *uuid.UUID
	IncludeArchived bool
	ExcludePinned   bool
	Tag             *string
	Solved          *bool
	Since           *time.Time
	HideRead        bool
	ViewerID        uuid.UUID
	ApplyMutes      bool
	MutedBoardIds   []uuid.UUID
	AfterID         *uuid.UUID
	AfterTime       *time.Time
	Lim             int32
}

// Newest topics first.
func (q *Queries) ListFeedNew(ctx context.Context, arg ListFeedNewParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listFeedNew,
		arg.BoardIds,
		arg.PlaceID,
		arg.IncludeArchived,
		arg.ExcludePinned,
		arg.Tag,
		arg.Solved,
		arg.Since,
		arg.HideRead,
		arg.ViewerID,
		arg.ApplyMutes,
		arg.MutedBoardIds,
		arg.AfterID,
		arg.AfterTime,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Tags,
			&i.IsPinned,
			&i.IsLocked,
			&i.IsArchived,
			&i.SolutionPostID,
			&i.PostCount,
			&i.LastPostNumber,
			&i.LastPostAt,
			&i.LastPosterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Upvotes,
			&i.Downvotes,
			&i.Score,
			&i.HotRank,
			&i.Controversy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedPinned = `-- name: ListFeedPinned :many
SELECT t.id, t.place_id, t.board_id, t.author_id, t.title, t.slug, t.tags, t.is_pinned, t.is_locked, t.is_archived, t.solution_post_id, t.post_count, t.last_post_number, t.last_post_at, t.last_poster_id, t.created_at, t.updated_at, t.deleted_at, t.deleted_by, t.upvotes, t.downvotes, t.score, t.hot_rank, t.controversy FROM topics t
WHERE t.board_id = ANY($1::uuid[])
  AND t.deleted_at IS NULL
  AND ($2::uuid IS NULL OR t.place_id = $2::uuid)
  AND ($3::boolean OR NOT t.is_archived)
  AND NOT ($4::boolean AND t.is_pinned)
  AND ($5::text IS NULL OR $5::text = ANY(t.tags))
  AND ($6::boolean IS NULL
       OR (t.solution_post_id IS NOT NULL) = $6::boolean)
  AND ($7::timestamptz IS NULL OR t.created_at >= $7::timestamptz)
  AND NOT ($8::boolean AND EXISTS (
        SELECT 1 FROM topic_reads r
        WHERE r.user_id = $9::uuid AND r.topic_id = t.id
          AND r.opened_at IS NOT NULL AND r.seen_post_number >= t.last_post_number))
  AND NOT COALESCE(
        (SELECT s.level = 'muted' FROM subscriptions s
         WHERE $10::boolean AND s.user_id = $9::uuid
           AND s.target_type = 'topic' AND s.target_id = t.id),
        t.board_id = ANY($11::uuid[]))
  AND t.is_pinned
ORDER BY t.last_post_at DESC, t.id DESC
LIMIT $12
`

type ListFeedPinnedParams struct {
	BoardIds        []uuid.UUID
	PlaceID         *uuid.UUID
	IncludeArchived bool
	ExcludePinned   bool
	Tag             *string
	Solved          *bool
	Since           *time.Time
	HideRead        bool
	ViewerID        uuid.UUID
	ApplyMutes      bool
	MutedBoardIds   []uuid.UUID
	Lim             int32
}

// Pinned topics for the top of a place feed, most recently active first.
func (q *Queries) ListFeedPinned(ctx context.Context, arg ListFeedPinnedParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listFeedPinned,
		arg.BoardIds,
		arg.PlaceID,
		arg.IncludeArchived,
		arg.ExcludePinned,
		arg.Tag,
		arg.Solved,
		arg.Since,
		arg.HideRead,
		arg.ViewerID,
		arg.ApplyMutes,
		arg.MutedBoardIds,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Tags,
			&i.IsPinned,
			&i.IsLocked,
			&i.IsArchived,
			&i.SolutionPostID,
			&i.PostCount,
			&i.LastPostNumber,
			&i.LastPostAt,
			&i.LastPosterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Upvotes,
			&i.Downvotes,
			&i.Score,
			&i.HotRank,
			&i.Controversy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedRising = `-- name: ListFeedRising :many
WITH c AS (
    SELECT t.id,
           ((GREATEST(t.score, 0) + GREATEST(t.post_count - 1, 0) + 1)::float8
               / power(GREATEST(extract(epoch FROM ($4::timestamptz - t.created_at))::float8 / 3600, 0) + 2, 1.5)
           )::float8 AS rank
    FROM topics t
    WHERE t.board_id = ANY($5::uuid[])
      AND t.deleted_at IS NULL
      AND ($6::uuid IS NULL OR t.place_id = $6::uuid)
      AND ($7::boolean OR NOT t.is_archived)
      AND NOT ($8::boolean AND t.is_pinned)
      AND ($9::text IS NULL OR $9::text = ANY(t.tags))
      AND ($10::boolean IS NULL
           OR (t.solution_post_id IS NOT NULL) = $10::boolean)
      AND ($11::timestamptz IS NULL OR t.created_at >= $11::timestamptz)
      AND NOT ($12::boolean AND EXISTS (
            SELECT 1 FROM topic_reads r
            WHERE r.user_id = $13::uuid AND r.topic_id = t.id
              AND r.opened_at IS NOT NULL AND r.seen_post_number >= t.last_post_number))
      AND NOT COALESCE(
            (SELECT s.level = 'muted' FROM subscriptions s
             WHERE $14::boolean AND s.user_id = $13::uuid
               AND s.target_type = 'topic' AND s.target_id = t.id),
            t.board_id = ANY($15::uuid[]))
      AND t.created_at <= $4::timestamptz
)
SELECT t.id, t.place_id, t.board_id, t.author_id, t.title, t.slug, t.tags, t.is_pinned, t.is_locked, t.is_archived, t.solution_post_id, t.post_count, t.last_post_number, t.last_post_at, t.last_poster_id, t.created_at, t.updated_at, t.deleted_at, t.deleted_by, t.upvotes, t.downvotes, t.score, t.hot_rank, t.controversy, c.rank
FROM c
JOIN topics t ON t.id = c.id
WHERE $1::uuid IS NULL
   OR (c.rank, c.id) < ($2::float8, $1::uuid)
ORDER BY c.rank DESC, c.id DESC
LIMIT $3
`

type ListFeedRisingParams struct {
	AfterID         *uuid.UUID
	AfterRank       *float64
	Lim             int32
	AsOf            time.Time
	BoardIds        []uuid.UUID
	PlaceID         *uuid.UUID
	IncludeArchived bool
	ExcludePinned   bool
	Tag             *string
	Solved          *bool
	Since           *time.Time
	HideRead        bool
	ViewerID        uuid.UUID
	ApplyMutes      bool
	MutedBoardIds   []uuid.UUID
}

type ListFeedRisingRow struct {
	Topic Topic
	Rank  float64
}

// Recent topics (since bounds the candidates to the last 48 hours) gaining votes and replies
// fastest relative to their age at as_of. as_of is fixed by the first page so pages agree.
func (q *Queries) ListFeedRising(ctx context.Context, arg ListFeedRisingParams) ([]ListFeedRisingRow, error) {
	rows, err := q.db.Query(ctx, listFeedRising,
		arg.AfterID,
		arg.AfterRank,
		arg.Lim,
		arg.AsOf,
		arg.BoardIds,
		arg.PlaceID,
		arg.IncludeArchived,
		arg.ExcludePinned,
		arg.Tag,
		arg.Solved,
		arg.Since,
		arg.HideRead,
		arg.ViewerID,
		arg.ApplyMutes,
		arg.MutedBoardIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedRisingRow{}
	for rows.Next() {
		var i ListFeedRisingRow
		if err := rows.Scan(
			&i.Topic.ID,
			&i.Topic.PlaceID,
			&i.Topic.BoardID,
			&i.Topic.AuthorID,
			&i.Topic.Title,
			&i.Topic.Slug,
			&i.Topic.Tags,
			&i.Topic.IsPinned,
			&i.Topic.IsLocked,
			&i.Topic.IsArchived,
			&i.Topic.SolutionPostID,
			&i.Topic.PostCount,
			&i.Topic.LastPostNumber,
			&i.Topic.LastPostAt,
			&i.Topic.LastPosterID,
			&i.Topic.CreatedAt,
			&i.Topic.UpdatedAt,
			&i.Topic.DeletedAt,
			&i.Topic.DeletedBy,
			&i.Topic.Upvotes,
			&i.Topic.Downvotes,
			&i.Topic.Score,
			&i.Topic.HotRank,
			&i.Topic.Controversy,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedTop = `-- name: ListFeedTop :many
SELECT t.id, t.place_id, t.board_id, t.author_id, t.title, t.slug, t.tags, t.is_pinned, t.is_locked, t.is_archived, t.solution_post_id, t.post_count, t.last_post_number, t.last_post_at, t.last_poster_id, t.created_at, t.updated_at, t.deleted_at, t.deleted_by, t.upvotes, t.downvotes, t.score, t.hot_rank, t.controversy FROM topics t
WHERE t.board_id = ANY($1::uuid[])
  AND t.deleted_at IS NULL
  AND ($2::uuid IS NULL OR t.place_id = $2::uuid)
  AND ($3::boolean OR NOT t.is_archived)
  AND NOT ($4::boolean AND t.is_pinned)
  AND ($5::text IS NULL OR $5::text = ANY(t.tags))
  AND ($6::boolean IS NULL
       OR (t.solution_post_id IS NOT NULL) = $6::boolean)
  AND ($7::timestamptz IS NULL OR t.created_at >= $7::timestamptz)
  AND NOT ($8::boolean AND EXISTS (
        SELECT 1 FROM topic_reads r
        WHERE r.user_id = $9::uuid AND r.topic_id = t.id
          AND r.opened_at IS NOT NULL AND r.seen_post_number >= t.last_post_number))
  AND NOT COALESCE(
        (SELECT s.level = 'muted' FROM subscriptions s
         WHERE $10::boolean AND s.user_id = $9::uuid
           AND s.target_type = 'topic' AND s.target_id = t.id),
        t.board_id = ANY($11::uuid[]))
  AND ($12::uuid IS NULL
       OR (t.score, t.id) < ($13::integer, $12::uuid))
ORDER BY t.score DESC, t.id DESC
LIMIT $14
`

type ListFeedTopParams struct {
	BoardIds        []uuid.UUID
	PlaceID         *uuid.UUID
	IncludeArchived bool
	ExcludePinned   bool
	Tag             *string
	Solved          *bool
	Since           *time.Time
	HideRead        bool
	ViewerID        uuid.UUID
	ApplyMutes      bool
	MutedBoardIds   []uuid.UUID
	AfterID         *uuid.UUID
	AfterScore      *int32
	Lim             int32
}

// Highest score first; since bounds the window.
func (q *Queries) ListFeedTop(ctx context.Context, arg ListFeedTopParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listFeedTop,
		arg.BoardIds,
		arg.PlaceID,
		arg.IncludeArchived,
		arg.ExcludePinned,
		arg.Tag,
		arg.Solved,
		arg.Since,
		arg.HideRead,
		arg.ViewerID,
		arg.ApplyMutes,
		arg.MutedBoardIds,
		arg.AfterID,
		arg.AfterScore,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Tags,
			&i.IsPinned,
			&i.IsLocked,
			&i.IsArchived,
			&i.SolutionPostID,
			&i.PostCount,
			&i.LastPostNumber,
			&i.LastPostAt,
			&i.LastPosterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Upvotes,
			&i.Downvotes,
			&i.Score,
			&i.HotRank,
			&i.Controversy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForumMutes = `-- name: ListForumMutes :many
SELECT user_id, target_type, target_id, place_id, level, created_at, updated_at FROM subscriptions
WHERE user_id = $1 AND place_id = ANY($2::uuid[]) AND target_type IN ('place', 'board')
`

type ListForumMutesParams struct {
	UserID   uuid.UUID
	PlaceIds []uuid.UUID
}

// A user's place and board level notification preferences in the given places.
func (q *Queries) ListForumMutes(ctx context.Context, arg ListForumMutesParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listForumMutes, arg.UserID, arg.PlaceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.UserID,
			&i.TargetType,
			&i.TargetID,
			&i.PlaceID,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberRolesForPlaces = `-- name: ListMemberRolesForPlaces :many
SELECT r.id, r.place_id, r.name, r.color, r.position, r.permissions, r.is_default, r.created_at, r.updated_at FROM roles r
WHERE r.place_id = ANY($1::uuid[])
  AND (r.is_default
       OR r.id IN (SELECT mr.role_id FROM member_roles mr
                   WHERE mr.user_id = $2 AND mr.place_id = ANY($1::uuid[])))
`

type ListMemberRolesForPlacesParams struct {
	PlaceIds []uuid.UUID
	UserID   uuid.UUID
}

// The default role of each place plus every role the user holds there.
func (q *Queries) ListMemberRolesForPlaces(ctx context.Context, arg ListMemberRolesForPlacesParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listMemberRolesForPlaces, arg.PlaceIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.Permissions,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpeningPosts = `-- name: ListOpeningPosts :many
SELECT topic_id, content FROM posts WHERE topic_id = ANY($1::uuid[]) AND post_number = 1
`

type ListOpeningPostsRow struct {
	TopicID uuid.UUID
	Content string
}

func (q *Queries) ListOpeningPosts(ctx context.Context, topicIds []uuid.UUID) ([]ListOpeningPostsRow, error) {
	rows, err := q.db.Query(ctx, listOpeningPosts, topicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpeningPostsRow{}
	for rows.Next() {
		var i ListOpeningPostsRow
		if err := rows.Scan(&i.TopicID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicFeedBoards = `-- name: ListPublicFeedBoards :many
SELECT b.id, b.place_id, b.parent_id, b.kind, b.slug, b.name, b.description, b.position, b.reply_mode, b.solutions_enabled, b.is_nsfw, b.is_public, b.topic_count, b.post_count, b.last_post_at, b.created_at, b.updated_at,
       (b.is_nsfw OR pl.is_nsfw OR COALESCE(p1.is_nsfw, false) OR COALESCE(p2.is_nsfw, false))::boolean AS nsfw
FROM boards b
JOIN places pl ON pl.id = b.place_id
LEFT JOIN boards p1 ON p1.id = b.parent_id
LEFT JOIN boards p2 ON p2.id = p1.parent_id
WHERE b.is_public AND b.kind = 'board' AND pl.deleted_at IS NULL AND pl.visibility = 'public'
`

type ListPublicFeedBoardsRow struct {
	Board Board
	Nsfw  bool
}

// Boards signed-out visitors can read, across every live public place. is_nsfw also counts
// the place and the board's ancestors (boards nest at most three levels).
func (q *Queries) ListPublicFeedBoards(ctx context.Context) ([]ListPublicFeedBoardsRow, error) {
	rows, err := q.db.Query(ctx, listPublicFeedBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicFeedBoardsRow{}
	for rows.Next() {
		var i ListPublicFeedBoardsRow
		if err := rows.Scan(
			&i.Board.ID,
			&i.Board.PlaceID,
			&i.Board.ParentID,
			&i.Board.Kind,
			&i.Board.Slug,
			&i.Board.Name,
			&i.Board.Description,
			&i.Board.Position,
			&i.Board.ReplyMode,
			&i.Board.SolutionsEnabled,
			&i.Board.IsNsfw,
			&i.Board.IsPublic,
			&i.Board.TopicCount,
			&i.Board.PostCount,
			&i.Board.LastPostAt,
			&i.Board.CreatedAt,
			&i.Board.UpdatedAt,
			&i.Nsfw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicVotes = `-- name: ListTopicVotes :many
SELECT topic_id, value FROM topic_votes WHERE user_id = $1 AND topic_id = ANY($2::uuid[])
`

type ListTopicVotesParams struct {
	UserID   uuid.UUID
	TopicIds []uuid.UUID
}

type ListTopicVotesRow struct {
	TopicID uuid.UUID
	Value   int16
}

func (q *Queries) ListTopicVotes(ctx context.Context, arg ListTopicVotesParams) ([]ListTopicVotesRow, error) {
	rows, err := q.db.Query(ctx, listTopicVotes, arg.UserID, arg.TopicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicVotesRow{}
	for rows.Next() {
		var i ListTopicVotesRow
		if err := rows.Scan(&i.TopicID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedRead = `-- name: MarkFeedRead :execrows
INSERT INTO topic_reads (user_id, topic_id, last_read_post_number, opened_at, first_opened_at, seen_post_number)
SELECT $1, t.id, t.last_post_number, now(), now(), t.last_post_number
FROM topics t
WHERE t.board_id = ANY($2::uuid[])
  AND t.deleted_at IS NULL
  AND t.last_post_at <= $3::timestamptz
ORDER BY t.last_post_at DESC
LIMIT $4
ON CONFLICT (user_id, topic_id) DO UPDATE
SET last_read_post_number = GREATEST(topic_reads.last_read_post_number, EXCLUDED.last_read_post_number),
    opened_at             = now(),
    first_opened_at       = COALESCE(topic_reads.first_opened_at, now()),
    seen_post_number      = GREATEST(topic_reads.seen_post_number, EXCLUDED.seen_post_number),
    updated_at            = now()
`

type MarkFeedReadParams struct {
	UserID   uuid.UUID
	BoardIds []uuid.UUID
	Before   time.Time
	Lim      int32
}

// Marks the most recently active topics in the given boards fully read, up to before.
func (q *Queries) MarkFeedRead(ctx context.Context, arg MarkFeedReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFeedRead,
		arg.UserID,
		arg.BoardIds,
		arg.Before,
		arg.Lim,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTopicUnread = `-- name: MarkTopicUnread :execrows
UPDATE topic_reads SET opened_at = NULL, updated_at = now()
WHERE user_id = $1 AND topic_id = $2 AND opened_at IS NOT NULL
`

type MarkTopicUnreadParams struct {
	UserID  uuid.UUID
	TopicID uuid.UUID
}

// Clears the "opened" state but keeps the read position.
func (q *Queries) MarkTopicUnread(ctx context.Context, arg MarkTopicUnreadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTopicUnread, arg.UserID, arg.TopicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTopicsOpened = `-- name: MarkTopicsOpened :many
INSERT INTO topic_reads (user_id, topic_id, last_read_post_number, opened_at, first_opened_at, seen_post_number)
SELECT $1, t.id, 1, now(), now(), t.last_post_number
FROM topics t
WHERE t.id = ANY($2::uuid[]) AND t.deleted_at IS NULL
ON CONFLICT (user_id, topic_id) DO UPDATE
SET opened_at        = now(),
    first_opened_at  = COALESCE(topic_reads.first_opened_at, now()),
    seen_post_number = GREATEST(topic_reads.seen_post_number, EXCLUDED.seen_post_number),
    updated_at       = now()
RETURNING topic_id
`

type MarkTopicsOpenedParams struct {
	UserID   uuid.UUID
	TopicIds []uuid.UUID
}

// Records opens of several (already authorized) topics at once.
func (q *Queries) MarkTopicsOpened(ctx context.Context, arg MarkTopicsOpenedParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, markTopicsOpened, arg.UserID, arg.TopicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var topic_id uuid.UUID
		if err := rows.Scan(&topic_id); err != nil {
			return nil, err
		}
		items = append(items, topic_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTopicRanks = `-- name: RefreshTopicRanks :exec
UPDATE topics t
SET score       = s.score,
    hot_rank    = sign(s.score + 2 * sqrt(GREATEST(t.post_count - 1, 0)))
                      * log(GREATEST(abs(s.score + 2 * sqrt(GREATEST(t.post_count - 1, 0))), 1))
                  + (extract(epoch FROM t.created_at)::float8 - 1704067200) / 45000,
    controversy = CASE
        WHEN s.voting_enabled AND t.upvotes > 0 AND t.downvotes > 0
            THEN power((t.upvotes + t.downvotes)::float8,
                       LEAST(t.upvotes, t.downvotes)::float8 / GREATEST(t.upvotes, t.downvotes)::float8)
        ELSE 0 END
FROM (
    SELECT tt.id,
           pl.voting_enabled,
           (CASE WHEN pl.voting_enabled THEN tt.upvotes - tt.downvotes
                 ELSE COALESCE(op.reaction_count, 0) END)::integer AS score
    FROM topics tt
    JOIN places pl ON pl.id = tt.place_id
    LEFT JOIN posts op ON op.topic_id = tt.id AND op.post_number = 1
    WHERE tt.id = ANY($1::uuid[]) OR tt.place_id = $2::uuid
) s
WHERE t.id = s.id
`

type RefreshTopicRanksParams struct {
	TopicIds []uuid.UUID
	PlaceID  *uuid.UUID
}

// Recomputes score, hot_rank and controversy for the given topics, or every topic of a
// place. Score is up minus down votes, or the reactions on the opening post when the place has
// voting off. hot_rank is sign(s) times log10 of max(abs(s), 1) plus age in units of 45000
// seconds, where s is score plus twice the square root of the reply count: ten times the
// engagement is worth 12.5 hours of age. Keep in sync with 00006_feeds.sql.
func (q *Queries) RefreshTopicRanks(ctx context.Context, arg RefreshTopicRanksParams) error {
	_, err := q.db.Exec(ctx, refreshTopicRanks, arg.TopicIds, arg.PlaceID)
	return err
}

const removeUserTopicVotes = `-- name: RemoveUserTopicVotes :many
WITH removed AS (
    DELETE FROM topic_votes WHERE user_id = $1 RETURNING topic_id, value
)
UPDATE topics
SET upvotes   = topics.upvotes - r.up,
    downvotes = topics.downvotes - r.down
FROM (
    SELECT topic_id,
           (count(*) FILTER (WHERE value = 1))::integer  AS up,
           (count(*) FILTER (WHERE value = -1))::integer AS down
    FROM removed GROUP BY topic_id
) r
WHERE topics.id = r.topic_id
RETURNING topics.id
`

// Erases a user's votes and takes them off the topic counts; returns the affected topics
// so their ranks can be refreshed.
func (q *Queries) RemoveUserTopicVotes(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, removeUserTopicVotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTopicVote = `-- name: UpsertTopicVote :exec
INSERT INTO topic_votes (topic_id, user_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (topic_id, user_id) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type UpsertTopicVoteParams struct {
	TopicID uuid.UUID
	UserID  uuid.UUID
	Value   int16
}

func (q *Queries) UpsertTopicVote(ctx context.Context, arg UpsertTopicVoteParams) error {
	_, err := q.db.Exec(ctx, upsertTopicVote, arg.TopicID, arg.UserID, arg.Value)
	return err
}
