// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance.sql

package store

import (
	"context"
)

const completeSetup = `-- name: CompleteSetup :one
UPDATE instance_settings
SET name               = $1,
    description        = $2,
    registration_mode  = $3,
    setup_completed_at = now(),
    setup_token        = NULL,
    updated_at         = now()
WHERE id = 1 AND setup_completed_at IS NULL
RETURNING id, name, description, icon_url, registration_mode, setup_token, setup_completed_at, jwt_secret, created_at, updated_at
`

type CompleteSetupParams struct {
	Name             string
	Description      string
	RegistrationMode string
}

func (q *Queries) CompleteSetup(ctx context.Context, arg CompleteSetupParams) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, completeSetup, arg.Name, arg.Description, arg.RegistrationMode)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.RegistrationMode,
		&i.SetupToken,
		&i.SetupCompletedAt,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPlaces = `-- name: CountPlaces :one
SELECT count(*) FROM places WHERE deleted_at IS NULL
`

func (q *Queries) CountPlaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE deleted_at IS NULL AND NOT is_bot
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureInstanceSettings = `-- name: EnsureInstanceSettings :exec
INSERT INTO instance_settings (id, jwt_secret, setup_token)
VALUES (1, $1, $2)
ON CONFLICT (id) DO NOTHING
`

type EnsureInstanceSettingsParams struct {
	JwtSecret  []byte
	SetupToken *string
}

func (q *Queries) EnsureInstanceSettings(ctx context.Context, arg EnsureInstanceSettingsParams) error {
	_, err := q.db.Exec(ctx, ensureInstanceSettings, arg.JwtSecret, arg.SetupToken)
	return err
}

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT id, name, description, icon_url, registration_mode, setup_token, setup_completed_at, jwt_secret, created_at, updated_at FROM instance_settings WHERE id = 1
`

func (q *Queries) GetInstanceSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, getInstanceSettings)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.RegistrationMode,
		&i.SetupToken,
		&i.SetupCompletedAt,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstanceSettings = `-- name: UpdateInstanceSettings :one
UPDATE instance_settings
SET name              = COALESCE($1::text, name),
    description       = COALESCE($2::text, description),
    icon_url          = CASE WHEN $3::text IS NULL THEN icon_url
                             ELSE NULLIF($3::text, '') END,
    registration_mode = COALESCE($4::text, registration_mode),
    updated_at        = now()
WHERE id = 1
RETURNING id, name, description, icon_url, registration_mode, setup_token, setup_completed_at, jwt_secret, created_at, updated_at
`

type UpdateInstanceSettingsParams struct {
	Name             *string
	Description      *string
	IconUrl          *string
	RegistrationMode *string
}

// Nullable params leave the column unchanged; an empty icon_url clears it.
func (q *Queries) UpdateInstanceSettings(ctx context.Context, arg UpdateInstanceSettingsParams) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, updateInstanceSettings,
		arg.Name,
		arg.Description,
		arg.IconUrl,
		arg.RegistrationMode,
	)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.RegistrationMode,
		&i.SetupToken,
		&i.SetupCompletedAt,
		&i.JwtSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
