// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE invites
SET uses = uses + 1
WHERE code = $1
  AND (max_uses IS NULL OR uses < max_uses)
  AND (expires_at IS NULL OR expires_at > now())
RETURNING code, place_id, created_by, max_uses, uses, expires_at, created_at
`

// Atomically records one use of a still-valid invite.
func (q *Queries) ConsumeInvite(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, consumeInvite, code)
	var i Invite
	err := row.Scan(
		&i.Code,
		&i.PlaceID,
		&i.CreatedBy,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (code, place_id, created_by, max_uses, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING code, place_id, created_by, max_uses, uses, expires_at, created_at
`

type CreateInviteParams struct {
	Code      string
	PlaceID   uuid.UUID
	CreatedBy *uuid.UUID
	MaxUses   *int32
	ExpiresAt *time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.Code,
		arg.PlaceID,
		arg.CreatedBy,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.Code,
		&i.PlaceID,
		&i.CreatedBy,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM invites WHERE code = $1 AND place_id = $2
`

type DeleteInviteParams struct {
	Code    string
	PlaceID uuid.UUID
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvite, arg.Code, arg.PlaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvite = `-- name: GetInvite :one
SELECT code, place_id, created_by, max_uses, uses, expires_at, created_at FROM invites WHERE code = $1
`

func (q *Queries) GetInvite(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInvite, code)
	var i Invite
	err := row.Scan(
		&i.Code,
		&i.PlaceID,
		&i.CreatedBy,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT code, place_id, created_by, max_uses, uses, expires_at, created_at FROM invites WHERE place_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context, placeID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.Code,
			&i.PlaceID,
			&i.CreatedBy,
			&i.MaxUses,
			&i.Uses,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
