// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mail.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimMail = `-- name: ClaimMail :many
UPDATE mail_outbox
SET locked_until = now() + make_interval(secs => $1::integer),
    attempts     = attempts + 1
WHERE id IN (
    SELECT id FROM mail_outbox
    WHERE status = 'pending' AND next_attempt_at <= now() AND expires_at > now()
      AND (locked_until IS NULL OR locked_until < now())
    ORDER BY next_attempt_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, to_address, subject, text_body, html_body, status, attempts, next_attempt_at, expires_at, locked_until, last_error, created_at, completed_at
`

type ClaimMailParams struct {
	LockSeconds int32
	Lim         int32
}

// Locks due messages for this replica; SKIP LOCKED lets every replica drain the queue
// without sending anything twice.
func (q *Queries) ClaimMail(ctx context.Context, arg ClaimMailParams) ([]MailOutbox, error) {
	rows, err := q.db.Query(ctx, claimMail, arg.LockSeconds, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MailOutbox{}
	for rows.Next() {
		var i MailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ToAddress,
			&i.Subject,
			&i.TextBody,
			&i.HtmlBody,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.ExpiresAt,
			&i.LockedUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const consumeEmailToken = `-- name: ConsumeEmailToken :one
UPDATE email_tokens SET used_at = now()
WHERE token_hash = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > now()
RETURNING token_hash, user_id, purpose, email, created_at, expires_at, used_at
`

type ConsumeEmailTokenParams struct {
	TokenHash []byte
	Purpose   string
}

// Marks a live token used. Concurrent consumers race on the row; only one gets it back.
func (q *Queries) ConsumeEmailToken(ctx context.Context, arg ConsumeEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, consumeEmailToken, arg.TokenHash, arg.Purpose)
	var i EmailToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.Purpose,
		&i.Email,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createEmailToken = `-- name: CreateEmailToken :exec
INSERT INTO email_tokens (token_hash, user_id, purpose, email, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateEmailTokenParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	Purpose   string
	Email     string
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailToken,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.Email,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredEmailTokens = `-- name: DeleteExpiredEmailTokens :execrows
DELETE FROM email_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredEmailTokens(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEmailTokens, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldMail = `-- name: DeleteOldMail :execrows
DELETE FROM mail_outbox WHERE completed_at < $1
`

func (q *Queries) DeleteOldMail(ctx context.Context, before *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldMail, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueMail = `-- name: EnqueueMail :one
INSERT INTO mail_outbox (id, kind, to_address, subject, text_body, html_body, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, kind, to_address, subject, text_body, html_body, status, attempts, next_attempt_at, expires_at, locked_until, last_error, created_at, completed_at
`

type EnqueueMailParams struct {
	ID        uuid.UUID
	Kind      string
	ToAddress string
	Subject   string
	TextBody  string
	HtmlBody  string
	ExpiresAt time.Time
}

func (q *Queries) EnqueueMail(ctx context.Context, arg EnqueueMailParams) (MailOutbox, error) {
	row := q.db.QueryRow(ctx, enqueueMail,
		arg.ID,
		arg.Kind,
		arg.ToAddress,
		arg.Subject,
		arg.TextBody,
		arg.HtmlBody,
		arg.ExpiresAt,
	)
	var i MailOutbox
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ToAddress,
		&i.Subject,
		&i.TextBody,
		&i.HtmlBody,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.ExpiresAt,
		&i.LockedUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const expireMail = `-- name: ExpireMail :execrows
UPDATE mail_outbox
SET status = 'failed', last_error = 'expired before it could be sent', completed_at = now(),
    text_body = '', html_body = '', locked_until = NULL
WHERE status = 'pending' AND expires_at <= now()
`

func (q *Queries) ExpireMail(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireMail)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishMail = `-- name: FinishMail :exec
UPDATE mail_outbox
SET status          = $1,
    next_attempt_at = $2,
    last_error      = $3,
    locked_until    = NULL,
    completed_at    = CASE WHEN $1::text = 'pending' THEN NULL ELSE now() END,
    text_body       = CASE WHEN $1::text = 'pending' THEN text_body ELSE '' END,
    html_body       = CASE WHEN $1::text = 'pending' THEN html_body ELSE '' END
WHERE id = $4
`

type FinishMailParams struct {
	Status        string
	NextAttemptAt time.Time
	LastError     string
	ID            uuid.UUID
}

func (q *Queries) FinishMail(ctx context.Context, arg FinishMailParams) error {
	_, err := q.db.Exec(ctx, finishMail,
		arg.Status,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, display_name, bio, pronouns, avatar_url, is_instance_admin, email_verified_at, created_at, updated_at, deleted_at, is_bot FROM users WHERE lower(email) = lower($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Bio,
		&i.Pronouns,
		&i.AvatarUrl,
		&i.IsInstanceAdmin,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsBot,
	)
	return i, err
}

const invalidateEmailTokens = `-- name: InvalidateEmailTokens :exec
UPDATE email_tokens SET used_at = now()
WHERE user_id = $1 AND purpose = $2 AND used_at IS NULL
`

type InvalidateEmailTokensParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) InvalidateEmailTokens(ctx context.Context, arg InvalidateEmailTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateEmailTokens, arg.UserID, arg.Purpose)
	return err
}

const latestEmailTokenAt = `-- name: LatestEmailTokenAt :one
SELECT created_at FROM email_tokens
WHERE user_id = $1 AND purpose = $2
ORDER BY created_at DESC
LIMIT 1
`

type LatestEmailTokenAtParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) LatestEmailTokenAt(ctx context.Context, arg LatestEmailTokenAtParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestEmailTokenAt, arg.UserID, arg.Purpose)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const listMailOutbox = `-- name: ListMailOutbox :many
SELECT id, kind, to_address, subject, text_body, html_body, status, attempts, next_attempt_at, expires_at, locked_until, last_error, created_at, completed_at FROM mail_outbox ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListMailOutbox(ctx context.Context, lim int32) ([]MailOutbox, error) {
	rows, err := q.db.Query(ctx, listMailOutbox, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MailOutbox{}
	for rows.Next() {
		var i MailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ToAddress,
			&i.Subject,
			&i.TextBody,
			&i.HtmlBody,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.ExpiresAt,
			&i.LockedUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :one
UPDATE users SET email_verified_at = COALESCE(email_verified_at, now()), updated_at = now()
WHERE id = $1 AND lower(email) = lower($2) AND deleted_at IS NULL
RETURNING id, username, email, password_hash, display_name, bio, pronouns, avatar_url, is_instance_admin, email_verified_at, created_at, updated_at, deleted_at, is_bot
`

type MarkEmailVerifiedParams struct {
	ID    uuid.UUID
	Email string
}

// Only verifies the address the token was sent to, in case the account's email changed.
func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) (User, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Bio,
		&i.Pronouns,
		&i.AvatarUrl,
		&i.IsInstanceAdmin,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsBot,
	)
	return i, err
}

const setInstanceAdmin = `-- name: SetInstanceAdmin :exec
UPDATE users SET is_instance_admin = true, updated_at = now() WHERE id = $1
`

func (q *Queries) SetInstanceAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setInstanceAdmin, id)
	return err
}
