// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :execrows
INSERT INTO place_members (place_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddMemberParams struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, addMember, arg.PlaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addMemberRole = `-- name: AddMemberRole :exec
INSERT INTO member_roles (place_id, user_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddMemberRoleParams struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
	RoleID  uuid.UUID
}

func (q *Queries) AddMemberRole(ctx context.Context, arg AddMemberRoleParams) error {
	_, err := q.db.Exec(ctx, addMemberRole, arg.PlaceID, arg.UserID, arg.RoleID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT m.place_id, m.user_id, m.nickname, m.joined_at, u.id, u.username, u.email, u.password_hash, u.display_name, u.bio, u.pronouns, u.avatar_url, u.is_instance_admin, u.email_verified_at, u.created_at, u.updated_at, u.deleted_at
FROM place_members m
JOIN users u ON u.id = m.user_id
WHERE m.place_id = $1 AND m.user_id = $2
`

type GetMemberParams struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
}

type GetMemberRow struct {
	PlaceMember PlaceMember
	User        User
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, arg.PlaceID, arg.UserID)
	var i GetMemberRow
	err := row.Scan(
		&i.PlaceMember.PlaceID,
		&i.PlaceMember.UserID,
		&i.PlaceMember.Nickname,
		&i.PlaceMember.JoinedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.DisplayName,
		&i.User.Bio,
		&i.User.Pronouns,
		&i.User.AvatarUrl,
		&i.User.IsInstanceAdmin,
		&i.User.EmailVerifiedAt,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
	)
	return i, err
}

const getMemberRolesForPermissions = `-- name: GetMemberRolesForPermissions :many
SELECT r.permissions, r.position
FROM roles r
WHERE r.place_id = $1
  AND (r.is_default
       OR r.id IN (SELECT mr.role_id FROM member_roles mr
                   WHERE mr.place_id = $1 AND mr.user_id = $2))
`

type GetMemberRolesForPermissionsParams struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
}

type GetMemberRolesForPermissionsRow struct {
	Permissions int64
	Position    int32
}

// Returns the default role plus every role assigned to the member.
func (q *Queries) GetMemberRolesForPermissions(ctx context.Context, arg GetMemberRolesForPermissionsParams) ([]GetMemberRolesForPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getMemberRolesForPermissions, arg.PlaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMemberRolesForPermissionsRow{}
	for rows.Next() {
		var i GetMemberRolesForPermissionsRow
		if err := rows.Scan(&i.Permissions, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isMember = `-- name: IsMember :one
SELECT EXISTS (SELECT 1 FROM place_members WHERE place_id = $1 AND user_id = $2)
`

type IsMemberParams struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.PlaceID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMemberRoleIDs = `-- name: ListMemberRoleIDs :many
SELECT user_id, role_id FROM member_roles
WHERE place_id = $1 AND user_id = ANY($2::uuid[])
`

type ListMemberRoleIDsParams struct {
	PlaceID uuid.UUID
	UserIds []uuid.UUID
}

type ListMemberRoleIDsRow struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) ListMemberRoleIDs(ctx context.Context, arg ListMemberRoleIDsParams) ([]ListMemberRoleIDsRow, error) {
	rows, err := q.db.Query(ctx, listMemberRoleIDs, arg.PlaceID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberRoleIDsRow{}
	for rows.Next() {
		var i ListMemberRoleIDsRow
		if err := rows.Scan(&i.UserID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.place_id, m.user_id, m.nickname, m.joined_at, u.id, u.username, u.email, u.password_hash, u.display_name, u.bio, u.pronouns, u.avatar_url, u.is_instance_admin, u.email_verified_at, u.created_at, u.updated_at, u.deleted_at
FROM place_members m
JOIN users u ON u.id = m.user_id
WHERE m.place_id = $1
ORDER BY m.joined_at, m.user_id
LIMIT $3 OFFSET $2
`

type ListMembersParams struct {
	PlaceID uuid.UUID
	Off     int32
	Lim     int32
}

type ListMembersRow struct {
	PlaceMember PlaceMember
	User        User
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.PlaceID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.PlaceMember.PlaceID,
			&i.PlaceMember.UserID,
			&i.PlaceMember.Nickname,
			&i.PlaceMember.JoinedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.DisplayName,
			&i.User.Bio,
			&i.User.Pronouns,
			&i.User.AvatarUrl,
			&i.User.IsInstanceAdmin,
			&i.User.EmailVerifiedAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllUserMemberships = `-- name: RemoveAllUserMemberships :exec
DELETE FROM place_members WHERE user_id = $1
`

func (q *Queries) RemoveAllUserMemberships(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllUserMemberships, userID)
	return err
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM place_members WHERE place_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.PlaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeMemberRole = `-- name: RemoveMemberRole :execrows
DELETE FROM member_roles WHERE place_id = $1 AND user_id = $2 AND role_id = $3
`

type RemoveMemberRoleParams struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
	RoleID  uuid.UUID
}

func (q *Queries) RemoveMemberRole(ctx context.Context, arg RemoveMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMemberRole, arg.PlaceID, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMemberNickname = `-- name: UpdateMemberNickname :exec
UPDATE place_members SET nickname = NULLIF($1::text, '')
WHERE place_id = $2 AND user_id = $3
`

type UpdateMemberNicknameParams struct {
	Nickname string
	PlaceID  uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) UpdateMemberNickname(ctx context.Context, arg UpdateMemberNicknameParams) error {
	_, err := q.db.Exec(ctx, updateMemberNickname, arg.Nickname, arg.PlaceID, arg.UserID)
	return err
}
