// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addMessageReaction = `-- name: AddMessageReaction :execrows
INSERT INTO message_reactions (message_id, user_id, emoji) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddMessageReactionParams struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
	Emoji     string
}

func (q *Queries) AddMessageReaction(ctx context.Context, arg AddMessageReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, addMessageReaction, arg.MessageID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countDistinctMessageReactions = `-- name: CountDistinctMessageReactions :one
SELECT count(DISTINCT emoji) FROM message_reactions WHERE message_id = $1
`

func (q *Queries) CountDistinctMessageReactions(ctx context.Context, messageID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDistinctMessageReactions, messageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPins = `-- name: CountPins :one
SELECT count(*) FROM messages WHERE channel_id = $1 AND is_pinned
`

func (q *Queries) CountPins(ctx context.Context, channelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPins, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, channel_id, place_id, author_id, content, reply_to_id, mention_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, channel_id, place_id, author_id, content, reply_to_id, mention_ids, is_pinned, pinned_at, pinned_by, edit_count, edited_at, created_at, updated_at
`

type CreateMessageParams struct {
	ID         uuid.UUID
	ChannelID  uuid.UUID
	PlaceID    *uuid.UUID
	AuthorID   *uuid.UUID
	Content    string
	ReplyToID  *uuid.UUID
	MentionIds []uuid.UUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ChannelID,
		arg.PlaceID,
		arg.AuthorID,
		arg.Content,
		arg.ReplyToID,
		arg.MentionIds,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PlaceID,
		&i.AuthorID,
		&i.Content,
		&i.ReplyToID,
		&i.MentionIds,
		&i.IsPinned,
		&i.PinnedAt,
		&i.PinnedBy,
		&i.EditCount,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessageRevision = `-- name: CreateMessageRevision :exec
INSERT INTO message_revisions (id, message_id, content) VALUES ($1, $2, $3)
`

type CreateMessageRevisionParams struct {
	ID        uuid.UUID
	MessageID uuid.UUID
	Content   string
}

func (q *Queries) CreateMessageRevision(ctx context.Context, arg CreateMessageRevisionParams) error {
	_, err := q.db.Exec(ctx, createMessageRevision, arg.ID, arg.MessageID, arg.Content)
	return err
}

const deleteMessage = `-- name: DeleteMessage :execrows
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, channel_id, place_id, author_id, content, reply_to_id, mention_ids, is_pinned, pinned_at, pinned_by, edit_count, edited_at, created_at, updated_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PlaceID,
		&i.AuthorID,
		&i.Content,
		&i.ReplyToID,
		&i.MentionIds,
		&i.IsPinned,
		&i.PinnedAt,
		&i.PinnedBy,
		&i.EditCount,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessageReactionUsers = `-- name: ListMessageReactionUsers :many
SELECT u.id, u.username, u.email, u.password_hash, u.display_name, u.bio, u.pronouns, u.avatar_url, u.is_instance_admin, u.email_verified_at, u.created_at, u.updated_at, u.deleted_at, u.is_bot
FROM message_reactions r
JOIN users u ON u.id = r.user_id
WHERE r.message_id = $1 AND r.emoji = $2 AND u.deleted_at IS NULL
ORDER BY r.created_at, u.id
LIMIT $4 OFFSET $3
`

type ListMessageReactionUsersParams struct {
	MessageID uuid.UUID
	Emoji     string
	Off       int32
	Lim       int32
}

type ListMessageReactionUsersRow struct {
	User User
}

func (q *Queries) ListMessageReactionUsers(ctx context.Context, arg ListMessageReactionUsersParams) ([]ListMessageReactionUsersRow, error) {
	rows, err := q.db.Query(ctx, listMessageReactionUsers,
		arg.MessageID,
		arg.Emoji,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageReactionUsersRow{}
	for rows.Next() {
		var i ListMessageReactionUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.DisplayName,
			&i.User.Bio,
			&i.User.Pronouns,
			&i.User.AvatarUrl,
			&i.User.IsInstanceAdmin,
			&i.User.EmailVerifiedAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
			&i.User.IsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageRevisions = `-- name: ListMessageRevisions :many
SELECT id, message_id, content, created_at FROM message_revisions WHERE message_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListMessageRevisions(ctx context.Context, messageID uuid.UUID) ([]MessageRevision, error) {
	rows, err := q.db.Query(ctx, listMessageRevisions, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageRevision{}
	for rows.Next() {
		var i MessageRevision
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT id, channel_id, place_id, author_id, content, reply_to_id, mention_ids, is_pinned, pinned_at, pinned_by, edit_count, edited_at, created_at, updated_at FROM messages
WHERE channel_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListMessagesAfterParams struct {
	ChannelID uuid.UUID
	After     uuid.UUID
	Lim       int32
}

func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter, arg.ChannelID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.PlaceID,
			&i.AuthorID,
			&i.Content,
			&i.ReplyToID,
			&i.MentionIds,
			&i.IsPinned,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.EditCount,
			&i.EditedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT id, channel_id, place_id, author_id, content, reply_to_id, mention_ids, is_pinned, pinned_at, pinned_by, edit_count, edited_at, created_at, updated_at FROM messages
WHERE channel_id = $1 AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC
LIMIT $3
`

type ListMessagesBeforeParams struct {
	ChannelID uuid.UUID
	Before    *uuid.UUID
	Lim       int32
}

// Newest first; callers reverse the page into chronological order.
func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore, arg.ChannelID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.PlaceID,
			&i.AuthorID,
			&i.Content,
			&i.ReplyToID,
			&i.MentionIds,
			&i.IsPinned,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.EditCount,
			&i.EditedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByIDs = `-- name: ListMessagesByIDs :many
SELECT id, channel_id, place_id, author_id, content, reply_to_id, mention_ids, is_pinned, pinned_at, pinned_by, edit_count, edited_at, created_at, updated_at FROM messages WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListMessagesByIDs(ctx context.Context, ids []uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.PlaceID,
			&i.AuthorID,
			&i.Content,
			&i.ReplyToID,
			&i.MentionIds,
			&i.IsPinned,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.EditCount,
			&i.EditedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPins = `-- name: ListPins :many
SELECT id, channel_id, place_id, author_id, content, reply_to_id, mention_ids, is_pinned, pinned_at, pinned_by, edit_count, edited_at, created_at, updated_at FROM messages WHERE channel_id = $1 AND is_pinned ORDER BY pinned_at DESC, id DESC
`

func (q *Queries) ListPins(ctx context.Context, channelID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listPins, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.PlaceID,
			&i.AuthorID,
			&i.Content,
			&i.ReplyToID,
			&i.MentionIds,
			&i.IsPinned,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.EditCount,
			&i.EditedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageHasEmoji = `-- name: MessageHasEmoji :one
SELECT EXISTS (SELECT 1 FROM message_reactions WHERE message_id = $1 AND emoji = $2)
`

type MessageHasEmojiParams struct {
	MessageID uuid.UUID
	Emoji     string
}

func (q *Queries) MessageHasEmoji(ctx context.Context, arg MessageHasEmojiParams) (bool, error) {
	row := q.db.QueryRow(ctx, messageHasEmoji, arg.MessageID, arg.Emoji)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const messageReactionSummaries = `-- name: MessageReactionSummaries :many
SELECT message_id, emoji, count(*)::integer AS count, bool_or(user_id = $1)::boolean AS me
FROM message_reactions
WHERE message_id = ANY($2::uuid[])
GROUP BY message_id, emoji
ORDER BY message_id, min(created_at), emoji
`

type MessageReactionSummariesParams struct {
	ViewerID   uuid.UUID
	MessageIds []uuid.UUID
}

type MessageReactionSummariesRow struct {
	MessageID uuid.UUID
	Emoji     string
	Count     int32
	Me        bool
}

// viewer_id may be uuid.Nil.
func (q *Queries) MessageReactionSummaries(ctx context.Context, arg MessageReactionSummariesParams) ([]MessageReactionSummariesRow, error) {
	rows, err := q.db.Query(ctx, messageReactionSummaries, arg.ViewerID, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageReactionSummariesRow{}
	for rows.Next() {
		var i MessageReactionSummariesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Emoji,
			&i.Count,
			&i.Me,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMessageReaction = `-- name: RemoveMessageReaction :execrows
DELETE FROM message_reactions WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveMessageReactionParams struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
	Emoji     string
}

func (q *Queries) RemoveMessageReaction(ctx context.Context, arg RemoveMessageReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMessageReaction, arg.MessageID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMessagePinned = `-- name: SetMessagePinned :one
UPDATE messages
SET is_pinned  = $1::boolean,
    pinned_at  = CASE WHEN $1::boolean THEN now() END,
    pinned_by  = CASE WHEN $1::boolean THEN $2::uuid END,
    updated_at = now()
WHERE id = $3
RETURNING id, channel_id, place_id, author_id, content, reply_to_id, mention_ids, is_pinned, pinned_at, pinned_by, edit_count, edited_at, created_at, updated_at
`

type SetMessagePinnedParams struct {
	Pinned   bool
	PinnedBy *uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) SetMessagePinned(ctx context.Context, arg SetMessagePinnedParams) (Message, error) {
	row := q.db.QueryRow(ctx, setMessagePinned, arg.Pinned, arg.PinnedBy, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PlaceID,
		&i.AuthorID,
		&i.Content,
		&i.ReplyToID,
		&i.MentionIds,
		&i.IsPinned,
		&i.PinnedAt,
		&i.PinnedBy,
		&i.EditCount,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE messages
SET content     = $1,
    mention_ids = $2,
    edit_count  = edit_count + 1,
    edited_at   = now(),
    updated_at  = now()
WHERE id = $3
RETURNING id, channel_id, place_id, author_id, content, reply_to_id, mention_ids, is_pinned, pinned_at, pinned_by, edit_count, edited_at, created_at, updated_at
`

type UpdateMessageContentParams struct {
	Content    string
	MentionIds []uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageContent, arg.Content, arg.MentionIds, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PlaceID,
		&i.AuthorID,
		&i.Content,
		&i.ReplyToID,
		&i.MentionIds,
		&i.IsPinned,
		&i.PinnedAt,
		&i.PinnedBy,
		&i.EditCount,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
