// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createAuditEntry = `-- name: CreateAuditEntry :exec
INSERT INTO audit_log (id, place_id, actor_id, action, target_type, target_id, reason, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAuditEntryParams struct {
	ID         uuid.UUID
	PlaceID    uuid.UUID
	ActorID    *uuid.UUID
	Action     string
	TargetType string
	TargetID   *uuid.UUID
	Reason     string
	Metadata   []byte
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error {
	_, err := q.db.Exec(ctx, createAuditEntry,
		arg.ID,
		arg.PlaceID,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.Metadata,
	)
	return err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (id, place_id, reporter_id, target_type, post_id, target_user_id, reason, details, content_snapshot)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, place_id, reporter_id, target_type, post_id, target_user_id, reason, details, content_snapshot, status, resolved_by, resolved_at, resolution_note, created_at
`

type CreateReportParams struct {
	ID              uuid.UUID
	PlaceID         uuid.UUID
	ReporterID      *uuid.UUID
	TargetType      string
	PostID          *uuid.UUID
	TargetUserID    *uuid.UUID
	Reason          string
	Details         string
	ContentSnapshot string
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.PlaceID,
		arg.ReporterID,
		arg.TargetType,
		arg.PostID,
		arg.TargetUserID,
		arg.Reason,
		arg.Details,
		arg.ContentSnapshot,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.ReporterID,
		&i.TargetType,
		&i.PostID,
		&i.TargetUserID,
		&i.Reason,
		&i.Details,
		&i.ContentSnapshot,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.CreatedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, place_id, reporter_id, target_type, post_id, target_user_id, reason, details, content_snapshot, status, resolved_by, resolved_at, resolution_note, created_at FROM reports WHERE id = $1 AND place_id = $2
`

type GetReportParams struct {
	ID      uuid.UUID
	PlaceID uuid.UUID
}

func (q *Queries) GetReport(ctx context.Context, arg GetReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, getReport, arg.ID, arg.PlaceID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.ReporterID,
		&i.TargetType,
		&i.PostID,
		&i.TargetUserID,
		&i.Reason,
		&i.Details,
		&i.ContentSnapshot,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, place_id, actor_id, action, target_type, target_id, reason, metadata, created_at FROM audit_log
WHERE place_id = $1
  AND ($2::text IS NULL OR action = $2::text
       OR action LIKE $2::text || '.%')
  AND ($3::uuid IS NULL OR actor_id = $3::uuid)
  AND ($4::uuid IS NULL OR target_id = $4::uuid)
ORDER BY id DESC
LIMIT $6 OFFSET $5
`

type ListAuditLogParams struct {
	PlaceID  uuid.UUID
	Action   *string
	ActorID  *uuid.UUID
	TargetID *uuid.UUID
	Off      int32
	Lim      int32
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.PlaceID,
		arg.Action,
		arg.ActorID,
		arg.TargetID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReports = `-- name: ListReports :many
SELECT id, place_id, reporter_id, target_type, post_id, target_user_id, reason, details, content_snapshot, status, resolved_by, resolved_at, resolution_note, created_at FROM reports
WHERE place_id = $1 AND ($2::text IS NULL OR status = $2::text)
ORDER BY id DESC
LIMIT $4 OFFSET $3
`

type ListReportsParams struct {
	PlaceID uuid.UUID
	Status  *string
	Off     int32
	Lim     int32
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports,
		arg.PlaceID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.ReporterID,
			&i.TargetType,
			&i.PostID,
			&i.TargetUserID,
			&i.Reason,
			&i.Details,
			&i.ContentSnapshot,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.ResolutionNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReport = `-- name: ResolveReport :one
UPDATE reports
SET status = $1, resolved_by = $2, resolved_at = now(), resolution_note = $3
WHERE id = $4 AND place_id = $5
RETURNING id, place_id, reporter_id, target_type, post_id, target_user_id, reason, details, content_snapshot, status, resolved_by, resolved_at, resolution_note, created_at
`

type ResolveReportParams struct {
	Status         string
	ResolvedBy     *uuid.UUID
	ResolutionNote string
	ID             uuid.UUID
	PlaceID        uuid.UUID
}

func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, resolveReport,
		arg.Status,
		arg.ResolvedBy,
		arg.ResolutionNote,
		arg.ID,
		arg.PlaceID,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.ReporterID,
		&i.TargetType,
		&i.PostID,
		&i.TargetUserID,
		&i.Reason,
		&i.Details,
		&i.ContentSnapshot,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.ResolutionNote,
		&i.CreatedAt,
	)
	return i, err
}
