// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type InstanceSetting struct {
	ID               int16
	Name             string
	Description      string
	IconUrl          *string
	RegistrationMode string
	SetupToken       *string
	SetupCompletedAt *time.Time
	JwtSecret        []byte
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Invite struct {
	Code      string
	PlaceID   uuid.UUID
	CreatedBy *uuid.UUID
	MaxUses   *int32
	Uses      int32
	ExpiresAt *time.Time
	CreatedAt time.Time
}

type MemberRole struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
	RoleID  uuid.UUID
}

type Place struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Description string
	IconUrl     *string
	BannerUrl   *string
	Visibility  string
	IsNsfw      bool
	Locale      string
	OwnerID     uuid.UUID
	MemberCount int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type PlaceBan struct {
	PlaceID   uuid.UUID
	UserID    uuid.UUID
	Reason    string
	BannedBy  *uuid.UUID
	CreatedAt time.Time
}

type PlaceMember struct {
	PlaceID  uuid.UUID
	UserID   uuid.UUID
	Nickname *string
	JoinedAt time.Time
}

type Role struct {
	ID          uuid.UUID
	PlaceID     uuid.UUID
	Name        string
	Color       int32
	Position    int32
	Permissions int64
	IsDefault   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash []byte
	UserAgent        string
	IpAddress        string
	CreatedAt        time.Time
	LastUsedAt       time.Time
	ExpiresAt        time.Time
	RevokedAt        *time.Time
}

type User struct {
	ID              uuid.UUID
	Username        string
	Email           string
	PasswordHash    string
	DisplayName     string
	Bio             string
	Pronouns        string
	AvatarUrl       *string
	IsInstanceAdmin bool
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}
