// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type ApiToken struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ApplicationID *uuid.UUID
	Kind          string
	Name          string
	TokenHash     []byte
	TokenHint     string
	Scopes        []string
	CreatedAt     time.Time
	LastUsedAt    *time.Time
	ExpiresAt     *time.Time
	RevokedAt     *time.Time
}

type Application struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	BotUserID   uuid.UUID
	Name        string
	Description string
	IconUrl     *string
	IsPublic    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ApplicationCommand struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
	Name          string
	Description   string
	Options       []byte
	CreatedAt     time.Time
}

type AuditLog struct {
	ID         uuid.UUID
	PlaceID    uuid.UUID
	ActorID    *uuid.UUID
	Action     string
	TargetType string
	TargetID   *uuid.UUID
	Reason     string
	Metadata   []byte
	CreatedAt  time.Time
}

type Board struct {
	ID               uuid.UUID
	PlaceID          uuid.UUID
	ParentID         *uuid.UUID
	Kind             string
	Slug             string
	Name             string
	Description      string
	Position         int32
	ReplyMode        string
	SolutionsEnabled bool
	IsNsfw           bool
	IsPublic         bool
	TopicCount       int32
	PostCount        int32
	LastPostAt       *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type BoardOverwrite struct {
	BoardID uuid.UUID
	RoleID  uuid.UUID
	PlaceID uuid.UUID
	Allow   int64
	Deny    int64
}

type Channel struct {
	ID              uuid.UUID
	PlaceID         *uuid.UUID
	ParentID        *uuid.UUID
	Kind            string
	Name            string
	Topic           string
	Position        int32
	IsNsfw          bool
	OwnerID         *uuid.UUID
	ThreadMessageID *uuid.UUID
	IsArchived      bool
	DmKey           *string
	LastMessageID   *uuid.UUID
	LastMessageAt   *time.Time
	MessageCount    int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	UserLimit       int32
}

type ChannelOverwrite struct {
	ChannelID uuid.UUID
	RoleID    uuid.UUID
	PlaceID   uuid.UUID
	Allow     int64
	Deny      int64
}

type ChannelRead struct {
	UserID            uuid.UUID
	ChannelID         uuid.UUID
	LastReadMessageID *uuid.UUID
	MentionCount      int32
	UpdatedAt         time.Time
}

type ChannelRecipient struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
	JoinedAt  time.Time
}

type ConsentRecord struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Purpose       string
	PolicyVersion *int32
	Granted       bool
	IpAddress     string
	UserAgent     string
	CreatedAt     time.Time
}

type Draft struct {
	UserID    uuid.UUID
	Key       string
	Data      []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type InstanceSetting struct {
	ID               int16
	Name             string
	Description      string
	IconUrl          *string
	RegistrationMode string
	SetupToken       *string
	SetupCompletedAt *time.Time
	JwtSecret        []byte
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Invite struct {
	Code      string
	PlaceID   uuid.UUID
	CreatedBy *uuid.UUID
	MaxUses   *int32
	Uses      int32
	ExpiresAt *time.Time
	CreatedAt time.Time
}

type MemberRole struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
	RoleID  uuid.UUID
}

type Message struct {
	ID         uuid.UUID
	ChannelID  uuid.UUID
	PlaceID    *uuid.UUID
	AuthorID   *uuid.UUID
	Content    string
	ReplyToID  *uuid.UUID
	MentionIds []uuid.UUID
	IsPinned   bool
	PinnedAt   *time.Time
	PinnedBy   *uuid.UUID
	EditCount  int32
	EditedAt   *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type MessageReaction struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
	Emoji     string
	CreatedAt time.Time
}

type MessageRevision struct {
	ID        uuid.UUID
	MessageID uuid.UUID
	Content   string
	CreatedAt time.Time
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	PlaceID   *uuid.UUID
	TopicID   *uuid.UUID
	PostID    *uuid.UUID
	ActorID   *uuid.UUID
	Data      []byte
	ReadAt    *time.Time
	CreatedAt time.Time
	ChannelID *uuid.UUID
	MessageID *uuid.UUID
}

type Place struct {
	ID            uuid.UUID
	Slug          string
	Name          string
	Description   string
	IconUrl       *string
	BannerUrl     *string
	Visibility    string
	IsNsfw        bool
	Locale        string
	OwnerID       uuid.UUID
	MemberCount   int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	VotingEnabled bool
}

type PlaceBan struct {
	PlaceID   uuid.UUID
	UserID    uuid.UUID
	Reason    string
	BannedBy  *uuid.UUID
	CreatedAt time.Time
	ExpiresAt *time.Time
}

type PlaceMember struct {
	PlaceID       uuid.UUID
	UserID        uuid.UUID
	Nickname      *string
	JoinedAt      time.Time
	TimeoutUntil  *time.Time
	VoiceMuted    bool
	VoiceDeafened bool
}

type PolicyDocument struct {
	ID              uuid.UUID
	Kind            string
	Version         int32
	Title           string
	Content         string
	Summary         string
	RequiresConsent bool
	EffectiveAt     time.Time
	PublishedBy     *uuid.UUID
	CreatedAt       time.Time
}

type Post struct {
	ID            uuid.UUID
	TopicID       uuid.UUID
	PlaceID       uuid.UUID
	BoardID       uuid.UUID
	AuthorID      *uuid.UUID
	ParentID      *uuid.UUID
	PostNumber    int32
	Content       string
	ReactionCount int32
	EditCount     int32
	EditedAt      *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	DeletedBy     *uuid.UUID
}

type PostReaction struct {
	PostID    uuid.UUID
	UserID    uuid.UUID
	Emoji     string
	CreatedAt time.Time
}

type PostRevision struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	EditorID  *uuid.UUID
	Content   string
	CreatedAt time.Time
}

type Report struct {
	ID              uuid.UUID
	PlaceID         uuid.UUID
	ReporterID      *uuid.UUID
	TargetType      string
	PostID          *uuid.UUID
	TargetUserID    *uuid.UUID
	Reason          string
	Details         string
	ContentSnapshot string
	Status          string
	ResolvedBy      *uuid.UUID
	ResolvedAt      *time.Time
	ResolutionNote  string
	CreatedAt       time.Time
	MessageID       *uuid.UUID
	ChannelID       *uuid.UUID
}

type Role struct {
	ID          uuid.UUID
	PlaceID     uuid.UUID
	Name        string
	Color       int32
	Position    int32
	Permissions int64
	IsDefault   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SearchDocument struct {
	PostID    uuid.UUID
	Vector    interface{}
	IndexedAt time.Time
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash []byte
	UserAgent        string
	IpAddress        string
	CreatedAt        time.Time
	LastUsedAt       time.Time
	ExpiresAt        time.Time
	RevokedAt        *time.Time
}

type Subscription struct {
	UserID     uuid.UUID
	TargetType string
	TargetID   uuid.UUID
	PlaceID    *uuid.UUID
	Level      string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Topic struct {
	ID             uuid.UUID
	PlaceID        uuid.UUID
	BoardID        uuid.UUID
	AuthorID       *uuid.UUID
	Title          string
	Slug           string
	Tags           []string
	IsPinned       bool
	IsLocked       bool
	IsArchived     bool
	SolutionPostID *uuid.UUID
	PostCount      int32
	LastPostNumber int32
	LastPostAt     time.Time
	LastPosterID   *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
	DeletedBy      *uuid.UUID
	Upvotes        int32
	Downvotes      int32
	Score          int32
	HotRank        float64
	Controversy    float64
}

type TopicRead struct {
	UserID             uuid.UUID
	TopicID            uuid.UUID
	LastReadPostNumber int32
	UpdatedAt          time.Time
	OpenedAt           *time.Time
	FirstOpenedAt      *time.Time
	SeenPostNumber     int32
}

type TopicVote struct {
	TopicID   uuid.UUID
	UserID    uuid.UUID
	Value     int16
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID              uuid.UUID
	Username        string
	Email           string
	PasswordHash    string
	DisplayName     string
	Bio             string
	Pronouns        string
	AvatarUrl       *string
	IsInstanceAdmin bool
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
	IsBot           bool
}

type VoiceSession struct {
	ID               uuid.UUID
	ChannelID        uuid.UUID
	PlaceID          uuid.UUID
	UserID           uuid.UUID
	StartedAt        time.Time
	ConnectedAt      *time.Time
	EndedAt          *time.Time
	EndReason        *string
	TelemetrySamples int32
	PacketLossAvg    float64
	PacketLossMax    float64
	JitterMsAvg      float64
	RttMsAvg         float64
	BitrateKbpsAvg   float64
}

type VoiceState struct {
	UserID         uuid.UUID
	ChannelID      uuid.UUID
	PlaceID        uuid.UUID
	VoiceSessionID uuid.UUID
	AuthSessionID  uuid.UUID
	SelfMute       bool
	SelfDeaf       bool
	SelfVideo      bool
	SelfStream     bool
	ServerMute     bool
	ServerDeaf     bool
	CanSpeak       bool
	CanStream      bool
	ParticipantSid *string
	ConnectedAt    *time.Time
	JoinedAt       time.Time
	UpdatedAt      time.Time
}

type Webhook struct {
	ID                  uuid.UUID
	PlaceID             uuid.UUID
	Name                string
	Url                 string
	Secret              string
	Events              []string
	IsActive            bool
	CreatedBy           *uuid.UUID
	ConsecutiveFailures int32
	DisabledReason      string
	LastDeliveryAt      *time.Time
	LastSuccessAt       *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type WebhookDelivery struct {
	ID             uuid.UUID
	WebhookID      uuid.UUID
	Event          string
	Payload        []byte
	Status         string
	Attempts       int32
	NextAttemptAt  time.Time
	LockedUntil    *time.Time
	ResponseStatus *int32
	LastError      string
	DurationMs     *int32
	CreatedAt      time.Time
	CompletedAt    *time.Time
}
