// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countDrafts = `-- name: CountDrafts :one
SELECT count(*) FROM drafts WHERE user_id = $1
`

func (q *Queries) CountDrafts(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDrafts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDraft = `-- name: DeleteDraft :execrows
DELETE FROM drafts WHERE user_id = $1 AND key = $2
`

type DeleteDraftParams struct {
	UserID uuid.UUID
	Key    string
}

func (q *Queries) DeleteDraft(ctx context.Context, arg DeleteDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraft, arg.UserID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotification = `-- name: DeleteNotification :execrows
DELETE FROM notifications WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE user_id = $1 AND target_type = $2 AND target_id = $3
`

type DeleteSubscriptionParams struct {
	UserID     uuid.UUID
	TargetType string
	TargetID   uuid.UUID
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.UserID, arg.TargetType, arg.TargetID)
	return err
}

const deleteTargetSubscriptions = `-- name: DeleteTargetSubscriptions :exec
DELETE FROM subscriptions WHERE target_type = $1 AND target_id = $2
`

type DeleteTargetSubscriptionsParams struct {
	TargetType string
	TargetID   uuid.UUID
}

func (q *Queries) DeleteTargetSubscriptions(ctx context.Context, arg DeleteTargetSubscriptionsParams) error {
	_, err := q.db.Exec(ctx, deleteTargetSubscriptions, arg.TargetType, arg.TargetID)
	return err
}

const ensureSubscription = `-- name: EnsureSubscription :exec
INSERT INTO subscriptions (user_id, target_type, target_id, place_id, level)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type EnsureSubscriptionParams struct {
	UserID     uuid.UUID
	TargetType string
	TargetID   uuid.UUID
	PlaceID    uuid.UUID
	Level      string
}

// Adds a subscription without overriding an explicit choice.
func (q *Queries) EnsureSubscription(ctx context.Context, arg EnsureSubscriptionParams) error {
	_, err := q.db.Exec(ctx, ensureSubscription,
		arg.UserID,
		arg.TargetType,
		arg.TargetID,
		arg.PlaceID,
		arg.Level,
	)
	return err
}

const getDraft = `-- name: GetDraft :one
SELECT user_id, key, data, created_at, updated_at FROM drafts WHERE user_id = $1 AND key = $2
`

type GetDraftParams struct {
	UserID uuid.UUID
	Key    string
}

func (q *Queries) GetDraft(ctx context.Context, arg GetDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, getDraft, arg.UserID, arg.Key)
	var i Draft
	err := row.Scan(
		&i.UserID,
		&i.Key,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDrafts = `-- name: ListDrafts :many
SELECT user_id, key, data, created_at, updated_at FROM drafts WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListDrafts(ctx context.Context, userID uuid.UUID) ([]Draft, error) {
	rows, err := q.db.Query(ctx, listDrafts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Draft{}
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.UserID,
			&i.Key,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, kind, place_id, topic_id, post_id, actor_id, data, read_at, created_at FROM notifications
WHERE user_id = $1 AND (NOT $2::boolean OR read_at IS NULL)
ORDER BY id DESC
LIMIT $4 OFFSET $3
`

type ListNotificationsParams struct {
	UserID     uuid.UUID
	UnreadOnly bool
	Off        int32
	Lim        int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.PlaceID,
			&i.TopicID,
			&i.PostID,
			&i.ActorID,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsFor = `-- name: ListSubscriptionsFor :many
SELECT user_id, target_type, target_id, place_id, level, created_at, updated_at FROM subscriptions WHERE user_id = ANY($1::uuid[]) AND target_id = ANY($2::uuid[])
`

type ListSubscriptionsForParams struct {
	UserIds   []uuid.UUID
	TargetIds []uuid.UUID
}

func (q *Queries) ListSubscriptionsFor(ctx context.Context, arg ListSubscriptionsForParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsFor, arg.UserIds, arg.TargetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.UserID,
			&i.TargetType,
			&i.TargetID,
			&i.PlaceID,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSubscriptions = `-- name: ListUserSubscriptions :many
SELECT user_id, target_type, target_id, place_id, level, created_at, updated_at FROM subscriptions WHERE user_id = $1 AND target_id = ANY($2::uuid[])
`

type ListUserSubscriptionsParams struct {
	UserID    uuid.UUID
	TargetIds []uuid.UUID
}

func (q *Queries) ListUserSubscriptions(ctx context.Context, arg ListUserSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listUserSubscriptions, arg.UserID, arg.TargetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.UserID,
			&i.TargetType,
			&i.TargetID,
			&i.PlaceID,
			&i.Level,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchers = `-- name: ListWatchers :many
SELECT DISTINCT user_id FROM subscriptions WHERE level = 'watching' AND target_id = ANY($1::uuid[])
`

func (q *Queries) ListWatchers(ctx context.Context, targetIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listWatchers, targetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = COALESCE(read_at, now()) WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDraft = `-- name: UpsertDraft :exec
INSERT INTO drafts (user_id, key, data) VALUES ($1, $2, $3)
ON CONFLICT (user_id, key) DO UPDATE SET data = EXCLUDED.data, updated_at = now()
`

type UpsertDraftParams struct {
	UserID uuid.UUID
	Key    string
	Data   []byte
}

func (q *Queries) UpsertDraft(ctx context.Context, arg UpsertDraftParams) error {
	_, err := q.db.Exec(ctx, upsertDraft, arg.UserID, arg.Key, arg.Data)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (user_id, target_type, target_id, place_id, level)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, target_type, target_id) DO UPDATE SET level = EXCLUDED.level, updated_at = now()
`

type UpsertSubscriptionParams struct {
	UserID     uuid.UUID
	TargetType string
	TargetID   uuid.UUID
	PlaceID    uuid.UUID
	Level      string
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription,
		arg.UserID,
		arg.TargetType,
		arg.TargetID,
		arg.PlaceID,
		arg.Level,
	)
	return err
}
