// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: places.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const adjustMemberCount = `-- name: AdjustMemberCount :exec
UPDATE places SET member_count = member_count + $1 WHERE id = $2
`

type AdjustMemberCountParams struct {
	Delta int32
	ID    uuid.UUID
}

func (q *Queries) AdjustMemberCount(ctx context.Context, arg AdjustMemberCountParams) error {
	_, err := q.db.Exec(ctx, adjustMemberCount, arg.Delta, arg.ID)
	return err
}

const createPlace = `-- name: CreatePlace :one
INSERT INTO places (id, slug, name, description, visibility, is_nsfw, locale, owner_id, member_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 0)
RETURNING id, slug, name, description, icon_url, banner_url, visibility, is_nsfw, locale, owner_id, member_count, created_at, updated_at, deleted_at, voting_enabled
`

type CreatePlaceParams struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Description string
	Visibility  string
	IsNsfw      bool
	Locale      string
	OwnerID     uuid.UUID
}

func (q *Queries) CreatePlace(ctx context.Context, arg CreatePlaceParams) (Place, error) {
	row := q.db.QueryRow(ctx, createPlace,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.IsNsfw,
		arg.Locale,
		arg.OwnerID,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.BannerUrl,
		&i.Visibility,
		&i.IsNsfw,
		&i.Locale,
		&i.OwnerID,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.VotingEnabled,
	)
	return i, err
}

const decrementMemberCountsForUser = `-- name: DecrementMemberCountsForUser :exec
UPDATE places SET member_count = member_count - 1
WHERE id IN (SELECT place_id FROM place_members WHERE user_id = $1)
`

func (q *Queries) DecrementMemberCountsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementMemberCountsForUser, userID)
	return err
}

const getPlaceByID = `-- name: GetPlaceByID :one
SELECT id, slug, name, description, icon_url, banner_url, visibility, is_nsfw, locale, owner_id, member_count, created_at, updated_at, deleted_at, voting_enabled FROM places WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPlaceByID(ctx context.Context, id uuid.UUID) (Place, error) {
	row := q.db.QueryRow(ctx, getPlaceByID, id)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.BannerUrl,
		&i.Visibility,
		&i.IsNsfw,
		&i.Locale,
		&i.OwnerID,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.VotingEnabled,
	)
	return i, err
}

const getPlaceBySlug = `-- name: GetPlaceBySlug :one
SELECT id, slug, name, description, icon_url, banner_url, visibility, is_nsfw, locale, owner_id, member_count, created_at, updated_at, deleted_at, voting_enabled FROM places WHERE lower(slug) = lower($1) AND deleted_at IS NULL
`

func (q *Queries) GetPlaceBySlug(ctx context.Context, slug string) (Place, error) {
	row := q.db.QueryRow(ctx, getPlaceBySlug, slug)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.BannerUrl,
		&i.Visibility,
		&i.IsNsfw,
		&i.Locale,
		&i.OwnerID,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.VotingEnabled,
	)
	return i, err
}

const listDiscoverablePlaces = `-- name: ListDiscoverablePlaces :many
SELECT id, slug, name, description, icon_url, banner_url, visibility, is_nsfw, locale, owner_id, member_count, created_at, updated_at, deleted_at, voting_enabled FROM places
WHERE deleted_at IS NULL
  AND visibility <> 'private'
  AND ($1::text IS NULL
       OR name ILIKE '%' || $1::text || '%'
       OR description ILIKE '%' || $1::text || '%')
ORDER BY member_count DESC, id
LIMIT $3 OFFSET $2
`

type ListDiscoverablePlacesParams struct {
	Query *string
	Off   int32
	Lim   int32
}

func (q *Queries) ListDiscoverablePlaces(ctx context.Context, arg ListDiscoverablePlacesParams) ([]Place, error) {
	rows, err := q.db.Query(ctx, listDiscoverablePlaces, arg.Query, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Place{}
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IconUrl,
			&i.BannerUrl,
			&i.Visibility,
			&i.IsNsfw,
			&i.Locale,
			&i.OwnerID,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.VotingEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesByIDs = `-- name: ListPlacesByIDs :many
SELECT id, slug, name, description, icon_url, banner_url, visibility, is_nsfw, locale, owner_id, member_count, created_at, updated_at, deleted_at, voting_enabled FROM places WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
`

func (q *Queries) ListPlacesByIDs(ctx context.Context, ids []uuid.UUID) ([]Place, error) {
	rows, err := q.db.Query(ctx, listPlacesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Place{}
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IconUrl,
			&i.BannerUrl,
			&i.Visibility,
			&i.IsNsfw,
			&i.Locale,
			&i.OwnerID,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.VotingEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPlaces = `-- name: ListUserPlaces :many
SELECT p.id, p.slug, p.name, p.description, p.icon_url, p.banner_url, p.visibility, p.is_nsfw, p.locale, p.owner_id, p.member_count, p.created_at, p.updated_at, p.deleted_at, p.voting_enabled FROM places p
JOIN place_members m ON m.place_id = p.id
WHERE m.user_id = $1 AND p.deleted_at IS NULL
ORDER BY m.joined_at
`

func (q *Queries) ListUserPlaces(ctx context.Context, userID uuid.UUID) ([]Place, error) {
	rows, err := q.db.Query(ctx, listUserPlaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Place{}
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IconUrl,
			&i.BannerUrl,
			&i.Visibility,
			&i.IsNsfw,
			&i.Locale,
			&i.OwnerID,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.VotingEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlace = `-- name: LockPlace :one
SELECT id FROM places WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) LockPlace(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPlace, id)
	err := row.Scan(&id)
	return id, err
}

const softDeletePlace = `-- name: SoftDeletePlace :exec
UPDATE places SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeletePlace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePlace, id)
	return err
}

const transferPlaceOwnership = `-- name: TransferPlaceOwnership :exec
UPDATE places SET owner_id = $1, updated_at = now() WHERE id = $2
`

type TransferPlaceOwnershipParams struct {
	OwnerID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) TransferPlaceOwnership(ctx context.Context, arg TransferPlaceOwnershipParams) error {
	_, err := q.db.Exec(ctx, transferPlaceOwnership, arg.OwnerID, arg.ID)
	return err
}

const updatePlace = `-- name: UpdatePlace :one
UPDATE places
SET name        = COALESCE($1::text, name),
    description = COALESCE($2::text, description),
    slug        = COALESCE($3::text, slug),
    visibility  = COALESCE($4::text, visibility),
    is_nsfw     = COALESCE($5::boolean, is_nsfw),
    locale      = COALESCE($6::text, locale),
    icon_url    = CASE WHEN $7::text IS NULL THEN icon_url
                       ELSE NULLIF($7::text, '') END,
    banner_url  = CASE WHEN $8::text IS NULL THEN banner_url
                       ELSE NULLIF($8::text, '') END,
    voting_enabled = COALESCE($9::boolean, voting_enabled),
    updated_at  = now()
WHERE id = $10 AND deleted_at IS NULL
RETURNING id, slug, name, description, icon_url, banner_url, visibility, is_nsfw, locale, owner_id, member_count, created_at, updated_at, deleted_at, voting_enabled
`

type UpdatePlaceParams struct {
	Name          *string
	Description   *string
	Slug          *string
	Visibility    *string
	IsNsfw        *bool
	Locale        *string
	IconUrl       *string
	BannerUrl     *string
	VotingEnabled *bool
	ID            uuid.UUID
}

// Nullable params leave the column unchanged; empty icon/banner URLs clear them.
func (q *Queries) UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (Place, error) {
	row := q.db.QueryRow(ctx, updatePlace,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.Visibility,
		arg.IsNsfw,
		arg.Locale,
		arg.IconUrl,
		arg.BannerUrl,
		arg.VotingEnabled,
		arg.ID,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.BannerUrl,
		&i.Visibility,
		&i.IsNsfw,
		&i.Locale,
		&i.OwnerID,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.VotingEnabled,
	)
	return i, err
}
