// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const auditActionCounts = `-- name: AuditActionCounts :many
SELECT action, count(*) AS total
FROM audit_log
WHERE ($1::uuid IS NULL OR place_id = $1::uuid)
  AND action = ANY($2::text[])
  AND created_at >= $3 AND created_at < $4
GROUP BY action
`

type AuditActionCountsParams struct {
	PlaceID *uuid.UUID
	Actions []string
	Since   time.Time
	Until   time.Time
}

type AuditActionCountsRow struct {
	Action string
	Total  int64
}

func (q *Queries) AuditActionCounts(ctx context.Context, arg AuditActionCountsParams) ([]AuditActionCountsRow, error) {
	rows, err := q.db.Query(ctx, auditActionCounts,
		arg.PlaceID,
		arg.Actions,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditActionCountsRow{}
	for rows.Next() {
		var i AuditActionCountsRow
		if err := rows.Scan(&i.Action, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createConsentRecord = `-- name: CreateConsentRecord :one
INSERT INTO consent_records (id, user_id, purpose, policy_version, granted, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, purpose, policy_version, granted, ip_address, user_agent, created_at
`

type CreateConsentRecordParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Purpose       string
	PolicyVersion *int32
	Granted       bool
	IpAddress     string
	UserAgent     string
}

func (q *Queries) CreateConsentRecord(ctx context.Context, arg CreateConsentRecordParams) (ConsentRecord, error) {
	row := q.db.QueryRow(ctx, createConsentRecord,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.PolicyVersion,
		arg.Granted,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i ConsentRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.PolicyVersion,
		&i.Granted,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createPolicyDocument = `-- name: CreatePolicyDocument :one
INSERT INTO policy_documents (id, kind, version, title, content, summary, requires_consent, effective_at, published_by)
VALUES ($1, $2,
        (SELECT COALESCE(max(version), 0) + 1 FROM policy_documents WHERE kind = $2),
        $3, $4, $5, $6, $7, $8)
RETURNING id, kind, version, title, content, summary, requires_consent, effective_at, published_by, created_at
`

type CreatePolicyDocumentParams struct {
	ID              uuid.UUID
	Kind            string
	Title           string
	Content         string
	Summary         string
	RequiresConsent bool
	EffectiveAt     time.Time
	PublishedBy     *uuid.UUID
}

func (q *Queries) CreatePolicyDocument(ctx context.Context, arg CreatePolicyDocumentParams) (PolicyDocument, error) {
	row := q.db.QueryRow(ctx, createPolicyDocument,
		arg.ID,
		arg.Kind,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.RequiresConsent,
		arg.EffectiveAt,
		arg.PublishedBy,
	)
	var i PolicyDocument
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Version,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.RequiresConsent,
		&i.EffectiveAt,
		&i.PublishedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentPolicy = `-- name: GetCurrentPolicy :one
SELECT id, kind, version, title, content, summary, requires_consent, effective_at, published_by, created_at FROM policy_documents
WHERE kind = $1 AND effective_at <= now()
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetCurrentPolicy(ctx context.Context, kind string) (PolicyDocument, error) {
	row := q.db.QueryRow(ctx, getCurrentPolicy, kind)
	var i PolicyDocument
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Version,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.RequiresConsent,
		&i.EffectiveAt,
		&i.PublishedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPolicyVersion = `-- name: GetPolicyVersion :one
SELECT id, kind, version, title, content, summary, requires_consent, effective_at, published_by, created_at FROM policy_documents WHERE kind = $1 AND version = $2
`

type GetPolicyVersionParams struct {
	Kind    string
	Version int32
}

func (q *Queries) GetPolicyVersion(ctx context.Context, arg GetPolicyVersionParams) (PolicyDocument, error) {
	row := q.db.QueryRow(ctx, getPolicyVersion, arg.Kind, arg.Version)
	var i PolicyDocument
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Version,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.RequiresConsent,
		&i.EffectiveAt,
		&i.PublishedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listConsentHistory = `-- name: ListConsentHistory :many
SELECT id, user_id, purpose, policy_version, granted, ip_address, user_agent, created_at FROM consent_records
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListConsentHistoryParams struct {
	UserID uuid.UUID
	Off    int32
	Lim    int32
}

func (q *Queries) ListConsentHistory(ctx context.Context, arg ListConsentHistoryParams) ([]ConsentRecord, error) {
	rows, err := q.db.Query(ctx, listConsentHistory, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsentRecord{}
	for rows.Next() {
		var i ConsentRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Purpose,
			&i.PolicyVersion,
			&i.Granted,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentPolicies = `-- name: ListCurrentPolicies :many
SELECT DISTINCT ON (kind) id, kind, version, title, content, summary, requires_consent, effective_at, published_by, created_at
FROM policy_documents
WHERE effective_at <= now()
ORDER BY kind, version DESC
`

// The newest version of each policy that is already in effect.
func (q *Queries) ListCurrentPolicies(ctx context.Context) ([]PolicyDocument, error) {
	rows, err := q.db.Query(ctx, listCurrentPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyDocument{}
	for rows.Next() {
		var i PolicyDocument
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.RequiresConsent,
			&i.EffectiveAt,
			&i.PublishedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestConsents = `-- name: ListLatestConsents :many
SELECT DISTINCT ON (purpose) id, user_id, purpose, policy_version, granted, ip_address, user_agent, created_at
FROM consent_records
WHERE user_id = $1
ORDER BY purpose, created_at DESC, id DESC
`

func (q *Queries) ListLatestConsents(ctx context.Context, userID uuid.UUID) ([]ConsentRecord, error) {
	rows, err := q.db.Query(ctx, listLatestConsents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsentRecord{}
	for rows.Next() {
		var i ConsentRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Purpose,
			&i.PolicyVersion,
			&i.Granted,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyVersions = `-- name: ListPolicyVersions :many
SELECT id, kind, version, title, content, summary, requires_consent, effective_at, published_by, created_at FROM policy_documents WHERE kind = $1 ORDER BY version DESC
`

func (q *Queries) ListPolicyVersions(ctx context.Context, kind string) ([]PolicyDocument, error) {
	rows, err := q.db.Query(ctx, listPolicyVersions, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyDocument{}
	for rows.Next() {
		var i PolicyDocument
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.RequiresConsent,
			&i.EffectiveAt,
			&i.PublishedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportCountsByReason = `-- name: ReportCountsByReason :many
SELECT reason, count(*) AS total
FROM reports
WHERE ($1::uuid IS NULL OR place_id = $1::uuid)
  AND created_at >= $2 AND created_at < $3
GROUP BY reason
`

type ReportCountsByReasonParams struct {
	PlaceID *uuid.UUID
	Since   time.Time
	Until   time.Time
}

type ReportCountsByReasonRow struct {
	Reason string
	Total  int64
}

func (q *Queries) ReportCountsByReason(ctx context.Context, arg ReportCountsByReasonParams) ([]ReportCountsByReasonRow, error) {
	rows, err := q.db.Query(ctx, reportCountsByReason, arg.PlaceID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportCountsByReasonRow{}
	for rows.Next() {
		var i ReportCountsByReasonRow
		if err := rows.Scan(&i.Reason, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportCountsByStatus = `-- name: ReportCountsByStatus :many
SELECT status, count(*) AS total
FROM reports
WHERE ($1::uuid IS NULL OR place_id = $1::uuid)
  AND created_at >= $2 AND created_at < $3
GROUP BY status
`

type ReportCountsByStatusParams struct {
	PlaceID *uuid.UUID
	Since   time.Time
	Until   time.Time
}

type ReportCountsByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) ReportCountsByStatus(ctx context.Context, arg ReportCountsByStatusParams) ([]ReportCountsByStatusRow, error) {
	rows, err := q.db.Query(ctx, reportCountsByStatus, arg.PlaceID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportCountsByStatusRow{}
	for rows.Next() {
		var i ReportCountsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scrubUserConsents = `-- name: ScrubUserConsents :exec
UPDATE consent_records SET ip_address = '', user_agent = '' WHERE user_id = $1
`

// Consent records outlive account deletion as proof, without the network details.
func (q *Queries) ScrubUserConsents(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, scrubUserConsents, userID)
	return err
}
