// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addReaction = `-- name: AddReaction :execrows
INSERT INTO post_reactions (post_id, user_id, emoji) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddReactionParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
	Emoji  string
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, addReaction, arg.PostID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adjustReactionCount = `-- name: AdjustReactionCount :exec
UPDATE posts SET reaction_count = reaction_count + $1::integer WHERE id = $2
`

type AdjustReactionCountParams struct {
	Delta int32
	ID    uuid.UUID
}

func (q *Queries) AdjustReactionCount(ctx context.Context, arg AdjustReactionCountParams) error {
	_, err := q.db.Exec(ctx, adjustReactionCount, arg.Delta, arg.ID)
	return err
}

const countDistinctReactions = `-- name: CountDistinctReactions :one
SELECT count(DISTINCT emoji) FROM post_reactions WHERE post_id = $1
`

func (q *Queries) CountDistinctReactions(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDistinctReactions, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, topic_id, place_id, board_id, author_id, parent_id, post_number, content)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, topic_id, place_id, board_id, author_id, parent_id, post_number, content, reaction_count, edit_count, edited_at, created_at, updated_at, deleted_at, deleted_by
`

type CreatePostParams struct {
	ID         uuid.UUID
	TopicID    uuid.UUID
	PlaceID    uuid.UUID
	BoardID    uuid.UUID
	AuthorID   *uuid.UUID
	ParentID   *uuid.UUID
	PostNumber int32
	Content    string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.TopicID,
		arg.PlaceID,
		arg.BoardID,
		arg.AuthorID,
		arg.ParentID,
		arg.PostNumber,
		arg.Content,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.PlaceID,
		&i.BoardID,
		&i.AuthorID,
		&i.ParentID,
		&i.PostNumber,
		&i.Content,
		&i.ReactionCount,
		&i.EditCount,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const createPostRevision = `-- name: CreatePostRevision :exec
INSERT INTO post_revisions (id, post_id, editor_id, content) VALUES ($1, $2, $3, $4)
`

type CreatePostRevisionParams struct {
	ID       uuid.UUID
	PostID   uuid.UUID
	EditorID *uuid.UUID
	Content  string
}

func (q *Queries) CreatePostRevision(ctx context.Context, arg CreatePostRevisionParams) error {
	_, err := q.db.Exec(ctx, createPostRevision,
		arg.ID,
		arg.PostID,
		arg.EditorID,
		arg.Content,
	)
	return err
}

const deleteSearchDocument = `-- name: DeleteSearchDocument :exec
DELETE FROM search_documents WHERE post_id = $1
`

func (q *Queries) DeleteSearchDocument(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSearchDocument, postID)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, topic_id, place_id, board_id, author_id, parent_id, post_number, content, reaction_count, edit_count, edited_at, created_at, updated_at, deleted_at, deleted_by FROM posts WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.PlaceID,
		&i.BoardID,
		&i.AuthorID,
		&i.ParentID,
		&i.PostNumber,
		&i.Content,
		&i.ReactionCount,
		&i.EditCount,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getPostByNumber = `-- name: GetPostByNumber :one
SELECT id, topic_id, place_id, board_id, author_id, parent_id, post_number, content, reaction_count, edit_count, edited_at, created_at, updated_at, deleted_at, deleted_by FROM posts WHERE topic_id = $1 AND post_number = $2
`

type GetPostByNumberParams struct {
	TopicID    uuid.UUID
	PostNumber int32
}

func (q *Queries) GetPostByNumber(ctx context.Context, arg GetPostByNumberParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByNumber, arg.TopicID, arg.PostNumber)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.PlaceID,
		&i.BoardID,
		&i.AuthorID,
		&i.ParentID,
		&i.PostNumber,
		&i.Content,
		&i.ReactionCount,
		&i.EditCount,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listPostRevisions = `-- name: ListPostRevisions :many
SELECT id, post_id, editor_id, content, created_at FROM post_revisions WHERE post_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPostRevisions(ctx context.Context, postID uuid.UUID) ([]PostRevision, error) {
	rows, err := q.db.Query(ctx, listPostRevisions, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostRevision{}
	for rows.Next() {
		var i PostRevision
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.EditorID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionUsers = `-- name: ListReactionUsers :many
SELECT u.id, u.username, u.email, u.password_hash, u.display_name, u.bio, u.pronouns, u.avatar_url, u.is_instance_admin, u.email_verified_at, u.created_at, u.updated_at, u.deleted_at
FROM post_reactions r
JOIN users u ON u.id = r.user_id
WHERE r.post_id = $1 AND r.emoji = $2 AND u.deleted_at IS NULL
ORDER BY r.created_at, u.id
LIMIT $4 OFFSET $3
`

type ListReactionUsersParams struct {
	PostID uuid.UUID
	Emoji  string
	Off    int32
	Lim    int32
}

type ListReactionUsersRow struct {
	User User
}

func (q *Queries) ListReactionUsers(ctx context.Context, arg ListReactionUsersParams) ([]ListReactionUsersRow, error) {
	rows, err := q.db.Query(ctx, listReactionUsers,
		arg.PostID,
		arg.Emoji,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionUsersRow{}
	for rows.Next() {
		var i ListReactionUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.DisplayName,
			&i.User.Bio,
			&i.User.Pronouns,
			&i.User.AvatarUrl,
			&i.User.IsInstanceAdmin,
			&i.User.EmailVerifiedAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicPosts = `-- name: ListTopicPosts :many
SELECT id, topic_id, place_id, board_id, author_id, parent_id, post_number, content, reaction_count, edit_count, edited_at, created_at, updated_at, deleted_at, deleted_by FROM posts WHERE topic_id = $1 ORDER BY post_number LIMIT $3 OFFSET $2
`

type ListTopicPostsParams struct {
	TopicID uuid.UUID
	Off     int32
	Lim     int32
}

func (q *Queries) ListTopicPosts(ctx context.Context, arg ListTopicPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listTopicPosts, arg.TopicID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.PlaceID,
			&i.BoardID,
			&i.AuthorID,
			&i.ParentID,
			&i.PostNumber,
			&i.Content,
			&i.ReactionCount,
			&i.EditCount,
			&i.EditedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicPostsThreaded = `-- name: ListTopicPostsThreaded :many
WITH RECURSIVE tree AS (
    SELECT r.id, ARRAY[r.post_number] AS path
    FROM posts r
    WHERE r.topic_id = $3 AND r.parent_id IS NULL
    UNION ALL
    SELECT c.id, tree.path || c.post_number
    FROM posts c
    JOIN tree ON c.parent_id = tree.id
)
SELECT p.id, p.topic_id, p.place_id, p.board_id, p.author_id, p.parent_id, p.post_number, p.content, p.reaction_count, p.edit_count, p.edited_at, p.created_at, p.updated_at, p.deleted_at, p.deleted_by, (cardinality(tree.path) - 1)::integer AS depth
FROM tree
JOIN posts p ON p.id = tree.id
ORDER BY tree.path
LIMIT $2 OFFSET $1
`

type ListTopicPostsThreadedParams struct {
	Off     int32
	Lim     int32
	TopicID uuid.UUID
}

type ListTopicPostsThreadedRow struct {
	Post  Post
	Depth int32
}

// Depth-first order: each reply directly follows its parent, siblings oldest first.
func (q *Queries) ListTopicPostsThreaded(ctx context.Context, arg ListTopicPostsThreadedParams) ([]ListTopicPostsThreadedRow, error) {
	rows, err := q.db.Query(ctx, listTopicPostsThreaded, arg.Off, arg.Lim, arg.TopicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicPostsThreadedRow{}
	for rows.Next() {
		var i ListTopicPostsThreadedRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.TopicID,
			&i.Post.PlaceID,
			&i.Post.BoardID,
			&i.Post.AuthorID,
			&i.Post.ParentID,
			&i.Post.PostNumber,
			&i.Post.Content,
			&i.Post.ReactionCount,
			&i.Post.EditCount,
			&i.Post.EditedAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.Post.DeletedAt,
			&i.Post.DeletedBy,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postHasEmoji = `-- name: PostHasEmoji :one
SELECT EXISTS (SELECT 1 FROM post_reactions WHERE post_id = $1 AND emoji = $2)
`

type PostHasEmojiParams struct {
	PostID uuid.UUID
	Emoji  string
}

func (q *Queries) PostHasEmoji(ctx context.Context, arg PostHasEmojiParams) (bool, error) {
	row := q.db.QueryRow(ctx, postHasEmoji, arg.PostID, arg.Emoji)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reactionSummaries = `-- name: ReactionSummaries :many
SELECT post_id, emoji, count(*)::integer AS count, bool_or(user_id = $1)::boolean AS me
FROM post_reactions
WHERE post_id = ANY($2::uuid[])
GROUP BY post_id, emoji
ORDER BY post_id, min(created_at), emoji
`

type ReactionSummariesParams struct {
	ViewerID uuid.UUID
	PostIds  []uuid.UUID
}

type ReactionSummariesRow struct {
	PostID uuid.UUID
	Emoji  string
	Count  int32
	Me     bool
}

// viewer_id may be uuid.Nil for anonymous callers.
func (q *Queries) ReactionSummaries(ctx context.Context, arg ReactionSummariesParams) ([]ReactionSummariesRow, error) {
	rows, err := q.db.Query(ctx, reactionSummaries, arg.ViewerID, arg.PostIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReactionSummariesRow{}
	for rows.Next() {
		var i ReactionSummariesRow
		if err := rows.Scan(
			&i.PostID,
			&i.Emoji,
			&i.Count,
			&i.Me,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :execrows
DELETE FROM post_reactions WHERE post_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
	Emoji  string
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeReaction, arg.PostID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeletePost = `-- name: SoftDeletePost :execrows
UPDATE posts SET deleted_at = now(), deleted_by = $1, updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeletePostParams struct {
	DeletedBy *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePost, arg.DeletedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePostContent = `-- name: UpdatePostContent :one
UPDATE posts
SET content    = $1,
    edit_count = edit_count + 1,
    edited_at  = now(),
    updated_at = now()
WHERE id = $2
RETURNING id, topic_id, place_id, board_id, author_id, parent_id, post_number, content, reaction_count, edit_count, edited_at, created_at, updated_at, deleted_at, deleted_by
`

type UpdatePostContentParams struct {
	Content string
	ID      uuid.UUID
}

func (q *Queries) UpdatePostContent(ctx context.Context, arg UpdatePostContentParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePostContent, arg.Content, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.PlaceID,
		&i.BoardID,
		&i.AuthorID,
		&i.ParentID,
		&i.PostNumber,
		&i.Content,
		&i.ReactionCount,
		&i.EditCount,
		&i.EditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const upsertSearchDocument = `-- name: UpsertSearchDocument :exec
INSERT INTO search_documents (post_id, vector)
VALUES ($1, setweight(to_tsvector('simple', $2::text), 'A') ||
                  setweight(to_tsvector('simple', $3::text), 'B'))
ON CONFLICT (post_id) DO UPDATE SET vector = EXCLUDED.vector, indexed_at = now()
`

type UpsertSearchDocumentParams struct {
	PostID  uuid.UUID
	Title   string
	Content string
}

// The opening post's document also carries the topic title; pass ” for replies.
func (q *Queries) UpsertSearchDocument(ctx context.Context, arg UpsertSearchDocumentParams) error {
	_, err := q.db.Exec(ctx, upsertSearchDocument, arg.PostID, arg.Title, arg.Content)
	return err
}
