// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, place_id, name, color, position, permissions, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, place_id, name, color, position, permissions, is_default, created_at, updated_at
`

type CreateRoleParams struct {
	ID          uuid.UUID
	PlaceID     uuid.UUID
	Name        string
	Color       int32
	Position    int32
	Permissions int64
	IsDefault   bool
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.PlaceID,
		arg.Name,
		arg.Color,
		arg.Position,
		arg.Permissions,
		arg.IsDefault,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.Permissions,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1 AND place_id = $2 AND NOT is_default
`

type DeleteRoleParams struct {
	ID      uuid.UUID
	PlaceID uuid.UUID
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.PlaceID)
	return err
}

const getDefaultRole = `-- name: GetDefaultRole :one
SELECT id, place_id, name, color, position, permissions, is_default, created_at, updated_at FROM roles WHERE place_id = $1 AND is_default
`

func (q *Queries) GetDefaultRole(ctx context.Context, placeID uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getDefaultRole, placeID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.Permissions,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, place_id, name, color, position, permissions, is_default, created_at, updated_at FROM roles WHERE id = $1 AND place_id = $2
`

type GetRoleParams struct {
	ID      uuid.UUID
	PlaceID uuid.UUID
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, arg.ID, arg.PlaceID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.Permissions,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, place_id, name, color, position, permissions, is_default, created_at, updated_at FROM roles WHERE place_id = $1 ORDER BY position DESC, created_at
`

func (q *Queries) ListRoles(ctx context.Context, placeID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.Permissions,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxRolePosition = `-- name: MaxRolePosition :one
SELECT COALESCE(MAX(position), 0)::integer FROM roles WHERE place_id = $1
`

func (q *Queries) MaxRolePosition(ctx context.Context, placeID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxRolePosition, placeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const shiftRolePositions = `-- name: ShiftRolePositions :exec
UPDATE roles SET position = position + $1::integer, updated_at = now()
WHERE place_id = $2
  AND NOT is_default
  AND position BETWEEN $3::integer AND $4::integer
`

type ShiftRolePositionsParams struct {
	Delta   int32
	PlaceID uuid.UUID
	FromPos int32
	ToPos   int32
}

// Shifts non-default roles whose position lies within [from_pos, to_pos] by delta.
func (q *Queries) ShiftRolePositions(ctx context.Context, arg ShiftRolePositionsParams) error {
	_, err := q.db.Exec(ctx, shiftRolePositions,
		arg.Delta,
		arg.PlaceID,
		arg.FromPos,
		arg.ToPos,
	)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name        = COALESCE($1::text, name),
    color       = COALESCE($2::integer, color),
    permissions = COALESCE($3::bigint, permissions),
    position    = COALESCE($4::integer, position),
    updated_at  = now()
WHERE id = $5 AND place_id = $6
RETURNING id, place_id, name, color, position, permissions, is_default, created_at, updated_at
`

type UpdateRoleParams struct {
	Name        *string
	Color       *int32
	Permissions *int64
	Position    *int32
	ID          uuid.UUID
	PlaceID     uuid.UUID
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.Name,
		arg.Color,
		arg.Permissions,
		arg.Position,
		arg.ID,
		arg.PlaceID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.Permissions,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
