// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const searchPosts = `-- name: SearchPosts :many
WITH q AS (
    SELECT websearch_to_tsquery('simple', $2::text) AS tsq
),
hits AS (
    SELECT p.id,
           p.created_at,
           (ts_rank_cd(d.vector, q.tsq)::float8
                * (1 + ln(1 + p.reaction_count::float8) / 5)
                / (1 + extract(epoch FROM now() - p.created_at)::float8 / 7776000))::float8 AS rank
    FROM search_documents d
    CROSS JOIN q
    JOIN posts p ON p.id = d.post_id
    JOIN topics t ON t.id = p.topic_id
    JOIN boards b ON b.id = p.board_id
    JOIN places pl ON pl.id = p.place_id
    WHERE d.vector @@ q.tsq
      AND p.deleted_at IS NULL
      AND t.deleted_at IS NULL
      AND pl.deleted_at IS NULL
      AND (($3::boolean AND b.is_public)
           OR (NOT $3::boolean AND p.board_id = ANY($4::uuid[])))
      AND ($5::uuid IS NULL OR p.place_id = $5::uuid)
      AND ($6::uuid IS NULL OR p.board_id = $6::uuid)
      AND ($7::uuid IS NULL OR p.author_id = $7::uuid)
      AND ($8::text IS NULL OR $8::text = ANY(t.tags))
      AND ($9::boolean IS NULL
           OR (t.solution_post_id IS NOT NULL) = $9::boolean)
      AND ($10::timestamptz IS NULL OR p.created_at >= $10::timestamptz)
      AND ($11::timestamptz IS NULL OR p.created_at < $11::timestamptz)
      AND (NOT $12::boolean OR p.post_number = 1)
),
page AS (
    SELECT id, created_at, rank FROM hits
    ORDER BY CASE WHEN $1::text = 'newest' THEN hits.created_at END DESC,
             CASE WHEN $1::text = 'oldest' THEN hits.created_at END ASC,
             hits.rank DESC,
             hits.id DESC
    LIMIT $14 OFFSET $13
)
SELECT p.id, p.topic_id, p.place_id, p.board_id, p.author_id, p.parent_id, p.post_number, p.content, p.reaction_count, p.edit_count, p.edited_at, p.created_at, p.updated_at, p.deleted_at, p.deleted_by,
       t.id, t.place_id, t.board_id, t.author_id, t.title, t.slug, t.tags, t.is_pinned, t.is_locked, t.is_archived, t.solution_post_id, t.post_count, t.last_post_number, t.last_post_at, t.last_poster_id, t.created_at, t.updated_at, t.deleted_at, t.deleted_by,
       page.rank::float8 AS rank,
       ts_headline('simple', p.content, q.tsq,
                   'StartSel="**", StopSel="**", MaxWords=35, MinWords=15, MaxFragments=2, FragmentDelimiter=" … "')::text AS snippet
FROM page
CROSS JOIN q
JOIN posts p ON p.id = page.id
JOIN topics t ON t.id = p.topic_id
ORDER BY CASE WHEN $1::text = 'newest' THEN page.created_at END DESC,
         CASE WHEN $1::text = 'oldest' THEN page.created_at END ASC,
         page.rank DESC,
         page.id DESC
`

type SearchPostsParams struct {
	Sort       string
	Query      string
	PublicOnly bool
	BoardIds   []uuid.UUID
	PlaceID    *uuid.UUID
	BoardID    *uuid.UUID
	AuthorID   *uuid.UUID
	Tag        *string
	Solved     *bool
	After      *time.Time
	Before     *time.Time
	TopicsOnly bool
	Off        int32
	Lim        int32
}

type SearchPostsRow struct {
	Post    Post
	Topic   Topic
	Rank    float64
	Snippet string
}

// Full-text search over live posts. Scope is either the explicit board_ids (per-place
// search) or, with public_only, boards readable by signed-out visitors (instance-wide).
// Relevance blends text rank with reactions and recency (90-day decay scale).
func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts,
		arg.Sort,
		arg.Query,
		arg.PublicOnly,
		arg.BoardIds,
		arg.PlaceID,
		arg.BoardID,
		arg.AuthorID,
		arg.Tag,
		arg.Solved,
		arg.After,
		arg.Before,
		arg.TopicsOnly,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPostsRow{}
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.TopicID,
			&i.Post.PlaceID,
			&i.Post.BoardID,
			&i.Post.AuthorID,
			&i.Post.ParentID,
			&i.Post.PostNumber,
			&i.Post.Content,
			&i.Post.ReactionCount,
			&i.Post.EditCount,
			&i.Post.EditedAt,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.Post.DeletedAt,
			&i.Post.DeletedBy,
			&i.Topic.ID,
			&i.Topic.PlaceID,
			&i.Topic.BoardID,
			&i.Topic.AuthorID,
			&i.Topic.Title,
			&i.Topic.Slug,
			&i.Topic.Tags,
			&i.Topic.IsPinned,
			&i.Topic.IsLocked,
			&i.Topic.IsArchived,
			&i.Topic.SolutionPostID,
			&i.Topic.PostCount,
			&i.Topic.LastPostNumber,
			&i.Topic.LastPostAt,
			&i.Topic.LastPosterID,
			&i.Topic.CreatedAt,
			&i.Topic.UpdatedAt,
			&i.Topic.DeletedAt,
			&i.Topic.DeletedBy,
			&i.Rank,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
