// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selfhosting.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpConfigRevision = `-- name: BumpConfigRevision :one
UPDATE instance_settings SET config_revision = config_revision + 1, updated_at = now()
WHERE id = 1
RETURNING config_revision
`

func (q *Queries) BumpConfigRevision(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, bumpConfigRevision)
	var config_revision int64
	err := row.Scan(&config_revision)
	return config_revision, err
}

const countUploads = `-- name: CountUploads :one
SELECT count(*) AS uploads, COALESCE(sum(size_bytes), 0)::bigint AS bytes FROM uploads
`

type CountUploadsRow struct {
	Uploads int64
	Bytes   int64
}

func (q *Queries) CountUploads(ctx context.Context) (CountUploadsRow, error) {
	row := q.db.QueryRow(ctx, countUploads)
	var i CountUploadsRow
	err := row.Scan(&i.Uploads, &i.Bytes)
	return i, err
}

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (id, storage_key, url, purpose, uploader_id, content_type, size_bytes, width, height, filename)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, storage_key, url, purpose, uploader_id, content_type, size_bytes, width, height, created_at, filename
`

type CreateUploadParams struct {
	ID          uuid.UUID
	StorageKey  string
	Url         string
	Purpose     string
	UploaderID  *uuid.UUID
	ContentType string
	SizeBytes   int64
	Width       int32
	Height      int32
	Filename    string
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.ID,
		arg.StorageKey,
		arg.Url,
		arg.Purpose,
		arg.UploaderID,
		arg.ContentType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.Filename,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Url,
		&i.Purpose,
		&i.UploaderID,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.Filename,
	)
	return i, err
}

const deleteAllInstanceConfig = `-- name: DeleteAllInstanceConfig :execrows
DELETE FROM instance_config
`

func (q *Queries) DeleteAllInstanceConfig(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllInstanceConfig)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInstanceConfig = `-- name: DeleteInstanceConfig :execrows
DELETE FROM instance_config WHERE section = $1
`

func (q *Queries) DeleteInstanceConfig(ctx context.Context, section string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInstanceConfig, section)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUpload = `-- name: DeleteUpload :exec
DELETE FROM uploads WHERE id = $1
`

func (q *Queries) DeleteUpload(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUpload, id)
	return err
}

const getConfigRevision = `-- name: GetConfigRevision :one
SELECT config_revision FROM instance_settings WHERE id = 1
`

func (q *Queries) GetConfigRevision(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getConfigRevision)
	var config_revision int64
	err := row.Scan(&config_revision)
	return config_revision, err
}

const getUploadByKey = `-- name: GetUploadByKey :one
SELECT id, storage_key, url, purpose, uploader_id, content_type, size_bytes, width, height, created_at, filename FROM uploads WHERE storage_key = $1
`

func (q *Queries) GetUploadByKey(ctx context.Context, storageKey string) (Upload, error) {
	row := q.db.QueryRow(ctx, getUploadByKey, storageKey)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Url,
		&i.Purpose,
		&i.UploaderID,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.Filename,
	)
	return i, err
}

const getUploadByURL = `-- name: GetUploadByURL :one
SELECT id, storage_key, url, purpose, uploader_id, content_type, size_bytes, width, height, created_at, filename FROM uploads WHERE url = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetUploadByURL(ctx context.Context, url string) (Upload, error) {
	row := q.db.QueryRow(ctx, getUploadByURL, url)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Url,
		&i.Purpose,
		&i.UploaderID,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.Filename,
	)
	return i, err
}

const listInstanceConfig = `-- name: ListInstanceConfig :many
SELECT section, settings, updated_by, updated_at FROM instance_config ORDER BY section
`

func (q *Queries) ListInstanceConfig(ctx context.Context) ([]InstanceConfig, error) {
	rows, err := q.db.Query(ctx, listInstanceConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceConfig{}
	for rows.Next() {
		var i InstanceConfig
		if err := rows.Scan(
			&i.Section,
			&i.Settings,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreferencedUploads = `-- name: ListUnreferencedUploads :many
SELECT u.id, u.storage_key, u.url, u.purpose, u.uploader_id, u.content_type, u.size_bytes, u.width, u.height, u.created_at, u.filename FROM uploads u
WHERE u.created_at < $1
  AND NOT EXISTS (
      SELECT 1 FROM (
          SELECT avatar_url AS url FROM users WHERE avatar_url IS NOT NULL
          UNION ALL SELECT icon_url FROM places WHERE icon_url IS NOT NULL
          UNION ALL SELECT banner_url FROM places WHERE banner_url IS NOT NULL
          UNION ALL SELECT icon_url FROM instance_settings WHERE icon_url IS NOT NULL
          UNION ALL SELECT icon_url FROM applications WHERE icon_url IS NOT NULL
      ) refs
      WHERE refs.url = u.url
  )
  AND NOT EXISTS (
      SELECT 1 FROM (
          SELECT upload_id AS id FROM message_attachments
          UNION ALL SELECT upload_id FROM post_attachments
          UNION ALL SELECT image_upload_id FROM link_previews WHERE image_upload_id IS NOT NULL
      ) owned
      WHERE owned.id = u.id
  )
ORDER BY u.created_at
LIMIT $2
`

type ListUnreferencedUploadsParams struct {
	Before time.Time
	Lim    int32
}

// Uploads older than @before that nothing uses any more: replaced or cleared images,
// deleted accounts, attachments never sent or whose message or post was deleted, and
// link preview images that were replaced. One anti-join scans each referencing table once.
func (q *Queries) ListUnreferencedUploads(ctx context.Context, arg ListUnreferencedUploadsParams) ([]Upload, error) {
	rows, err := q.db.Query(ctx, listUnreferencedUploads, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Upload{}
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.Url,
			&i.Purpose,
			&i.UploaderID,
			&i.ContentType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uploadReferenced = `-- name: UploadReferenced :one
SELECT (EXISTS (SELECT 1 FROM users WHERE avatar_url = $1::text)
    OR EXISTS (SELECT 1 FROM places WHERE icon_url = $1::text OR banner_url = $1::text)
    OR EXISTS (SELECT 1 FROM instance_settings WHERE icon_url = $1::text)
    OR EXISTS (SELECT 1 FROM applications WHERE icon_url = $1::text)
    OR EXISTS (SELECT 1 FROM uploads u WHERE u.url = $1::text AND (
        EXISTS (SELECT 1 FROM message_attachments WHERE upload_id = u.id)
        OR EXISTS (SELECT 1 FROM post_attachments WHERE upload_id = u.id)
        OR EXISTS (SELECT 1 FROM link_previews WHERE image_upload_id = u.id))))::boolean AS referenced
`

func (q *Queries) UploadReferenced(ctx context.Context, url string) (bool, error) {
	row := q.db.QueryRow(ctx, uploadReferenced, url)
	var referenced bool
	err := row.Scan(&referenced)
	return referenced, err
}

const upsertInstanceConfig = `-- name: UpsertInstanceConfig :one
INSERT INTO instance_config (section, settings, updated_by, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (section) DO UPDATE
SET settings = EXCLUDED.settings, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING section, settings, updated_by, updated_at
`

type UpsertInstanceConfigParams struct {
	Section   string
	Settings  []byte
	UpdatedBy *uuid.UUID
}

func (q *Queries) UpsertInstanceConfig(ctx context.Context, arg UpsertInstanceConfigParams) (InstanceConfig, error) {
	row := q.db.QueryRow(ctx, upsertInstanceConfig, arg.Section, arg.Settings, arg.UpdatedBy)
	var i InstanceConfig
	err := row.Scan(
		&i.Section,
		&i.Settings,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
