// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActivePersonalTokens = `-- name: CountActivePersonalTokens :one
SELECT count(*) FROM api_tokens
WHERE user_id = $1 AND kind = 'personal' AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) CountActivePersonalTokens(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePersonalTokens, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (id, user_id, application_id, kind, name, token_hash, token_hint, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, application_id, kind, name, token_hash, token_hint, scopes, created_at, last_used_at, expires_at, revoked_at
`

type CreateAPITokenParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ApplicationID *uuid.UUID
	Kind          string
	Name          string
	TokenHash     []byte
	TokenHint     string
	Scopes        []string
	ExpiresAt     *time.Time
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.ApplicationID,
		arg.Kind,
		arg.Name,
		arg.TokenHash,
		arg.TokenHint,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenUser = `-- name: GetAPITokenUser :one
SELECT t.id, t.user_id, t.application_id, t.kind, t.name, t.token_hash, t.token_hint, t.scopes, t.created_at, t.last_used_at, t.expires_at, t.revoked_at, u.id, u.username, u.email, u.password_hash, u.display_name, u.bio, u.pronouns, u.avatar_url, u.is_instance_admin, u.email_verified_at, u.created_at, u.updated_at, u.deleted_at, u.is_bot
FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
  AND t.revoked_at IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > now())
  AND u.deleted_at IS NULL
`

type GetAPITokenUserRow struct {
	ApiToken ApiToken
	User     User
}

func (q *Queries) GetAPITokenUser(ctx context.Context, tokenHash []byte) (GetAPITokenUserRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenUser, tokenHash)
	var i GetAPITokenUserRow
	err := row.Scan(
		&i.ApiToken.ID,
		&i.ApiToken.UserID,
		&i.ApiToken.ApplicationID,
		&i.ApiToken.Kind,
		&i.ApiToken.Name,
		&i.ApiToken.TokenHash,
		&i.ApiToken.TokenHint,
		&i.ApiToken.Scopes,
		&i.ApiToken.CreatedAt,
		&i.ApiToken.LastUsedAt,
		&i.ApiToken.ExpiresAt,
		&i.ApiToken.RevokedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.DisplayName,
		&i.User.Bio,
		&i.User.Pronouns,
		&i.User.AvatarUrl,
		&i.User.IsInstanceAdmin,
		&i.User.EmailVerifiedAt,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.User.IsBot,
	)
	return i, err
}

const listPersonalTokens = `-- name: ListPersonalTokens :many
SELECT id, user_id, application_id, kind, name, token_hash, token_hint, scopes, created_at, last_used_at, expires_at, revoked_at FROM api_tokens
WHERE user_id = $1 AND kind = 'personal' AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPersonalTokens(ctx context.Context, userID uuid.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listPersonalTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApplicationID,
			&i.Kind,
			&i.Name,
			&i.TokenHash,
			&i.TokenHint,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApplicationTokens = `-- name: RevokeApplicationTokens :many
UPDATE api_tokens SET revoked_at = now()
WHERE application_id = $1 AND revoked_at IS NULL
RETURNING id
`

func (q *Queries) RevokeApplicationTokens(ctx context.Context, applicationID *uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeApplicationTokens, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePersonalToken = `-- name: RevokePersonalToken :execrows
UPDATE api_tokens SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND kind = 'personal' AND revoked_at IS NULL
`

type RevokePersonalTokenParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokePersonalToken(ctx context.Context, arg RevokePersonalTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePersonalToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePersonalTokens = `-- name: RevokePersonalTokens :many
UPDATE api_tokens SET revoked_at = now()
WHERE user_id = $1 AND kind = 'personal' AND revoked_at IS NULL
RETURNING id
`

func (q *Queries) RevokePersonalTokens(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokePersonalTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserTokens = `-- name: RevokeUserTokens :many
UPDATE api_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
RETURNING id
`

func (q *Queries) RevokeUserTokens(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeUserTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

// Usage is recorded at most once a minute to keep authentication cheap.
func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
