// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adjustTopicPostCount = `-- name: AdjustTopicPostCount :exec
UPDATE topics SET post_count = post_count + $1::integer WHERE id = $2
`

type AdjustTopicPostCountParams struct {
	Delta int32
	ID    uuid.UUID
}

func (q *Queries) AdjustTopicPostCount(ctx context.Context, arg AdjustTopicPostCountParams) error {
	_, err := q.db.Exec(ctx, adjustTopicPostCount, arg.Delta, arg.ID)
	return err
}

const claimPostNumber = `-- name: ClaimPostNumber :one
UPDATE topics
SET last_post_number = last_post_number + 1,
    post_count       = post_count + 1,
    last_post_at     = now(),
    last_poster_id   = $1
WHERE id = $2
RETURNING last_post_number
`

type ClaimPostNumberParams struct {
	PosterID *uuid.UUID
	ID       uuid.UUID
}

// Reserves the next post number and records the activity on the (now locked) topic row.
func (q *Queries) ClaimPostNumber(ctx context.Context, arg ClaimPostNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, claimPostNumber, arg.PosterID, arg.ID)
	var last_post_number int32
	err := row.Scan(&last_post_number)
	return last_post_number, err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (id, place_id, board_id, author_id, title, slug, tags, last_poster_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $4)
RETURNING id, place_id, board_id, author_id, title, slug, tags, is_pinned, is_locked, is_archived, solution_post_id, post_count, last_post_number, last_post_at, last_poster_id, created_at, updated_at, deleted_at, deleted_by, upvotes, downvotes, score, hot_rank, controversy
`

type CreateTopicParams struct {
	ID       uuid.UUID
	PlaceID  uuid.UUID
	BoardID  uuid.UUID
	AuthorID *uuid.UUID
	Title    string
	Slug     string
	Tags     []string
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.ID,
		arg.PlaceID,
		arg.BoardID,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Tags,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.BoardID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Tags,
		&i.IsPinned,
		&i.IsLocked,
		&i.IsArchived,
		&i.SolutionPostID,
		&i.PostCount,
		&i.LastPostNumber,
		&i.LastPostAt,
		&i.LastPosterID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Upvotes,
		&i.Downvotes,
		&i.Score,
		&i.HotRank,
		&i.Controversy,
	)
	return i, err
}

const getTopic = `-- name: GetTopic :one
SELECT id, place_id, board_id, author_id, title, slug, tags, is_pinned, is_locked, is_archived, solution_post_id, post_count, last_post_number, last_post_at, last_poster_id, created_at, updated_at, deleted_at, deleted_by, upvotes, downvotes, score, hot_rank, controversy FROM topics WHERE id = $1
`

func (q *Queries) GetTopic(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.BoardID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Tags,
		&i.IsPinned,
		&i.IsLocked,
		&i.IsArchived,
		&i.SolutionPostID,
		&i.PostCount,
		&i.LastPostNumber,
		&i.LastPostAt,
		&i.LastPosterID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Upvotes,
		&i.Downvotes,
		&i.Score,
		&i.HotRank,
		&i.Controversy,
	)
	return i, err
}

const getTopicForUpdate = `-- name: GetTopicForUpdate :one
SELECT id, place_id, board_id, author_id, title, slug, tags, is_pinned, is_locked, is_archived, solution_post_id, post_count, last_post_number, last_post_at, last_poster_id, created_at, updated_at, deleted_at, deleted_by, upvotes, downvotes, score, hot_rank, controversy FROM topics WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetTopicForUpdate(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicForUpdate, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.BoardID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Tags,
		&i.IsPinned,
		&i.IsLocked,
		&i.IsArchived,
		&i.SolutionPostID,
		&i.PostCount,
		&i.LastPostNumber,
		&i.LastPostAt,
		&i.LastPosterID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Upvotes,
		&i.Downvotes,
		&i.Score,
		&i.HotRank,
		&i.Controversy,
	)
	return i, err
}

const listBoardTopics = `-- name: ListBoardTopics :many
SELECT id, place_id, board_id, author_id, title, slug, tags, is_pinned, is_locked, is_archived, solution_post_id, post_count, last_post_number, last_post_at, last_poster_id, created_at, updated_at, deleted_at, deleted_by, upvotes, downvotes, score, hot_rank, controversy FROM topics
WHERE board_id = $1
  AND deleted_at IS NULL
  AND ($2::boolean OR NOT is_archived)
  AND ($3::text IS NULL OR $3::text = ANY(tags))
ORDER BY is_pinned DESC, last_post_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListBoardTopicsParams struct {
	BoardID         uuid.UUID
	IncludeArchived bool
	Tag             *string
	Off             int32
	Lim             int32
}

// Pinned topics first, then most recently active. Archived topics are excluded unless asked for.
func (q *Queries) ListBoardTopics(ctx context.Context, arg ListBoardTopicsParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listBoardTopics,
		arg.BoardID,
		arg.IncludeArchived,
		arg.Tag,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Tags,
			&i.IsPinned,
			&i.IsLocked,
			&i.IsArchived,
			&i.SolutionPostID,
			&i.PostCount,
			&i.LastPostNumber,
			&i.LastPostAt,
			&i.LastPosterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Upvotes,
			&i.Downvotes,
			&i.Score,
			&i.HotRank,
			&i.Controversy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceTags = `-- name: ListPlaceTags :many
SELECT tag::text AS tag, count(*)::bigint AS topic_count
FROM (
    SELECT unnest(t.tags) AS tag FROM topics t
    WHERE t.place_id = $1 AND t.deleted_at IS NULL AND t.board_id = ANY($2::uuid[])
) s
WHERE $3::text IS NULL OR tag LIKE $3::text || '%'
GROUP BY tag
ORDER BY count(*) DESC, tag
LIMIT $4
`

type ListPlaceTagsParams struct {
	PlaceID  uuid.UUID
	BoardIds []uuid.UUID
	Prefix   *string
	Lim      int32
}

type ListPlaceTagsRow struct {
	Tag        string
	TopicCount int64
}

// Tags used by live topics in the given boards, most used first. prefix must not contain
// LIKE wildcards (tags are restricted to [a-z0-9-]).
func (q *Queries) ListPlaceTags(ctx context.Context, arg ListPlaceTagsParams) ([]ListPlaceTagsRow, error) {
	rows, err := q.db.Query(ctx, listPlaceTags,
		arg.PlaceID,
		arg.BoardIds,
		arg.Prefix,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaceTagsRow{}
	for rows.Next() {
		var i ListPlaceTagsRow
		if err := rows.Scan(&i.Tag, &i.TopicCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceTopics = `-- name: ListPlaceTopics :many
SELECT id, place_id, board_id, author_id, title, slug, tags, is_pinned, is_locked, is_archived, solution_post_id, post_count, last_post_number, last_post_at, last_poster_id, created_at, updated_at, deleted_at, deleted_by, upvotes, downvotes, score, hot_rank, controversy FROM topics
WHERE place_id = $1
  AND board_id = ANY($2::uuid[])
  AND deleted_at IS NULL
  AND NOT is_archived
  AND ($3::text IS NULL OR $3::text = ANY(tags))
ORDER BY last_post_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListPlaceTopicsParams struct {
	PlaceID  uuid.UUID
	BoardIds []uuid.UUID
	Tag      *string
	Off      int32
	Lim      int32
}

// Latest activity across the given (visible) boards of a place.
func (q *Queries) ListPlaceTopics(ctx context.Context, arg ListPlaceTopicsParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listPlaceTopics,
		arg.PlaceID,
		arg.BoardIds,
		arg.Tag,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Tags,
			&i.IsPinned,
			&i.IsLocked,
			&i.IsArchived,
			&i.SolutionPostID,
			&i.PostCount,
			&i.LastPostNumber,
			&i.LastPostAt,
			&i.LastPosterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Upvotes,
			&i.Downvotes,
			&i.Score,
			&i.HotRank,
			&i.Controversy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicReads = `-- name: ListTopicReads :many
SELECT topic_id, last_read_post_number, opened_at, seen_post_number FROM topic_reads
WHERE user_id = $1 AND topic_id = ANY($2::uuid[])
`

type ListTopicReadsParams struct {
	UserID   uuid.UUID
	TopicIds []uuid.UUID
}

type ListTopicReadsRow struct {
	TopicID            uuid.UUID
	LastReadPostNumber int32
	OpenedAt           *time.Time
	SeenPostNumber     int32
}

func (q *Queries) ListTopicReads(ctx context.Context, arg ListTopicReadsParams) ([]ListTopicReadsRow, error) {
	rows, err := q.db.Query(ctx, listTopicReads, arg.UserID, arg.TopicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopicReadsRow{}
	for rows.Next() {
		var i ListTopicReadsRow
		if err := rows.Scan(
			&i.TopicID,
			&i.LastReadPostNumber,
			&i.OpenedAt,
			&i.SeenPostNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsByIDs = `-- name: ListTopicsByIDs :many
SELECT id, place_id, board_id, author_id, title, slug, tags, is_pinned, is_locked, is_archived, solution_post_id, post_count, last_post_number, last_post_at, last_poster_id, created_at, updated_at, deleted_at, deleted_by, upvotes, downvotes, score, hot_rank, controversy FROM topics WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListTopicsByIDs(ctx context.Context, ids []uuid.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopicsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Tags,
			&i.IsPinned,
			&i.IsLocked,
			&i.IsArchived,
			&i.SolutionPostID,
			&i.PostCount,
			&i.LastPostNumber,
			&i.LastPostAt,
			&i.LastPosterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.Upvotes,
			&i.Downvotes,
			&i.Score,
			&i.HotRank,
			&i.Controversy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTopicRead = `-- name: MarkTopicRead :one
INSERT INTO topic_reads (user_id, topic_id, last_read_post_number, opened_at, first_opened_at, seen_post_number)
VALUES ($1, $2, $3, now(), now(), $4)
ON CONFLICT (user_id, topic_id) DO UPDATE
SET last_read_post_number = GREATEST(topic_reads.last_read_post_number, EXCLUDED.last_read_post_number),
    opened_at             = now(),
    first_opened_at       = COALESCE(topic_reads.first_opened_at, now()),
    seen_post_number      = GREATEST(topic_reads.seen_post_number, EXCLUDED.seen_post_number),
    updated_at            = now()
RETURNING user_id, topic_id, last_read_post_number, updated_at, opened_at, first_opened_at, seen_post_number
`

type MarkTopicReadParams struct {
	UserID         uuid.UUID
	TopicID        uuid.UUID
	PostNumber     int32
	SeenPostNumber int32
}

// Records an open of the topic and advances the read position (never backwards).
// seen_post_number is the topic's last post number at this open.
func (q *Queries) MarkTopicRead(ctx context.Context, arg MarkTopicReadParams) (TopicRead, error) {
	row := q.db.QueryRow(ctx, markTopicRead,
		arg.UserID,
		arg.TopicID,
		arg.PostNumber,
		arg.SeenPostNumber,
	)
	var i TopicRead
	err := row.Scan(
		&i.UserID,
		&i.TopicID,
		&i.LastReadPostNumber,
		&i.UpdatedAt,
		&i.OpenedAt,
		&i.FirstOpenedAt,
		&i.SeenPostNumber,
	)
	return i, err
}

const moveTopicPosts = `-- name: MoveTopicPosts :exec
UPDATE posts SET board_id = $1 WHERE topic_id = $2
`

type MoveTopicPostsParams struct {
	BoardID uuid.UUID
	TopicID uuid.UUID
}

func (q *Queries) MoveTopicPosts(ctx context.Context, arg MoveTopicPostsParams) error {
	_, err := q.db.Exec(ctx, moveTopicPosts, arg.BoardID, arg.TopicID)
	return err
}

const setTopicSolution = `-- name: SetTopicSolution :one
UPDATE topics SET solution_post_id = $1::uuid, updated_at = now()
WHERE id = $2
RETURNING id, place_id, board_id, author_id, title, slug, tags, is_pinned, is_locked, is_archived, solution_post_id, post_count, last_post_number, last_post_at, last_poster_id, created_at, updated_at, deleted_at, deleted_by, upvotes, downvotes, score, hot_rank, controversy
`

type SetTopicSolutionParams struct {
	PostID *uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) SetTopicSolution(ctx context.Context, arg SetTopicSolutionParams) (Topic, error) {
	row := q.db.QueryRow(ctx, setTopicSolution, arg.PostID, arg.ID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.BoardID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Tags,
		&i.IsPinned,
		&i.IsLocked,
		&i.IsArchived,
		&i.SolutionPostID,
		&i.PostCount,
		&i.LastPostNumber,
		&i.LastPostAt,
		&i.LastPosterID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Upvotes,
		&i.Downvotes,
		&i.Score,
		&i.HotRank,
		&i.Controversy,
	)
	return i, err
}

const softDeleteTopic = `-- name: SoftDeleteTopic :exec
UPDATE topics SET deleted_at = now(), deleted_by = $1, updated_at = now() WHERE id = $2
`

type SoftDeleteTopicParams struct {
	DeletedBy *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteTopic(ctx context.Context, arg SoftDeleteTopicParams) error {
	_, err := q.db.Exec(ctx, softDeleteTopic, arg.DeletedBy, arg.ID)
	return err
}

const updateTopic = `-- name: UpdateTopic :one
UPDATE topics
SET title       = COALESCE($1::text, title),
    slug        = COALESCE($2::text, slug),
    tags        = COALESCE($3::text[], tags),
    is_pinned   = COALESCE($4::boolean, is_pinned),
    is_locked   = COALESCE($5::boolean, is_locked),
    is_archived = COALESCE($6::boolean, is_archived),
    board_id    = COALESCE($7::uuid, board_id),
    updated_at  = now()
WHERE id = $8
RETURNING id, place_id, board_id, author_id, title, slug, tags, is_pinned, is_locked, is_archived, solution_post_id, post_count, last_post_number, last_post_at, last_poster_id, created_at, updated_at, deleted_at, deleted_by, upvotes, downvotes, score, hot_rank, controversy
`

type UpdateTopicParams struct {
	Title      *string
	Slug       *string
	Tags       []string
	IsPinned   *bool
	IsLocked   *bool
	IsArchived *bool
	BoardID    *uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopic,
		arg.Title,
		arg.Slug,
		arg.Tags,
		arg.IsPinned,
		arg.IsLocked,
		arg.IsArchived,
		arg.BoardID,
		arg.ID,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.BoardID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Tags,
		&i.IsPinned,
		&i.IsLocked,
		&i.IsArchived,
		&i.SolutionPostID,
		&i.PostCount,
		&i.LastPostNumber,
		&i.LastPostAt,
		&i.LastPosterID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.Upvotes,
		&i.Downvotes,
		&i.Score,
		&i.HotRank,
		&i.Controversy,
	)
	return i, err
}
