// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const connectVoiceSession = `-- name: ConnectVoiceSession :exec
UPDATE voice_sessions SET connected_at = COALESCE(connected_at, now()) WHERE id = $1
`

func (q *Queries) ConnectVoiceSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, connectVoiceSession, id)
	return err
}

const countOtherVoiceStates = `-- name: CountOtherVoiceStates :one
SELECT count(*)::integer FROM voice_states WHERE channel_id = $1 AND user_id <> $2
`

type CountOtherVoiceStatesParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) CountOtherVoiceStates(ctx context.Context, arg CountOtherVoiceStatesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countOtherVoiceStates, arg.ChannelID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createVoiceSession = `-- name: CreateVoiceSession :one
INSERT INTO voice_sessions (id, channel_id, place_id, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, channel_id, place_id, user_id, started_at, connected_at, ended_at, end_reason, telemetry_samples, packet_loss_avg, packet_loss_max, jitter_ms_avg, rtt_ms_avg, bitrate_kbps_avg
`

type CreateVoiceSessionParams struct {
	ID        uuid.UUID
	ChannelID uuid.UUID
	PlaceID   uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) CreateVoiceSession(ctx context.Context, arg CreateVoiceSessionParams) (VoiceSession, error) {
	row := q.db.QueryRow(ctx, createVoiceSession,
		arg.ID,
		arg.ChannelID,
		arg.PlaceID,
		arg.UserID,
	)
	var i VoiceSession
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PlaceID,
		&i.UserID,
		&i.StartedAt,
		&i.ConnectedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.TelemetrySamples,
		&i.PacketLossAvg,
		&i.PacketLossMax,
		&i.JitterMsAvg,
		&i.RttMsAvg,
		&i.BitrateKbpsAvg,
	)
	return i, err
}

const deleteConnectedRoomVoiceStates = `-- name: DeleteConnectedRoomVoiceStates :many
DELETE FROM voice_states WHERE channel_id = $1 AND connected_at IS NOT NULL
RETURNING user_id, channel_id, place_id, voice_session_id, auth_session_id, self_mute, self_deaf, self_video, self_stream, server_mute, server_deaf, can_speak, can_stream, participant_sid, connected_at, joined_at, updated_at
`

func (q *Queries) DeleteConnectedRoomVoiceStates(ctx context.Context, channelID uuid.UUID) ([]VoiceState, error) {
	rows, err := q.db.Query(ctx, deleteConnectedRoomVoiceStates, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceState{}
	for rows.Next() {
		var i VoiceState
		if err := rows.Scan(
			&i.UserID,
			&i.ChannelID,
			&i.PlaceID,
			&i.VoiceSessionID,
			&i.AuthSessionID,
			&i.SelfMute,
			&i.SelfDeaf,
			&i.SelfVideo,
			&i.SelfStream,
			&i.ServerMute,
			&i.ServerDeaf,
			&i.CanSpeak,
			&i.CanStream,
			&i.ParticipantSid,
			&i.ConnectedAt,
			&i.JoinedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVoiceParticipant = `-- name: DeleteVoiceParticipant :one
DELETE FROM voice_states
WHERE user_id = $1 AND channel_id = $2 AND participant_sid = $3
RETURNING user_id, channel_id, place_id, voice_session_id, auth_session_id, self_mute, self_deaf, self_video, self_stream, server_mute, server_deaf, can_speak, can_stream, participant_sid, connected_at, joined_at, updated_at
`

type DeleteVoiceParticipantParams struct {
	UserID         uuid.UUID
	ChannelID      uuid.UUID
	ParticipantSid *string
}

// Removes the state behind a LiveKit participant that left.
func (q *Queries) DeleteVoiceParticipant(ctx context.Context, arg DeleteVoiceParticipantParams) (VoiceState, error) {
	row := q.db.QueryRow(ctx, deleteVoiceParticipant, arg.UserID, arg.ChannelID, arg.ParticipantSid)
	var i VoiceState
	err := row.Scan(
		&i.UserID,
		&i.ChannelID,
		&i.PlaceID,
		&i.VoiceSessionID,
		&i.AuthSessionID,
		&i.SelfMute,
		&i.SelfDeaf,
		&i.SelfVideo,
		&i.SelfStream,
		&i.ServerMute,
		&i.ServerDeaf,
		&i.CanSpeak,
		&i.CanStream,
		&i.ParticipantSid,
		&i.ConnectedAt,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVoiceState = `-- name: DeleteVoiceState :one
DELETE FROM voice_states WHERE user_id = $1 AND voice_session_id = $2
RETURNING user_id, channel_id, place_id, voice_session_id, auth_session_id, self_mute, self_deaf, self_video, self_stream, server_mute, server_deaf, can_speak, can_stream, participant_sid, connected_at, joined_at, updated_at
`

type DeleteVoiceStateParams struct {
	UserID         uuid.UUID
	VoiceSessionID uuid.UUID
}

// Removes one specific stay, so a stale request cannot end a newer one.
func (q *Queries) DeleteVoiceState(ctx context.Context, arg DeleteVoiceStateParams) (VoiceState, error) {
	row := q.db.QueryRow(ctx, deleteVoiceState, arg.UserID, arg.VoiceSessionID)
	var i VoiceState
	err := row.Scan(
		&i.UserID,
		&i.ChannelID,
		&i.PlaceID,
		&i.VoiceSessionID,
		&i.AuthSessionID,
		&i.SelfMute,
		&i.SelfDeaf,
		&i.SelfVideo,
		&i.SelfStream,
		&i.ServerMute,
		&i.ServerDeaf,
		&i.CanSpeak,
		&i.CanStream,
		&i.ParticipantSid,
		&i.ConnectedAt,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endOrphanedVoiceSessions = `-- name: EndOrphanedVoiceSessions :exec
UPDATE voice_sessions s SET ended_at = now(), end_reason = 'disconnected'
WHERE s.ended_at IS NULL AND s.started_at < $1
  AND NOT EXISTS (SELECT 1 FROM voice_states v WHERE v.voice_session_id = s.id)
`

// Closes sessions whose state disappeared without ending them (e.g. a crash mid-request).
func (q *Queries) EndOrphanedVoiceSessions(ctx context.Context, before time.Time) error {
	_, err := q.db.Exec(ctx, endOrphanedVoiceSessions, before)
	return err
}

const endVoiceSession = `-- name: EndVoiceSession :exec
UPDATE voice_sessions SET ended_at = now(), end_reason = $1
WHERE id = $2 AND ended_at IS NULL
`

type EndVoiceSessionParams struct {
	EndReason *string
	ID        uuid.UUID
}

func (q *Queries) EndVoiceSession(ctx context.Context, arg EndVoiceSessionParams) error {
	_, err := q.db.Exec(ctx, endVoiceSession, arg.EndReason, arg.ID)
	return err
}

const getMemberVoiceFlags = `-- name: GetMemberVoiceFlags :one
SELECT voice_muted, voice_deafened FROM place_members WHERE place_id = $1 AND user_id = $2
`

type GetMemberVoiceFlagsParams struct {
	PlaceID uuid.UUID
	UserID  uuid.UUID
}

type GetMemberVoiceFlagsRow struct {
	VoiceMuted    bool
	VoiceDeafened bool
}

func (q *Queries) GetMemberVoiceFlags(ctx context.Context, arg GetMemberVoiceFlagsParams) (GetMemberVoiceFlagsRow, error) {
	row := q.db.QueryRow(ctx, getMemberVoiceFlags, arg.PlaceID, arg.UserID)
	var i GetMemberVoiceFlagsRow
	err := row.Scan(&i.VoiceMuted, &i.VoiceDeafened)
	return i, err
}

const getVoiceState = `-- name: GetVoiceState :one
SELECT user_id, channel_id, place_id, voice_session_id, auth_session_id, self_mute, self_deaf, self_video, self_stream, server_mute, server_deaf, can_speak, can_stream, participant_sid, connected_at, joined_at, updated_at FROM voice_states WHERE user_id = $1
`

func (q *Queries) GetVoiceState(ctx context.Context, userID uuid.UUID) (VoiceState, error) {
	row := q.db.QueryRow(ctx, getVoiceState, userID)
	var i VoiceState
	err := row.Scan(
		&i.UserID,
		&i.ChannelID,
		&i.PlaceID,
		&i.VoiceSessionID,
		&i.AuthSessionID,
		&i.SelfMute,
		&i.SelfDeaf,
		&i.SelfVideo,
		&i.SelfStream,
		&i.ServerMute,
		&i.ServerDeaf,
		&i.CanSpeak,
		&i.CanStream,
		&i.ParticipantSid,
		&i.ConnectedAt,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllVoiceStates = `-- name: ListAllVoiceStates :many
SELECT user_id, channel_id, place_id, voice_session_id, auth_session_id, self_mute, self_deaf, self_video, self_stream, server_mute, server_deaf, can_speak, can_stream, participant_sid, connected_at, joined_at, updated_at FROM voice_states ORDER BY channel_id, joined_at
`

func (q *Queries) ListAllVoiceStates(ctx context.Context) ([]VoiceState, error) {
	rows, err := q.db.Query(ctx, listAllVoiceStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceState{}
	for rows.Next() {
		var i VoiceState
		if err := rows.Scan(
			&i.UserID,
			&i.ChannelID,
			&i.PlaceID,
			&i.VoiceSessionID,
			&i.AuthSessionID,
			&i.SelfMute,
			&i.SelfDeaf,
			&i.SelfVideo,
			&i.SelfStream,
			&i.ServerMute,
			&i.ServerDeaf,
			&i.CanSpeak,
			&i.CanStream,
			&i.ParticipantSid,
			&i.ConnectedAt,
			&i.JoinedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelVoiceSessions = `-- name: ListChannelVoiceSessions :many
SELECT id, channel_id, place_id, user_id, started_at, connected_at, ended_at, end_reason, telemetry_samples, packet_loss_avg, packet_loss_max, jitter_ms_avg, rtt_ms_avg, bitrate_kbps_avg FROM voice_sessions
WHERE channel_id = $1
ORDER BY started_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListChannelVoiceSessionsParams struct {
	ChannelID uuid.UUID
	Off       int32
	Lim       int32
}

func (q *Queries) ListChannelVoiceSessions(ctx context.Context, arg ListChannelVoiceSessionsParams) ([]VoiceSession, error) {
	rows, err := q.db.Query(ctx, listChannelVoiceSessions, arg.ChannelID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceSession{}
	for rows.Next() {
		var i VoiceSession
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.PlaceID,
			&i.UserID,
			&i.StartedAt,
			&i.ConnectedAt,
			&i.EndedAt,
			&i.EndReason,
			&i.TelemetrySamples,
			&i.PacketLossAvg,
			&i.PacketLossMax,
			&i.JitterMsAvg,
			&i.RttMsAvg,
			&i.BitrateKbpsAvg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelVoiceStates = `-- name: ListChannelVoiceStates :many
SELECT user_id, channel_id, place_id, voice_session_id, auth_session_id, self_mute, self_deaf, self_video, self_stream, server_mute, server_deaf, can_speak, can_stream, participant_sid, connected_at, joined_at, updated_at FROM voice_states WHERE channel_id = $1 ORDER BY joined_at, user_id
`

func (q *Queries) ListChannelVoiceStates(ctx context.Context, channelID uuid.UUID) ([]VoiceState, error) {
	rows, err := q.db.Query(ctx, listChannelVoiceStates, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceState{}
	for rows.Next() {
		var i VoiceState
		if err := rows.Scan(
			&i.UserID,
			&i.ChannelID,
			&i.PlaceID,
			&i.VoiceSessionID,
			&i.AuthSessionID,
			&i.SelfMute,
			&i.SelfDeaf,
			&i.SelfVideo,
			&i.SelfStream,
			&i.ServerMute,
			&i.ServerDeaf,
			&i.CanSpeak,
			&i.CanStream,
			&i.ParticipantSid,
			&i.ConnectedAt,
			&i.JoinedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceVoiceStates = `-- name: ListPlaceVoiceStates :many
SELECT user_id, channel_id, place_id, voice_session_id, auth_session_id, self_mute, self_deaf, self_video, self_stream, server_mute, server_deaf, can_speak, can_stream, participant_sid, connected_at, joined_at, updated_at FROM voice_states WHERE place_id = $1 ORDER BY joined_at, user_id
`

func (q *Queries) ListPlaceVoiceStates(ctx context.Context, placeID uuid.UUID) ([]VoiceState, error) {
	rows, err := q.db.Query(ctx, listPlaceVoiceStates, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceState{}
	for rows.Next() {
		var i VoiceState
		if err := rows.Scan(
			&i.UserID,
			&i.ChannelID,
			&i.PlaceID,
			&i.VoiceSessionID,
			&i.AuthSessionID,
			&i.SelfMute,
			&i.SelfDeaf,
			&i.SelfVideo,
			&i.SelfStream,
			&i.ServerMute,
			&i.ServerDeaf,
			&i.CanSpeak,
			&i.CanStream,
			&i.ParticipantSid,
			&i.ConnectedAt,
			&i.JoinedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserVoice = `-- name: LockUserVoice :exec
SELECT pg_advisory_xact_lock(hashtextextended('gotalk:voice:' || $1::text, 0))
`

// Serializes voice changes for one user (joins, moves and leaves) within a transaction.
func (q *Queries) LockUserVoice(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, lockUserVoice, userID)
	return err
}

const markVoiceConnected = `-- name: MarkVoiceConnected :one
UPDATE voice_states
SET participant_sid = $1,
    connected_at    = COALESCE(connected_at, now()),
    updated_at      = now()
WHERE user_id = $2 AND channel_id = $3
  AND ($4::uuid IS NULL OR voice_session_id = $4::uuid)
RETURNING user_id, channel_id, place_id, voice_session_id, auth_session_id, self_mute, self_deaf, self_video, self_stream, server_mute, server_deaf, can_speak, can_stream, participant_sid, connected_at, joined_at, updated_at
`

type MarkVoiceConnectedParams struct {
	ParticipantSid *string
	UserID         uuid.UUID
	ChannelID      uuid.UUID
	VoiceSessionID *uuid.UUID
}

func (q *Queries) MarkVoiceConnected(ctx context.Context, arg MarkVoiceConnectedParams) (VoiceState, error) {
	row := q.db.QueryRow(ctx, markVoiceConnected,
		arg.ParticipantSid,
		arg.UserID,
		arg.ChannelID,
		arg.VoiceSessionID,
	)
	var i VoiceState
	err := row.Scan(
		&i.UserID,
		&i.ChannelID,
		&i.PlaceID,
		&i.VoiceSessionID,
		&i.AuthSessionID,
		&i.SelfMute,
		&i.SelfDeaf,
		&i.SelfVideo,
		&i.SelfStream,
		&i.ServerMute,
		&i.ServerDeaf,
		&i.CanSpeak,
		&i.CanStream,
		&i.ParticipantSid,
		&i.ConnectedAt,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pruneVoiceSessions = `-- name: PruneVoiceSessions :exec
DELETE FROM voice_sessions WHERE ended_at < $1
`

func (q *Queries) PruneVoiceSessions(ctx context.Context, before *time.Time) error {
	_, err := q.db.Exec(ctx, pruneVoiceSessions, before)
	return err
}

const recordVoiceTelemetry = `-- name: RecordVoiceTelemetry :exec
UPDATE voice_sessions
SET packet_loss_avg   = (packet_loss_avg * telemetry_samples + $1::float8) / (telemetry_samples + 1),
    packet_loss_max   = GREATEST(packet_loss_max, $1::float8),
    jitter_ms_avg     = (jitter_ms_avg * telemetry_samples + $2::float8) / (telemetry_samples + 1),
    rtt_ms_avg        = (rtt_ms_avg * telemetry_samples + $3::float8) / (telemetry_samples + 1),
    bitrate_kbps_avg  = (bitrate_kbps_avg * telemetry_samples + $4::float8) / (telemetry_samples + 1),
    telemetry_samples = telemetry_samples + 1
WHERE id = $5 AND ended_at IS NULL
`

type RecordVoiceTelemetryParams struct {
	PacketLoss  float64
	JitterMs    float64
	RttMs       float64
	BitrateKbps float64
	ID          uuid.UUID
}

// Folds one client report into running averages.
func (q *Queries) RecordVoiceTelemetry(ctx context.Context, arg RecordVoiceTelemetryParams) error {
	_, err := q.db.Exec(ctx, recordVoiceTelemetry,
		arg.PacketLoss,
		arg.JitterMs,
		arg.RttMs,
		arg.BitrateKbps,
		arg.ID,
	)
	return err
}

const setMemberVoiceFlags = `-- name: SetMemberVoiceFlags :one
UPDATE place_members
SET voice_muted    = COALESCE($1::boolean, voice_muted),
    voice_deafened = COALESCE($2::boolean, voice_deafened)
WHERE place_id = $3 AND user_id = $4
RETURNING voice_muted, voice_deafened
`

type SetMemberVoiceFlagsParams struct {
	Muted    *bool
	Deafened *bool
	PlaceID  uuid.UUID
	UserID   uuid.UUID
}

type SetMemberVoiceFlagsRow struct {
	VoiceMuted    bool
	VoiceDeafened bool
}

func (q *Queries) SetMemberVoiceFlags(ctx context.Context, arg SetMemberVoiceFlagsParams) (SetMemberVoiceFlagsRow, error) {
	row := q.db.QueryRow(ctx, setMemberVoiceFlags,
		arg.Muted,
		arg.Deafened,
		arg.PlaceID,
		arg.UserID,
	)
	var i SetMemberVoiceFlagsRow
	err := row.Scan(&i.VoiceMuted, &i.VoiceDeafened)
	return i, err
}

const tryVoiceSweepLock = `-- name: TryVoiceSweepLock :one
SELECT pg_try_advisory_xact_lock(hashtextextended('gotalk:voice:sweep', 0))
`

// Lets one replica at a time reconcile voice states with LiveKit.
func (q *Queries) TryVoiceSweepLock(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tryVoiceSweepLock)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}

const updateVoiceGrant = `-- name: UpdateVoiceGrant :one
UPDATE voice_states
SET server_mute = $1,
    server_deaf = $2,
    can_speak   = $3,
    can_stream  = $4,
    self_video  = self_video AND $4,
    self_stream = self_stream AND $4,
    updated_at  = now()
WHERE user_id = $5 AND voice_session_id = $6
RETURNING user_id, channel_id, place_id, voice_session_id, auth_session_id, self_mute, self_deaf, self_video, self_stream, server_mute, server_deaf, can_speak, can_stream, participant_sid, connected_at, joined_at, updated_at
`

type UpdateVoiceGrantParams struct {
	ServerMute     bool
	ServerDeaf     bool
	CanSpeak       bool
	CanStream      bool
	UserID         uuid.UUID
	VoiceSessionID uuid.UUID
}

// Losing the right to stream also turns the stream flags off.
func (q *Queries) UpdateVoiceGrant(ctx context.Context, arg UpdateVoiceGrantParams) (VoiceState, error) {
	row := q.db.QueryRow(ctx, updateVoiceGrant,
		arg.ServerMute,
		arg.ServerDeaf,
		arg.CanSpeak,
		arg.CanStream,
		arg.UserID,
		arg.VoiceSessionID,
	)
	var i VoiceState
	err := row.Scan(
		&i.UserID,
		&i.ChannelID,
		&i.PlaceID,
		&i.VoiceSessionID,
		&i.AuthSessionID,
		&i.SelfMute,
		&i.SelfDeaf,
		&i.SelfVideo,
		&i.SelfStream,
		&i.ServerMute,
		&i.ServerDeaf,
		&i.CanSpeak,
		&i.CanStream,
		&i.ParticipantSid,
		&i.ConnectedAt,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVoiceSelf = `-- name: UpdateVoiceSelf :one
UPDATE voice_states
SET self_mute   = COALESCE($1::boolean, self_mute),
    self_deaf   = COALESCE($2::boolean, self_deaf),
    self_video  = COALESCE($3::boolean, self_video),
    self_stream = COALESCE($4::boolean, self_stream),
    updated_at  = now()
WHERE user_id = $5
RETURNING user_id, channel_id, place_id, voice_session_id, auth_session_id, self_mute, self_deaf, self_video, self_stream, server_mute, server_deaf, can_speak, can_stream, participant_sid, connected_at, joined_at, updated_at
`

type UpdateVoiceSelfParams struct {
	SelfMute   *bool
	SelfDeaf   *bool
	SelfVideo  *bool
	SelfStream *bool
	UserID     uuid.UUID
}

func (q *Queries) UpdateVoiceSelf(ctx context.Context, arg UpdateVoiceSelfParams) (VoiceState, error) {
	row := q.db.QueryRow(ctx, updateVoiceSelf,
		arg.SelfMute,
		arg.SelfDeaf,
		arg.SelfVideo,
		arg.SelfStream,
		arg.UserID,
	)
	var i VoiceState
	err := row.Scan(
		&i.UserID,
		&i.ChannelID,
		&i.PlaceID,
		&i.VoiceSessionID,
		&i.AuthSessionID,
		&i.SelfMute,
		&i.SelfDeaf,
		&i.SelfVideo,
		&i.SelfStream,
		&i.ServerMute,
		&i.ServerDeaf,
		&i.CanSpeak,
		&i.CanStream,
		&i.ParticipantSid,
		&i.ConnectedAt,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertVoiceState = `-- name: UpsertVoiceState :one
INSERT INTO voice_states (user_id, channel_id, place_id, voice_session_id, auth_session_id,
                          self_mute, self_deaf, server_mute, server_deaf, can_speak, can_stream)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10, $11)
ON CONFLICT (user_id) DO UPDATE
SET channel_id       = EXCLUDED.channel_id,
    place_id         = EXCLUDED.place_id,
    voice_session_id = EXCLUDED.voice_session_id,
    auth_session_id  = EXCLUDED.auth_session_id,
    self_mute        = EXCLUDED.self_mute,
    self_deaf        = EXCLUDED.self_deaf,
    self_video       = false,
    self_stream      = false,
    server_mute      = EXCLUDED.server_mute,
    server_deaf      = EXCLUDED.server_deaf,
    can_speak        = EXCLUDED.can_speak,
    can_stream       = EXCLUDED.can_stream,
    participant_sid  = NULL,
    connected_at     = NULL,
    joined_at        = now(),
    updated_at       = now()
RETURNING user_id, channel_id, place_id, voice_session_id, auth_session_id, self_mute, self_deaf, self_video, self_stream, server_mute, server_deaf, can_speak, can_stream, participant_sid, connected_at, joined_at, updated_at
`

type UpsertVoiceStateParams struct {
	UserID         uuid.UUID
	ChannelID      uuid.UUID
	PlaceID        uuid.UUID
	VoiceSessionID uuid.UUID
	AuthSessionID  uuid.UUID
	SelfMute       bool
	SelfDeaf       bool
	ServerMute     bool
	ServerDeaf     bool
	CanSpeak       bool
	CanStream      bool
}

// A new stay in a voice channel; replaces any previous state of the user.
func (q *Queries) UpsertVoiceState(ctx context.Context, arg UpsertVoiceStateParams) (VoiceState, error) {
	row := q.db.QueryRow(ctx, upsertVoiceState,
		arg.UserID,
		arg.ChannelID,
		arg.PlaceID,
		arg.VoiceSessionID,
		arg.AuthSessionID,
		arg.SelfMute,
		arg.SelfDeaf,
		arg.ServerMute,
		arg.ServerDeaf,
		arg.CanSpeak,
		arg.CanStream,
	)
	var i VoiceState
	err := row.Scan(
		&i.UserID,
		&i.ChannelID,
		&i.PlaceID,
		&i.VoiceSessionID,
		&i.AuthSessionID,
		&i.SelfMute,
		&i.SelfDeaf,
		&i.SelfVideo,
		&i.SelfStream,
		&i.ServerMute,
		&i.ServerDeaf,
		&i.CanSpeak,
		&i.CanStream,
		&i.ParticipantSid,
		&i.ConnectedAt,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}
