// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelPendingDeliveries = `-- name: CancelPendingDeliveries :exec
UPDATE webhook_deliveries
SET status = 'failed', last_error = $1, completed_at = now(), locked_until = NULL
WHERE webhook_id = $2 AND status = 'pending'
`

type CancelPendingDeliveriesParams struct {
	Reason    string
	WebhookID uuid.UUID
}

func (q *Queries) CancelPendingDeliveries(ctx context.Context, arg CancelPendingDeliveriesParams) error {
	_, err := q.db.Exec(ctx, cancelPendingDeliveries, arg.Reason, arg.WebhookID)
	return err
}

const claimWebhookDeliveries = `-- name: ClaimWebhookDeliveries :many
UPDATE webhook_deliveries
SET locked_until = now() + make_interval(secs => $1::integer),
    attempts     = attempts + 1
WHERE id IN (
    SELECT d.id
    FROM webhook_deliveries d
    JOIN webhooks w ON w.id = d.webhook_id
    WHERE d.status = 'pending' AND w.is_active
      AND d.next_attempt_at <= now()
      AND (d.locked_until IS NULL OR d.locked_until < now())
    ORDER BY d.next_attempt_at
    LIMIT $2
    FOR UPDATE OF d SKIP LOCKED
)
RETURNING id, webhook_id, event, payload, status, attempts, next_attempt_at, locked_until, response_status, last_error, duration_ms, created_at, completed_at
`

type ClaimWebhookDeliveriesParams struct {
	LockSeconds int32
	Lim         int32
}

// Locks due deliveries of active webhooks for this replica. SKIP LOCKED lets several
// replicas drain the queue without delivering anything twice.
func (q *Queries) ClaimWebhookDeliveries(ctx context.Context, arg ClaimWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimWebhookDeliveries, arg.LockSeconds, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.ResponseStatus,
			&i.LastError,
			&i.DurationMs,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWebhooks = `-- name: CountWebhooks :one
SELECT count(*) FROM webhooks WHERE place_id = $1
`

func (q *Queries) CountWebhooks(ctx context.Context, placeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhooks, placeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (id, place_id, name, url, secret, events, is_active, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, place_id, name, url, secret, events, is_active, created_by, consecutive_failures, disabled_reason, last_delivery_at, last_success_at, created_at, updated_at
`

type CreateWebhookParams struct {
	ID        uuid.UUID
	PlaceID   uuid.UUID
	Name      string
	Url       string
	Secret    string
	Events    []string
	IsActive  bool
	CreatedBy *uuid.UUID
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.ID,
		arg.PlaceID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedBy,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.LastDeliveryAt,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (id, webhook_id, event, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, webhook_id, event, payload, status, attempts, next_attempt_at, locked_until, response_status, last_error, duration_ms, created_at, completed_at
`

type CreateWebhookDeliveryParams struct {
	ID        uuid.UUID
	WebhookID uuid.UUID
	Event     string
	Payload   []byte
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.ID,
		arg.WebhookID,
		arg.Event,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.ResponseStatus,
		&i.LastError,
		&i.DurationMs,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteOldWebhookDeliveries = `-- name: DeleteOldWebhookDeliveries :execrows
DELETE FROM webhook_deliveries WHERE completed_at < $1
`

func (q *Queries) DeleteOldWebhookDeliveries(ctx context.Context, before *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldWebhookDeliveries, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const disableWebhook = `-- name: DisableWebhook :execrows
UPDATE webhooks
SET is_active = false, disabled_reason = $1, updated_at = now()
WHERE id = $2 AND is_active
`

type DisableWebhookParams struct {
	DisabledReason string
	ID             uuid.UUID
}

func (q *Queries) DisableWebhook(ctx context.Context, arg DisableWebhookParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableWebhook, arg.DisabledReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishWebhookAttempt = `-- name: FinishWebhookAttempt :one
UPDATE webhook_deliveries
SET status          = $1,
    next_attempt_at = $2,
    locked_until    = NULL,
    response_status = $3,
    last_error      = $4,
    duration_ms     = $5,
    completed_at    = CASE WHEN $1::text = 'pending' THEN NULL ELSE now() END
WHERE id = $6
RETURNING id, webhook_id, event, payload, status, attempts, next_attempt_at, locked_until, response_status, last_error, duration_ms, created_at, completed_at
`

type FinishWebhookAttemptParams struct {
	Status         string
	NextAttemptAt  time.Time
	ResponseStatus *int32
	LastError      string
	DurationMs     *int32
	ID             uuid.UUID
}

func (q *Queries) FinishWebhookAttempt(ctx context.Context, arg FinishWebhookAttemptParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, finishWebhookAttempt,
		arg.Status,
		arg.NextAttemptAt,
		arg.ResponseStatus,
		arg.LastError,
		arg.DurationMs,
		arg.ID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.ResponseStatus,
		&i.LastError,
		&i.DurationMs,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, place_id, name, url, secret, events, is_active, created_by, consecutive_failures, disabled_reason, last_delivery_at, last_success_at, created_at, updated_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedBy,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.LastDeliveryAt,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, webhook_id, event, payload, status, attempts, next_attempt_at, locked_until, response_status, last_error, duration_ms, created_at, completed_at FROM webhook_deliveries WHERE id = $1 AND webhook_id = $2
`

type GetWebhookDeliveryParams struct {
	ID        uuid.UUID
	WebhookID uuid.UUID
}

func (q *Queries) GetWebhookDelivery(ctx context.Context, arg GetWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, arg.ID, arg.WebhookID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.ResponseStatus,
		&i.LastError,
		&i.DurationMs,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, webhook_id, event, payload, status, attempts, next_attempt_at, locked_until, response_status, last_error, duration_ms, created_at, completed_at FROM webhook_deliveries
WHERE webhook_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY id DESC
LIMIT $4 OFFSET $3
`

type ListWebhookDeliveriesParams struct {
	WebhookID uuid.UUID
	Status    *string
	Off       int32
	Lim       int32
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries,
		arg.WebhookID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.ResponseStatus,
			&i.LastError,
			&i.DurationMs,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, place_id, name, url, secret, events, is_active, created_by, consecutive_failures, disabled_reason, last_delivery_at, last_success_at, created_at, updated_at FROM webhooks WHERE place_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListWebhooks(ctx context.Context, placeID uuid.UUID) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.CreatedBy,
			&i.ConsecutiveFailures,
			&i.DisabledReason,
			&i.LastDeliveryAt,
			&i.LastSuccessAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksForEvent = `-- name: ListWebhooksForEvent :many
SELECT id, place_id, name, url, secret, events, is_active, created_by, consecutive_failures, disabled_reason, last_delivery_at, last_success_at, created_at, updated_at FROM webhooks WHERE place_id = $1 AND is_active AND $2::text = ANY(events)
`

type ListWebhooksForEventParams struct {
	PlaceID uuid.UUID
	Event   string
}

func (q *Queries) ListWebhooksForEvent(ctx context.Context, arg ListWebhooksForEventParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksForEvent, arg.PlaceID, arg.Event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.CreatedBy,
			&i.ConsecutiveFailures,
			&i.DisabledReason,
			&i.LastDeliveryAt,
			&i.LastSuccessAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWebhookAttemptFailure = `-- name: RecordWebhookAttemptFailure :exec
UPDATE webhooks SET last_delivery_at = now() WHERE id = $1
`

func (q *Queries) RecordWebhookAttemptFailure(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordWebhookAttemptFailure, id)
	return err
}

const recordWebhookFailure = `-- name: RecordWebhookFailure :one
UPDATE webhooks
SET consecutive_failures = consecutive_failures + 1, last_delivery_at = now()
WHERE id = $1
RETURNING consecutive_failures
`

func (q *Queries) RecordWebhookFailure(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, recordWebhookFailure, id)
	var consecutive_failures int32
	err := row.Scan(&consecutive_failures)
	return consecutive_failures, err
}

const recordWebhookSuccess = `-- name: RecordWebhookSuccess :exec
UPDATE webhooks
SET consecutive_failures = 0, last_delivery_at = now(), last_success_at = now()
WHERE id = $1
`

func (q *Queries) RecordWebhookSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordWebhookSuccess, id)
	return err
}

const rotateWebhookSecret = `-- name: RotateWebhookSecret :one
UPDATE webhooks SET secret = $1, updated_at = now() WHERE id = $2 RETURNING id, place_id, name, url, secret, events, is_active, created_by, consecutive_failures, disabled_reason, last_delivery_at, last_success_at, created_at, updated_at
`

type RotateWebhookSecretParams struct {
	Secret string
	ID     uuid.UUID
}

func (q *Queries) RotateWebhookSecret(ctx context.Context, arg RotateWebhookSecretParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, rotateWebhookSecret, arg.Secret, arg.ID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedBy,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.LastDeliveryAt,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET name                 = COALESCE($1::text, name),
    url                  = COALESCE($2::text, url),
    events               = COALESCE($3::text[], events),
    is_active            = COALESCE($4::boolean, is_active),
    consecutive_failures = CASE WHEN $4::boolean THEN 0 ELSE consecutive_failures END,
    disabled_reason      = CASE WHEN $4::boolean IS NULL THEN disabled_reason
                                WHEN $4::boolean THEN ''
                                ELSE 'disabled by a moderator' END,
    updated_at           = now()
WHERE id = $5
RETURNING id, place_id, name, url, secret, events, is_active, created_by, consecutive_failures, disabled_reason, last_delivery_at, last_success_at, created_at, updated_at
`

type UpdateWebhookParams struct {
	Name     *string
	Url      *string
	Events   []string
	IsActive *bool
	ID       uuid.UUID
}

// Nullable params leave the column unchanged. Re-activating clears the failure streak.
func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.Name,
		arg.Url,
		arg.Events,
		arg.IsActive,
		arg.ID,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedBy,
		&i.ConsecutiveFailures,
		&i.DisabledReason,
		&i.LastDeliveryAt,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
